//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

/**
 * Map of normalized account addresses to their blockchain states.
 * Every address passed to a batched account-state fetch is guaranteed to have a key in this map. Accounts that don't exist on chain are represented by an `AccountState` with `status: 'non-existing'`. Keys are normalized via `asAddressFriendly`, regardless of the input format.
 */
public class TONAccountStates {

    /** Builds one of these from JSON. */
    public static final Parser<TONAccountStates> PARSER = new Parser<TONAccountStates>() {
        @Override
        public TONAccountStates parse(JSONObject json) {
            return fromJson(json);
        }
    };

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONAccountStates fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONAccountStates out = new TONAccountStates();
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
