//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

/** TON Proof request item. */
public class TONConnectionRequestTonProofRequestedItem {

    /** Builds one of these from JSON. */
    public static final Parser<TONConnectionRequestTonProofRequestedItem> PARSER = new Parser<TONConnectionRequestTonProofRequestedItem>() {
        @Override
        public TONConnectionRequestTonProofRequestedItem parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private String payload;

    /** Required by the API. */
    public String getPayload() {
        return payload;
    }

    public TONConnectionRequestTonProofRequestedItem setPayload(String value) {
        this.payload = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "payload", payload);
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONConnectionRequestTonProofRequestedItem fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONConnectionRequestTonProofRequestedItem out = new TONConnectionRequestTonProofRequestedItem();
        out.payload = TonApiJson.optString(json, "payload");
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
