/*
 * TON WalletKit models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ton.walletkit.api;

import java.util.Objects;
import java.math.BigDecimal;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Copyright (c) TonTech.  This source code is licensed under the MIT license found in the LICENSE file in the root directory of this source tree.
 */
@JsonAdapter(TONCONNECTEVENTERRORCODES.Adapter.class)
public enum TONCONNECTEVENTERRORCODES {
  
  NUMBER_0(new BigDecimal("0")),
  
  NUMBER_1(new BigDecimal("1")),
  
  NUMBER_2(new BigDecimal("2")),
  
  NUMBER_3(new BigDecimal("3")),
  
  NUMBER_100(new BigDecimal("100")),
  
  NUMBER_300(new BigDecimal("300")),
  
  NUMBER_400(new BigDecimal("400"));

  private BigDecimal value;

  TONCONNECTEVENTERRORCODES(BigDecimal value) {
    this.value = value;
  }

  public BigDecimal getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TONCONNECTEVENTERRORCODES fromValue(BigDecimal value) {
    for (TONCONNECTEVENTERRORCODES b : TONCONNECTEVENTERRORCODES.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<TONCONNECTEVENTERRORCODES> {
    @Override
    public void write(final JsonWriter jsonWriter, final TONCONNECTEVENTERRORCODES enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TONCONNECTEVENTERRORCODES read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TONCONNECTEVENTERRORCODES.fromValue(new BigDecimal(value));
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    TONCONNECTEVENTERRORCODES.fromValue(new BigDecimal(value));
  }
}

