//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

/** Discriminator for DeFi-style providers (swap quotes, staking, gasless relayers). */
public enum TONDefiProviderType {

    SWAP("swap"),
    STAKING("staking"),
    GASLESS("gasless");

    /** Reads one of these from a wire value; for arrays of this enum. */
    public static final EnumParser<TONDefiProviderType> VALUES = new EnumParser<TONDefiProviderType>() {
        @Override
        public TONDefiProviderType parse(Object wire) {
            return fromValue(wire);
        }
    };

    private final String value;

    TONDefiProviderType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    /** The constant for a wire value, or null if it is absent or unknown. */
    public static TONDefiProviderType fromValue(Object wire) {
        if (wire == null) {
            return null;
        }
        String text = wire.toString();
        for (TONDefiProviderType candidate : values()) {
            if (candidate.value.equals(text)) {
                return candidate;
            }
        }
        return null;
    }
}
