//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

/** Information about a decentralized application (dApp) connecting via TON Connect. */
public class TONDAppInfo {

    /** Builds one of these from JSON. */
    public static final Parser<TONDAppInfo> PARSER = new Parser<TONDAppInfo>() {
        @Override
        public TONDAppInfo parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private String description;
    private String iconUrl;
    private String manifestUrl;
    private String name;
    private String url;

    /** Brief description of the dApp's purpose */
    public String getDescription() {
        return description;
    }

    public TONDAppInfo setDescription(String value) {
        this.description = value;
        return this;
    }

    /** Icon/logo URL of the dApp */
    public String getIconUrl() {
        return iconUrl;
    }

    public TONDAppInfo setIconUrl(String value) {
        this.iconUrl = value;
        return this;
    }

    /** Manifest URL of the dApp */
    public String getManifestUrl() {
        return manifestUrl;
    }

    public TONDAppInfo setManifestUrl(String value) {
        this.manifestUrl = value;
        return this;
    }

    /** Display name of the dApp */
    public String getName() {
        return name;
    }

    public TONDAppInfo setName(String value) {
        this.name = value;
        return this;
    }

    /** Main website URL of the dApp */
    public String getUrl() {
        return url;
    }

    public TONDAppInfo setUrl(String value) {
        this.url = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "description", description);
        TonApiJson.put(json, "iconUrl", iconUrl);
        TonApiJson.put(json, "manifestUrl", manifestUrl);
        TonApiJson.put(json, "name", name);
        TonApiJson.put(json, "url", url);
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONDAppInfo fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONDAppInfo out = new TONDAppInfo();
        out.description = TonApiJson.optString(json, "description");
        out.iconUrl = TonApiJson.optString(json, "iconUrl");
        out.manifestUrl = TonApiJson.optString(json, "manifestUrl");
        out.name = TonApiJson.optString(json, "name");
        out.url = TonApiJson.optString(json, "url");
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
