//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

/**
 * A union: {@code method} says which variant this is, and the matching
 * accessor returns it. An unrecognised method leaves the value as the raw
 * JSON rather than failing, so a new variant upstream does not break a
 * response that merely contains one.
 */
public class TONEmbeddedRequest {

    public static final Parser<TONEmbeddedRequest> PARSER = new Parser<TONEmbeddedRequest>() {
        @Override
        public TONEmbeddedRequest parse(JSONObject json) {
            return fromJson(json);
        }
    };

    public static final String SEND_TRANSACTION = "sendTransaction";
    public static final String SIGN_MESSAGE = "signMessage";
    public static final String SIGN_DATA = "signData";

    private String method;
    private Object value;

    /** Which variant this is; one of the constants above. */
    public String getMethod() {
        return method;
    }

    /** The variant, typed by {@code method}, or the raw JSON if unrecognised. */
    public Object getValue() {
        return value;
    }

    /** The value when {@code method} is {@code sendTransaction}, else null. */
    public TONSendTransactionEmbeddedRequest asSendTransaction() {
        return value instanceof TONSendTransactionEmbeddedRequest ? (TONSendTransactionEmbeddedRequest) value : null;
    }

    /** The value when {@code method} is {@code signMessage}, else null. */
    public TONSignMessageEmbeddedRequest asSignMessage() {
        return value instanceof TONSignMessageEmbeddedRequest ? (TONSignMessageEmbeddedRequest) value : null;
    }

    /** The value when {@code method} is {@code signData}, else null. */
    public TONSignDataEmbeddedRequest asSignData() {
        return value instanceof TONSignDataEmbeddedRequest ? (TONSignDataEmbeddedRequest) value : null;
    }

    public JSONObject toJson() {
        Object encoded = asJson(value);
        JSONObject json = encoded instanceof JSONObject ? (JSONObject) encoded : new JSONObject();
        TonApiJson.put(json, "method", method);
        return json;
    }

    private static Object asJson(Object value) {
        if (value instanceof TONSendTransactionEmbeddedRequest) {
            return ((TONSendTransactionEmbeddedRequest) value).toJson();
        }
        if (value instanceof TONSignMessageEmbeddedRequest) {
            return ((TONSignMessageEmbeddedRequest) value).toJson();
        }
        if (value instanceof TONSignDataEmbeddedRequest) {
            return ((TONSignDataEmbeddedRequest) value).toJson();
        }
        return value;
    }

    public static TONEmbeddedRequest fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONEmbeddedRequest out = new TONEmbeddedRequest();
        out.method = TonApiJson.optString(json, "method");
        JSONObject payload = json;
        if (SEND_TRANSACTION.equals(out.method)) {
            out.value = TONSendTransactionEmbeddedRequest.fromJson(payload);
        } else if (SIGN_MESSAGE.equals(out.method)) {
            out.value = TONSignMessageEmbeddedRequest.fromJson(payload);
        } else if (SIGN_DATA.equals(out.method)) {
            out.value = TONSignDataEmbeddedRequest.fromJson(payload);
        } else {
            out.value = payload;
        }
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
