/*
 * TON WalletKit models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ton.walletkit.api;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.ton.walletkit.api.JSON;

/**
 * High-level action extracted from an emulated transaction trace.
 */
public class TONEmulationAction {
  public static final String SERIALIZED_NAME_ACCOUNTS = "accounts";
  @SerializedName(SERIALIZED_NAME_ACCOUNTS)
  private List<String> accounts = new ArrayList<>();

  public static final String SERIALIZED_NAME_DETAILS = "details";
  @SerializedName(SERIALIZED_NAME_DETAILS)
  private Map<String, Object> details = new HashMap<>();

  public static final String SERIALIZED_NAME_END_LT = "endLt";
  @SerializedName(SERIALIZED_NAME_END_LT)
  private String endLt;

  public static final String SERIALIZED_NAME_END_UTIME = "endUtime";
  @SerializedName(SERIALIZED_NAME_END_UTIME)
  private BigDecimal endUtime;

  public static final String SERIALIZED_NAME_IS_SUCCESS = "isSuccess";
  @SerializedName(SERIALIZED_NAME_IS_SUCCESS)
  private Boolean isSuccess;

  public static final String SERIALIZED_NAME_START_LT = "startLt";
  @SerializedName(SERIALIZED_NAME_START_LT)
  private String startLt;

  public static final String SERIALIZED_NAME_START_UTIME = "startUtime";
  @SerializedName(SERIALIZED_NAME_START_UTIME)
  private BigDecimal startUtime;

  public static final String SERIALIZED_NAME_TRACE_END_LT = "traceEndLt";
  @SerializedName(SERIALIZED_NAME_TRACE_END_LT)
  private String traceEndLt;

  public static final String SERIALIZED_NAME_TRACE_END_UTIME = "traceEndUtime";
  @SerializedName(SERIALIZED_NAME_TRACE_END_UTIME)
  private BigDecimal traceEndUtime;

  public static final String SERIALIZED_NAME_TRACE_ID = "traceId";
  @SerializedName(SERIALIZED_NAME_TRACE_ID)
  private String traceId;

  public static final String SERIALIZED_NAME_TRACE_MC_SEQNO_END = "traceMcSeqnoEnd";
  @SerializedName(SERIALIZED_NAME_TRACE_MC_SEQNO_END)
  private BigDecimal traceMcSeqnoEnd;

  public static final String SERIALIZED_NAME_TRANSACTIONS = "transactions";
  @SerializedName(SERIALIZED_NAME_TRANSACTIONS)
  private List<Object> transactions = new ArrayList<>();

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public TONEmulationAction() {
  }

  public TONEmulationAction accounts(List<String> accounts) {
    this.accounts = accounts;
    return this;
  }

  public TONEmulationAction addAccountsItem(String accountsItem) {
    if (this.accounts == null) {
      this.accounts = new ArrayList<>();
    }
    this.accounts.add(accountsItem);
    return this;
  }

  /**
   * Addresses of accounts involved in this action
   * @return accounts
   */
  public List<String> getAccounts() {
    return accounts;
  }

  public void setAccounts(List<String> accounts) {
    this.accounts = accounts;
  }


  public TONEmulationAction details(Map<String, Object> details) {
    this.details = details;
    return this;
  }

  public TONEmulationAction putDetailsItem(String key, Object detailsItem) {
    if (this.details == null) {
      this.details = new HashMap<>();
    }
    this.details.put(key, detailsItem);
    return this;
  }

  /**
   * Action-specific detail fields keyed by name
   * @return details
   */
  public Map<String, Object> getDetails() {
    return details;
  }

  public void setDetails(Map<String, Object> details) {
    this.details = details;
  }


  public TONEmulationAction endLt(String endLt) {
    this.endLt = endLt;
    return this;
  }

  /**
   * Logical time value used for ordering transactions on the TON blockchain
   * @return endLt
   */
  public String getEndLt() {
    return endLt;
  }

  public void setEndLt(String endLt) {
    this.endLt = endLt;
  }


  public TONEmulationAction endUtime(BigDecimal endUtime) {
    this.endUtime = endUtime;
    return this;
  }

  /**
   * Unix timestamp when the action ended
   * @return endUtime
   */
  public BigDecimal getEndUtime() {
    return endUtime;
  }

  public void setEndUtime(BigDecimal endUtime) {
    this.endUtime = endUtime;
  }


  public TONEmulationAction isSuccess(Boolean isSuccess) {
    this.isSuccess = isSuccess;
    return this;
  }

  /**
   * Whether the action completed successfully
   * @return isSuccess
   */
  public Boolean getIsSuccess() {
    return isSuccess;
  }

  public void setIsSuccess(Boolean isSuccess) {
    this.isSuccess = isSuccess;
  }


  public TONEmulationAction startLt(String startLt) {
    this.startLt = startLt;
    return this;
  }

  /**
   * Logical time value used for ordering transactions on the TON blockchain
   * @return startLt
   */
  public String getStartLt() {
    return startLt;
  }

  public void setStartLt(String startLt) {
    this.startLt = startLt;
  }


  public TONEmulationAction startUtime(BigDecimal startUtime) {
    this.startUtime = startUtime;
    return this;
  }

  /**
   * Unix timestamp when the action started
   * @return startUtime
   */
  public BigDecimal getStartUtime() {
    return startUtime;
  }

  public void setStartUtime(BigDecimal startUtime) {
    this.startUtime = startUtime;
  }


  public TONEmulationAction traceEndLt(String traceEndLt) {
    this.traceEndLt = traceEndLt;
    return this;
  }

  /**
   * Logical time value used for ordering transactions on the TON blockchain
   * @return traceEndLt
   */
  public String getTraceEndLt() {
    return traceEndLt;
  }

  public void setTraceEndLt(String traceEndLt) {
    this.traceEndLt = traceEndLt;
  }


  public TONEmulationAction traceEndUtime(BigDecimal traceEndUtime) {
    this.traceEndUtime = traceEndUtime;
    return this;
  }

  /**
   * Unix timestamp when the trace ended
   * @return traceEndUtime
   */
  public BigDecimal getTraceEndUtime() {
    return traceEndUtime;
  }

  public void setTraceEndUtime(BigDecimal traceEndUtime) {
    this.traceEndUtime = traceEndUtime;
  }


  public TONEmulationAction traceId(String traceId) {
    this.traceId = traceId;
    return this;
  }

  /**
   * Trace identifier this action belongs to
   * @return traceId
   */
  public String getTraceId() {
    return traceId;
  }

  public void setTraceId(String traceId) {
    this.traceId = traceId;
  }


  public TONEmulationAction traceMcSeqnoEnd(BigDecimal traceMcSeqnoEnd) {
    this.traceMcSeqnoEnd = traceMcSeqnoEnd;
    return this;
  }

  /**
   * Masterchain block sequence number when the trace ended
   * @return traceMcSeqnoEnd
   */
  public BigDecimal getTraceMcSeqnoEnd() {
    return traceMcSeqnoEnd;
  }

  public void setTraceMcSeqnoEnd(BigDecimal traceMcSeqnoEnd) {
    this.traceMcSeqnoEnd = traceMcSeqnoEnd;
  }


  public TONEmulationAction transactions(List<Object> transactions) {
    this.transactions = transactions;
    return this;
  }

  public TONEmulationAction addTransactionsItem(Object transactionsItem) {
    if (this.transactions == null) {
      this.transactions = new ArrayList<>();
    }
    this.transactions.add(transactionsItem);
    return this;
  }

  /**
   * Hex-encoded hashes of transactions involved in this action
   * @return transactions
   */
  public List<Object> getTransactions() {
    return transactions;
  }

  public void setTransactions(List<Object> transactions) {
    this.transactions = transactions;
  }


  public TONEmulationAction type(String type) {
    this.type = type;
    return this;
  }

  /**
   * Action type identifier (e.g. \&quot;jetton_transfer\&quot;, \&quot;ton_transfer\&quot;, \&quot;jetton_swap\&quot;)
   * @return type
   */
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TONEmulationAction emulationAction = (TONEmulationAction) o;
    return Objects.equals(this.accounts, emulationAction.accounts) &&
        Objects.equals(this.details, emulationAction.details) &&
        Objects.equals(this.endLt, emulationAction.endLt) &&
        Objects.equals(this.endUtime, emulationAction.endUtime) &&
        Objects.equals(this.isSuccess, emulationAction.isSuccess) &&
        Objects.equals(this.startLt, emulationAction.startLt) &&
        Objects.equals(this.startUtime, emulationAction.startUtime) &&
        Objects.equals(this.traceEndLt, emulationAction.traceEndLt) &&
        Objects.equals(this.traceEndUtime, emulationAction.traceEndUtime) &&
        Objects.equals(this.traceId, emulationAction.traceId) &&
        Objects.equals(this.traceMcSeqnoEnd, emulationAction.traceMcSeqnoEnd) &&
        Objects.equals(this.transactions, emulationAction.transactions) &&
        Objects.equals(this.type, emulationAction.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accounts, details, endLt, endUtime, isSuccess, startLt, startUtime, traceEndLt, traceEndUtime, traceId, traceMcSeqnoEnd, transactions, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TONEmulationAction {\n");
    sb.append("    accounts: ").append(toIndentedString(accounts)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    endLt: ").append(toIndentedString(endLt)).append("\n");
    sb.append("    endUtime: ").append(toIndentedString(endUtime)).append("\n");
    sb.append("    isSuccess: ").append(toIndentedString(isSuccess)).append("\n");
    sb.append("    startLt: ").append(toIndentedString(startLt)).append("\n");
    sb.append("    startUtime: ").append(toIndentedString(startUtime)).append("\n");
    sb.append("    traceEndLt: ").append(toIndentedString(traceEndLt)).append("\n");
    sb.append("    traceEndUtime: ").append(toIndentedString(traceEndUtime)).append("\n");
    sb.append("    traceId: ").append(toIndentedString(traceId)).append("\n");
    sb.append("    traceMcSeqnoEnd: ").append(toIndentedString(traceMcSeqnoEnd)).append("\n");
    sb.append("    transactions: ").append(toIndentedString(transactions)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("accounts");
    openapiFields.add("details");
    openapiFields.add("endLt");
    openapiFields.add("endUtime");
    openapiFields.add("isSuccess");
    openapiFields.add("startLt");
    openapiFields.add("startUtime");
    openapiFields.add("traceEndLt");
    openapiFields.add("traceEndUtime");
    openapiFields.add("traceId");
    openapiFields.add("traceMcSeqnoEnd");
    openapiFields.add("transactions");
    openapiFields.add("type");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("accounts");
    openapiRequiredFields.add("details");
    openapiRequiredFields.add("endLt");
    openapiRequiredFields.add("endUtime");
    openapiRequiredFields.add("isSuccess");
    openapiRequiredFields.add("startLt");
    openapiRequiredFields.add("startUtime");
    openapiRequiredFields.add("traceEndLt");
    openapiRequiredFields.add("traceEndUtime");
    openapiRequiredFields.add("traceMcSeqnoEnd");
    openapiRequiredFields.add("transactions");
    openapiRequiredFields.add("type");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TONEmulationAction
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TONEmulationAction.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TONEmulationAction is not found in the empty JSON string", TONEmulationAction.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TONEmulationAction.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TONEmulationAction` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TONEmulationAction.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the required json array is present
      if (jsonObj.get("accounts") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("accounts").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `accounts` to be an array in the JSON string but got `%s`", jsonObj.get("accounts").toString()));
      }
      if (!jsonObj.get("endLt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `endLt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("endLt").toString()));
      }
      if (!jsonObj.get("startLt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `startLt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("startLt").toString()));
      }
      if (!jsonObj.get("traceEndLt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `traceEndLt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("traceEndLt").toString()));
      }
      if ((jsonObj.get("traceId") != null && !jsonObj.get("traceId").isJsonNull()) && !jsonObj.get("traceId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `traceId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("traceId").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("transactions") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("transactions").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `transactions` to be an array in the JSON string but got `%s`", jsonObj.get("transactions").toString()));
      }
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TONEmulationAction.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TONEmulationAction' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TONEmulationAction> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TONEmulationAction.class));

       return (TypeAdapter<T>) new TypeAdapter<TONEmulationAction>() {
           @Override
           public void write(JsonWriter out, TONEmulationAction value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TONEmulationAction read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TONEmulationAction given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TONEmulationAction
   * @throws IOException if the JSON string is invalid with respect to TONEmulationAction
   */
  public static TONEmulationAction fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TONEmulationAction.class);
  }

  /**
   * Convert an instance of TONEmulationAction to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

