//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

/** Successful outcome of a transaction emulation attempt. Contains the full emulation response including trace and actions. */
public class TONEmulationResultSuccess {

    /** Builds one of these from JSON. */
    public static final Parser<TONEmulationResultSuccess> PARSER = new Parser<TONEmulationResultSuccess>() {
        @Override
        public TONEmulationResultSuccess parse(JSONObject json) {
            return fromJson(json);
        }
    };

    /** Values this property accepts. */
    public enum ResultEnum {

        SUCCESS("success");

        private final String value;

        ResultEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static ResultEnum fromValue(Object wire) {
            if (wire == null) {
                return null;
            }
            String text = wire.toString();
            for (ResultEnum candidate : values()) {
                if (candidate.value.equals(text)) {
                    return candidate;
                }
            }
            return null;
        }
    }

    private TONEmulationResponse emulationResult;
    private ResultEnum result;

    /**
     * The emulation response data including trace, actions, and messages
     * Required by the API.
     */
    public TONEmulationResponse getEmulationResult() {
        return emulationResult;
    }

    public TONEmulationResultSuccess setEmulationResult(TONEmulationResponse value) {
        this.emulationResult = value;
        return this;
    }

    /**
     * Discriminant tag indicating a successful emulation
     * Required by the API.
     */
    public ResultEnum getResult() {
        return result;
    }

    public TONEmulationResultSuccess setResult(ResultEnum value) {
        this.result = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "emulationResult", emulationResult == null ? null : emulationResult.toJson());
        TonApiJson.put(json, "result", result == null ? null : result.getValue());
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONEmulationResultSuccess fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONEmulationResultSuccess out = new TONEmulationResultSuccess();
        out.emulationResult = TONEmulationResponse.fromJson(TonApiJson.optObject(json, "emulationResult"));
        out.result = ResultEnum.fromValue(TonApiJson.opt(json, "result"));
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
