/*
 * TON WalletKit models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ton.walletkit.api;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.ton.walletkit.api.TONEmulationActionPhase;
import org.ton.walletkit.api.TONEmulationComputePhase;
import org.ton.walletkit.api.TONEmulationCreditPhase;
import org.ton.walletkit.api.TONEmulationStoragePhase;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.ton.walletkit.api.JSON;

/**
 * Detailed description of all execution phases in an emulated transaction.
 */
public class TONEmulationTransactionDescription {
  public static final String SERIALIZED_NAME_ACTION_PHASE = "actionPhase";
  @SerializedName(SERIALIZED_NAME_ACTION_PHASE)
  private TONEmulationActionPhase actionPhase;

  public static final String SERIALIZED_NAME_COMPUTE_PHASE = "computePhase";
  @SerializedName(SERIALIZED_NAME_COMPUTE_PHASE)
  private TONEmulationComputePhase computePhase;

  public static final String SERIALIZED_NAME_CREDIT_PHASE = "creditPhase";
  @SerializedName(SERIALIZED_NAME_CREDIT_PHASE)
  private TONEmulationCreditPhase creditPhase;

  public static final String SERIALIZED_NAME_IS_ABORTED = "isAborted";
  @SerializedName(SERIALIZED_NAME_IS_ABORTED)
  private Boolean isAborted;

  public static final String SERIALIZED_NAME_IS_CREDIT_FIRST = "isCreditFirst";
  @SerializedName(SERIALIZED_NAME_IS_CREDIT_FIRST)
  private Boolean isCreditFirst;

  public static final String SERIALIZED_NAME_IS_DESTROYED = "isDestroyed";
  @SerializedName(SERIALIZED_NAME_IS_DESTROYED)
  private Boolean isDestroyed;

  public static final String SERIALIZED_NAME_IS_INSTALLED = "isInstalled";
  @SerializedName(SERIALIZED_NAME_IS_INSTALLED)
  private Boolean isInstalled;

  public static final String SERIALIZED_NAME_IS_TOCK = "isTock";
  @SerializedName(SERIALIZED_NAME_IS_TOCK)
  private Boolean isTock;

  public static final String SERIALIZED_NAME_STORAGE_PHASE = "storagePhase";
  @SerializedName(SERIALIZED_NAME_STORAGE_PHASE)
  private TONEmulationStoragePhase storagePhase;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public TONEmulationTransactionDescription() {
  }

  public TONEmulationTransactionDescription actionPhase(TONEmulationActionPhase actionPhase) {
    this.actionPhase = actionPhase;
    return this;
  }

  /**
   * Get actionPhase
   * @return actionPhase
   */
  public TONEmulationActionPhase getActionPhase() {
    return actionPhase;
  }

  public void setActionPhase(TONEmulationActionPhase actionPhase) {
    this.actionPhase = actionPhase;
  }


  public TONEmulationTransactionDescription computePhase(TONEmulationComputePhase computePhase) {
    this.computePhase = computePhase;
    return this;
  }

  /**
   * Get computePhase
   * @return computePhase
   */
  public TONEmulationComputePhase getComputePhase() {
    return computePhase;
  }

  public void setComputePhase(TONEmulationComputePhase computePhase) {
    this.computePhase = computePhase;
  }


  public TONEmulationTransactionDescription creditPhase(TONEmulationCreditPhase creditPhase) {
    this.creditPhase = creditPhase;
    return this;
  }

  /**
   * Get creditPhase
   * @return creditPhase
   */
  public TONEmulationCreditPhase getCreditPhase() {
    return creditPhase;
  }

  public void setCreditPhase(TONEmulationCreditPhase creditPhase) {
    this.creditPhase = creditPhase;
  }


  public TONEmulationTransactionDescription isAborted(Boolean isAborted) {
    this.isAborted = isAborted;
    return this;
  }

  /**
   * Whether the transaction was aborted
   * @return isAborted
   */
  public Boolean getIsAborted() {
    return isAborted;
  }

  public void setIsAborted(Boolean isAborted) {
    this.isAborted = isAborted;
  }


  public TONEmulationTransactionDescription isCreditFirst(Boolean isCreditFirst) {
    this.isCreditFirst = isCreditFirst;
    return this;
  }

  /**
   * Whether the credit phase was executed before the storage phase
   * @return isCreditFirst
   */
  public Boolean getIsCreditFirst() {
    return isCreditFirst;
  }

  public void setIsCreditFirst(Boolean isCreditFirst) {
    this.isCreditFirst = isCreditFirst;
  }


  public TONEmulationTransactionDescription isDestroyed(Boolean isDestroyed) {
    this.isDestroyed = isDestroyed;
    return this;
  }

  /**
   * Whether the account was destroyed by this transaction
   * @return isDestroyed
   */
  public Boolean getIsDestroyed() {
    return isDestroyed;
  }

  public void setIsDestroyed(Boolean isDestroyed) {
    this.isDestroyed = isDestroyed;
  }


  public TONEmulationTransactionDescription isInstalled(Boolean isInstalled) {
    this.isInstalled = isInstalled;
    return this;
  }

  /**
   * Whether a contract was installed in this transaction
   * @return isInstalled
   */
  public Boolean getIsInstalled() {
    return isInstalled;
  }

  public void setIsInstalled(Boolean isInstalled) {
    this.isInstalled = isInstalled;
  }


  public TONEmulationTransactionDescription isTock(Boolean isTock) {
    this.isTock = isTock;
    return this;
  }

  /**
   * Whether this was a tock transaction
   * @return isTock
   */
  public Boolean getIsTock() {
    return isTock;
  }

  public void setIsTock(Boolean isTock) {
    this.isTock = isTock;
  }


  public TONEmulationTransactionDescription storagePhase(TONEmulationStoragePhase storagePhase) {
    this.storagePhase = storagePhase;
    return this;
  }

  /**
   * Get storagePhase
   * @return storagePhase
   */
  public TONEmulationStoragePhase getStoragePhase() {
    return storagePhase;
  }

  public void setStoragePhase(TONEmulationStoragePhase storagePhase) {
    this.storagePhase = storagePhase;
  }


  public TONEmulationTransactionDescription type(String type) {
    this.type = type;
    return this;
  }

  /**
   * Transaction type (e.g. \&quot;ord\&quot;, \&quot;ticktock\&quot;, \&quot;storage\&quot;)
   * @return type
   */
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TONEmulationTransactionDescription emulationTransactionDescription = (TONEmulationTransactionDescription) o;
    return Objects.equals(this.actionPhase, emulationTransactionDescription.actionPhase) &&
        Objects.equals(this.computePhase, emulationTransactionDescription.computePhase) &&
        Objects.equals(this.creditPhase, emulationTransactionDescription.creditPhase) &&
        Objects.equals(this.isAborted, emulationTransactionDescription.isAborted) &&
        Objects.equals(this.isCreditFirst, emulationTransactionDescription.isCreditFirst) &&
        Objects.equals(this.isDestroyed, emulationTransactionDescription.isDestroyed) &&
        Objects.equals(this.isInstalled, emulationTransactionDescription.isInstalled) &&
        Objects.equals(this.isTock, emulationTransactionDescription.isTock) &&
        Objects.equals(this.storagePhase, emulationTransactionDescription.storagePhase) &&
        Objects.equals(this.type, emulationTransactionDescription.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actionPhase, computePhase, creditPhase, isAborted, isCreditFirst, isDestroyed, isInstalled, isTock, storagePhase, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TONEmulationTransactionDescription {\n");
    sb.append("    actionPhase: ").append(toIndentedString(actionPhase)).append("\n");
    sb.append("    computePhase: ").append(toIndentedString(computePhase)).append("\n");
    sb.append("    creditPhase: ").append(toIndentedString(creditPhase)).append("\n");
    sb.append("    isAborted: ").append(toIndentedString(isAborted)).append("\n");
    sb.append("    isCreditFirst: ").append(toIndentedString(isCreditFirst)).append("\n");
    sb.append("    isDestroyed: ").append(toIndentedString(isDestroyed)).append("\n");
    sb.append("    isInstalled: ").append(toIndentedString(isInstalled)).append("\n");
    sb.append("    isTock: ").append(toIndentedString(isTock)).append("\n");
    sb.append("    storagePhase: ").append(toIndentedString(storagePhase)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("actionPhase");
    openapiFields.add("computePhase");
    openapiFields.add("creditPhase");
    openapiFields.add("isAborted");
    openapiFields.add("isCreditFirst");
    openapiFields.add("isDestroyed");
    openapiFields.add("isInstalled");
    openapiFields.add("isTock");
    openapiFields.add("storagePhase");
    openapiFields.add("type");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("computePhase");
    openapiRequiredFields.add("isAborted");
    openapiRequiredFields.add("isCreditFirst");
    openapiRequiredFields.add("isDestroyed");
    openapiRequiredFields.add("isInstalled");
    openapiRequiredFields.add("isTock");
    openapiRequiredFields.add("storagePhase");
    openapiRequiredFields.add("type");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TONEmulationTransactionDescription
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TONEmulationTransactionDescription.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TONEmulationTransactionDescription is not found in the empty JSON string", TONEmulationTransactionDescription.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TONEmulationTransactionDescription.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TONEmulationTransactionDescription` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TONEmulationTransactionDescription.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `actionPhase`
      if (jsonObj.get("actionPhase") != null && !jsonObj.get("actionPhase").isJsonNull()) {
        TONEmulationActionPhase.validateJsonElement(jsonObj.get("actionPhase"));
      }
      // validate the required field `computePhase`
      TONEmulationComputePhase.validateJsonElement(jsonObj.get("computePhase"));
      // validate the optional field `creditPhase`
      if (jsonObj.get("creditPhase") != null && !jsonObj.get("creditPhase").isJsonNull()) {
        TONEmulationCreditPhase.validateJsonElement(jsonObj.get("creditPhase"));
      }
      // validate the required field `storagePhase`
      TONEmulationStoragePhase.validateJsonElement(jsonObj.get("storagePhase"));
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TONEmulationTransactionDescription.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TONEmulationTransactionDescription' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TONEmulationTransactionDescription> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TONEmulationTransactionDescription.class));

       return (TypeAdapter<T>) new TypeAdapter<TONEmulationTransactionDescription>() {
           @Override
           public void write(JsonWriter out, TONEmulationTransactionDescription value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TONEmulationTransactionDescription read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TONEmulationTransactionDescription given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TONEmulationTransactionDescription
   * @throws IOException if the JSON string is invalid with respect to TONEmulationTransactionDescription
   */
  public static TONEmulationTransactionDescription fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TONEmulationTransactionDescription.class);
  }

  /**
   * Convert an instance of TONEmulationTransactionDescription to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

