//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

public class TONEmbeddedSignDataRequestEvent {

    /** Builds one of these from JSON. */
    public static final Parser<TONEmbeddedSignDataRequestEvent> PARSER = new Parser<TONEmbeddedSignDataRequestEvent>() {
        @Override
        public TONEmbeddedSignDataRequestEvent parse(JSONObject json) {
            return fromJson(json);
        }
    };

    /** Values this property accepts. */
    public enum TypeEnum {

        SIGN_DATA("signData");

        private final String value;

        TypeEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static TypeEnum fromValue(Object wire) {
            if (wire == null) {
                return null;
            }
            String text = wire.toString();
            for (TypeEnum candidate : values()) {
                if (candidate.value.equals(text)) {
                    return candidate;
                }
            }
            return null;
        }
    }

    private TONDAppInfo dAppInfo;
    private String domain;
    private String from;
    private String id;
    private Boolean isJsBridge;
    private Boolean isLocal;
    private String messageId;
    private TONSignDataPayload payload;
    private TONSignDataRequestEventPreview preview;
    private String returnStrategy;
    private String sessionId;
    private String tabId;
    private String traceId;
    private TypeEnum type;
    private String walletAddress;
    private String walletId;

    public TONDAppInfo getDAppInfo() {
        return dAppInfo;
    }

    public TONEmbeddedSignDataRequestEvent setDAppInfo(TONDAppInfo value) {
        this.dAppInfo = value;
        return this;
    }

    /** Domain of the dApp that initiated the event */
    public String getDomain() {
        return domain;
    }

    public TONEmbeddedSignDataRequestEvent setDomain(String value) {
        this.domain = value;
        return this;
    }

    public String getFrom() {
        return from;
    }

    public TONEmbeddedSignDataRequestEvent setFrom(String value) {
        this.from = value;
        return this;
    }

    /**
     * Unique identifier for the bridge event
     * Required by the API.
     */
    public String getId() {
        return id;
    }

    public TONEmbeddedSignDataRequestEvent setId(String value) {
        this.id = value;
        return this;
    }

    /** Whether the event originated from JS Bridge (injected provider) */
    public Boolean getIsJsBridge() {
        return isJsBridge;
    }

    public TONEmbeddedSignDataRequestEvent setIsJsBridge(Boolean value) {
        this.isJsBridge = value;
        return this;
    }

    public Boolean getIsLocal() {
        return isLocal;
    }

    public TONEmbeddedSignDataRequestEvent setIsLocal(Boolean value) {
        this.isLocal = value;
        return this;
    }

    public String getMessageId() {
        return messageId;
    }

    public TONEmbeddedSignDataRequestEvent setMessageId(String value) {
        this.messageId = value;
        return this;
    }

    /**
     * Payload containing the data to be signed
     * Required by the API.
     */
    public TONSignDataPayload getPayload() {
        return payload;
    }

    public TONEmbeddedSignDataRequestEvent setPayload(TONSignDataPayload value) {
        this.payload = value;
        return this;
    }

    /**
     * Preview information for UI display
     * Required by the API.
     */
    public TONSignDataRequestEventPreview getPreview() {
        return preview;
    }

    public TONEmbeddedSignDataRequestEvent setPreview(TONSignDataRequestEventPreview value) {
        this.preview = value;
        return this;
    }

    /** Raw TonConnect return strategy string. */
    public String getReturnStrategy() {
        return returnStrategy;
    }

    public TONEmbeddedSignDataRequestEvent setReturnStrategy(String value) {
        this.returnStrategy = value;
        return this;
    }

    /** Session identifier for the connection */
    public String getSessionId() {
        return sessionId;
    }

    public TONEmbeddedSignDataRequestEvent setSessionId(String value) {
        this.sessionId = value;
        return this;
    }

    /** Browser tab ID for JS Bridge events */
    public String getTabId() {
        return tabId;
    }

    public TONEmbeddedSignDataRequestEvent setTabId(String value) {
        this.tabId = value;
        return this;
    }

    public String getTraceId() {
        return traceId;
    }

    public TONEmbeddedSignDataRequestEvent setTraceId(String value) {
        this.traceId = value;
        return this;
    }

    /** Required by the API. */
    public TypeEnum getType() {
        return type;
    }

    public TONEmbeddedSignDataRequestEvent setType(TypeEnum value) {
        this.type = value;
        return this;
    }

    /** Wallet address associated with the event */
    public String getWalletAddress() {
        return walletAddress;
    }

    public TONEmbeddedSignDataRequestEvent setWalletAddress(String value) {
        this.walletAddress = value;
        return this;
    }

    /** Wallet identifier associated with the event */
    public String getWalletId() {
        return walletId;
    }

    public TONEmbeddedSignDataRequestEvent setWalletId(String value) {
        this.walletId = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "dAppInfo", dAppInfo == null ? null : dAppInfo.toJson());
        TonApiJson.put(json, "domain", domain);
        TonApiJson.put(json, "from", from);
        TonApiJson.put(json, "id", id);
        TonApiJson.put(json, "isJsBridge", isJsBridge);
        TonApiJson.put(json, "isLocal", isLocal);
        TonApiJson.put(json, "messageId", messageId);
        TonApiJson.put(json, "payload", payload == null ? null : payload.toJson());
        TonApiJson.put(json, "preview", preview == null ? null : preview.toJson());
        TonApiJson.put(json, "returnStrategy", returnStrategy);
        TonApiJson.put(json, "sessionId", sessionId);
        TonApiJson.put(json, "tabId", tabId);
        TonApiJson.put(json, "traceId", traceId);
        TonApiJson.put(json, "type", type == null ? null : type.getValue());
        TonApiJson.put(json, "walletAddress", walletAddress);
        TonApiJson.put(json, "walletId", walletId);
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONEmbeddedSignDataRequestEvent fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONEmbeddedSignDataRequestEvent out = new TONEmbeddedSignDataRequestEvent();
        out.dAppInfo = TONDAppInfo.fromJson(TonApiJson.optObject(json, "dAppInfo"));
        out.domain = TonApiJson.optString(json, "domain");
        out.from = TonApiJson.optString(json, "from");
        out.id = TonApiJson.optString(json, "id");
        out.isJsBridge = TonApiJson.optBoolean(json, "isJsBridge");
        out.isLocal = TonApiJson.optBoolean(json, "isLocal");
        out.messageId = TonApiJson.optString(json, "messageId");
        out.payload = TONSignDataPayload.fromJson(TonApiJson.optObject(json, "payload"));
        out.preview = TONSignDataRequestEventPreview.fromJson(TonApiJson.optObject(json, "preview"));
        out.returnStrategy = TonApiJson.optString(json, "returnStrategy");
        out.sessionId = TonApiJson.optString(json, "sessionId");
        out.tabId = TonApiJson.optString(json, "tabId");
        out.traceId = TonApiJson.optString(json, "traceId");
        out.type = TypeEnum.fromValue(TonApiJson.opt(json, "type"));
        out.walletAddress = TonApiJson.optString(json, "walletAddress");
        out.walletId = TonApiJson.optString(json, "walletId");
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
