/*
 * TON WalletKit models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ton.walletkit.api;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.ton.walletkit.api.TONEmulationMessageContent;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.ton.walletkit.api.JSON;

/**
 * Message sent or received within an emulated transaction trace.
 */
public class TONEmulationMessage {
  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private BigDecimal createdAt;

  public static final String SERIALIZED_NAME_CREATED_LT = "createdLt";
  @SerializedName(SERIALIZED_NAME_CREATED_LT)
  private String createdLt;

  public static final String SERIALIZED_NAME_DESTINATION = "destination";
  @SerializedName(SERIALIZED_NAME_DESTINATION)
  private String destination;

  public static final String SERIALIZED_NAME_FWD_FEE = "fwdFee";
  @SerializedName(SERIALIZED_NAME_FWD_FEE)
  private String fwdFee;

  public static final String SERIALIZED_NAME_IHR_DISABLED = "ihrDisabled";
  @SerializedName(SERIALIZED_NAME_IHR_DISABLED)
  private Boolean ihrDisabled;

  public static final String SERIALIZED_NAME_IHR_FEE = "ihrFee";
  @SerializedName(SERIALIZED_NAME_IHR_FEE)
  private String ihrFee;

  public static final String SERIALIZED_NAME_IMPORT_FEE = "importFee";
  @SerializedName(SERIALIZED_NAME_IMPORT_FEE)
  private String importFee;

  public static final String SERIALIZED_NAME_INIT_STATE = "initState";
  @SerializedName(SERIALIZED_NAME_INIT_STATE)
  private Object initState = null;

  public static final String SERIALIZED_NAME_IS_BOUNCE = "isBounce";
  @SerializedName(SERIALIZED_NAME_IS_BOUNCE)
  private Boolean isBounce;

  public static final String SERIALIZED_NAME_IS_BOUNCED = "isBounced";
  @SerializedName(SERIALIZED_NAME_IS_BOUNCED)
  private Boolean isBounced;

  public static final String SERIALIZED_NAME_MESSAGE_CONTENT = "messageContent";
  @SerializedName(SERIALIZED_NAME_MESSAGE_CONTENT)
  private TONEmulationMessageContent messageContent;

  public static final String SERIALIZED_NAME_SOURCE = "source";
  @SerializedName(SERIALIZED_NAME_SOURCE)
  private String source;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;

  public static final String SERIALIZED_NAME_VALUE_EXTRA_CURRENCIES = "valueExtraCurrencies";
  @SerializedName(SERIALIZED_NAME_VALUE_EXTRA_CURRENCIES)
  private Map<String, String> valueExtraCurrencies = new HashMap<>();

  public TONEmulationMessage() {
  }

  public TONEmulationMessage createdAt(BigDecimal createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Unix timestamp when the message was created, or undefined for external inbound messages
   * @return createdAt
   */
  public BigDecimal getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(BigDecimal createdAt) {
    this.createdAt = createdAt;
  }


  public TONEmulationMessage createdLt(String createdLt) {
    this.createdLt = createdLt;
    return this;
  }

  /**
   * Logical time value used for ordering transactions on the TON blockchain
   * @return createdLt
   */
  public String getCreatedLt() {
    return createdLt;
  }

  public void setCreatedLt(String createdLt) {
    this.createdLt = createdLt;
  }


  public TONEmulationMessage destination(String destination) {
    this.destination = destination;
    return this;
  }

  /**
   * User-friendly TON address representation (e.g., \&quot;EQDtFpEwcFAEcRe5mLVh2N6C0x-_hJEM7W61_JLnSF74p4q2\&quot;)
   * @return destination
   */
  public String getDestination() {
    return destination;
  }

  public void setDestination(String destination) {
    this.destination = destination;
  }


  public TONEmulationMessage fwdFee(String fwdFee) {
    this.fwdFee = fwdFee;
    return this;
  }

  /**
   * Token amount represented as a string to preserve precision. For TON, this is typically in nanotons (1 TON &#x3D; 10^9 nanotons).
   * @return fwdFee
   */
  public String getFwdFee() {
    return fwdFee;
  }

  public void setFwdFee(String fwdFee) {
    this.fwdFee = fwdFee;
  }


  public TONEmulationMessage ihrDisabled(Boolean ihrDisabled) {
    this.ihrDisabled = ihrDisabled;
    return this;
  }

  /**
   * Whether IHR delivery is disabled, or undefined for external inbound messages
   * @return ihrDisabled
   */
  public Boolean getIhrDisabled() {
    return ihrDisabled;
  }

  public void setIhrDisabled(Boolean ihrDisabled) {
    this.ihrDisabled = ihrDisabled;
  }


  public TONEmulationMessage ihrFee(String ihrFee) {
    this.ihrFee = ihrFee;
    return this;
  }

  /**
   * Token amount represented as a string to preserve precision. For TON, this is typically in nanotons (1 TON &#x3D; 10^9 nanotons).
   * @return ihrFee
   */
  public String getIhrFee() {
    return ihrFee;
  }

  public void setIhrFee(String ihrFee) {
    this.ihrFee = ihrFee;
  }


  public TONEmulationMessage importFee(String importFee) {
    this.importFee = importFee;
    return this;
  }

  /**
   * Token amount represented as a string to preserve precision. For TON, this is typically in nanotons (1 TON &#x3D; 10^9 nanotons).
   * @return importFee
   */
  public String getImportFee() {
    return importFee;
  }

  public void setImportFee(String importFee) {
    this.importFee = importFee;
  }


  public TONEmulationMessage initState(Object initState) {
    this.initState = initState;
    return this;
  }

  /**
   * Initial state (StateInit) attached to the message, if any
   * @return initState
   */
  public Object getInitState() {
    return initState;
  }

  public void setInitState(Object initState) {
    this.initState = initState;
  }


  public TONEmulationMessage isBounce(Boolean isBounce) {
    this.isBounce = isBounce;
    return this;
  }

  /**
   * Whether the message requested a bounce on failure, or undefined for external inbound messages
   * @return isBounce
   */
  public Boolean getIsBounce() {
    return isBounce;
  }

  public void setIsBounce(Boolean isBounce) {
    this.isBounce = isBounce;
  }


  public TONEmulationMessage isBounced(Boolean isBounced) {
    this.isBounced = isBounced;
    return this;
  }

  /**
   * Whether the message was bounced back, or undefined for external inbound messages
   * @return isBounced
   */
  public Boolean getIsBounced() {
    return isBounced;
  }

  public void setIsBounced(Boolean isBounced) {
    this.isBounced = isBounced;
  }


  public TONEmulationMessage messageContent(TONEmulationMessageContent messageContent) {
    this.messageContent = messageContent;
    return this;
  }

  /**
   * Get messageContent
   * @return messageContent
   */
  public TONEmulationMessageContent getMessageContent() {
    return messageContent;
  }

  public void setMessageContent(TONEmulationMessageContent messageContent) {
    this.messageContent = messageContent;
  }


  public TONEmulationMessage source(String source) {
    this.source = source;
    return this;
  }

  /**
   * User-friendly TON address representation (e.g., \&quot;EQDtFpEwcFAEcRe5mLVh2N6C0x-_hJEM7W61_JLnSF74p4q2\&quot;)
   * @return source
   */
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }


  public TONEmulationMessage value(String value) {
    this.value = value;
    return this;
  }

  /**
   * Token amount represented as a string to preserve precision. For TON, this is typically in nanotons (1 TON &#x3D; 10^9 nanotons).
   * @return value
   */
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  public TONEmulationMessage valueExtraCurrencies(Map<String, String> valueExtraCurrencies) {
    this.valueExtraCurrencies = valueExtraCurrencies;
    return this;
  }

  public TONEmulationMessage putValueExtraCurrenciesItem(String key, String valueExtraCurrenciesItem) {
    if (this.valueExtraCurrencies == null) {
      this.valueExtraCurrencies = new HashMap<>();
    }
    this.valueExtraCurrencies.put(key, valueExtraCurrenciesItem);
    return this;
  }

  /**
   * Map of extra currency IDs to their amounts. Extra currencies are additional tokens that can be attached to TON messages.
   * @return valueExtraCurrencies
   */
  public Map<String, String> getValueExtraCurrencies() {
    return valueExtraCurrencies;
  }

  public void setValueExtraCurrencies(Map<String, String> valueExtraCurrencies) {
    this.valueExtraCurrencies = valueExtraCurrencies;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TONEmulationMessage emulationMessage = (TONEmulationMessage) o;
    return Objects.equals(this.createdAt, emulationMessage.createdAt) &&
        Objects.equals(this.createdLt, emulationMessage.createdLt) &&
        Objects.equals(this.destination, emulationMessage.destination) &&
        Objects.equals(this.fwdFee, emulationMessage.fwdFee) &&
        Objects.equals(this.ihrDisabled, emulationMessage.ihrDisabled) &&
        Objects.equals(this.ihrFee, emulationMessage.ihrFee) &&
        Objects.equals(this.importFee, emulationMessage.importFee) &&
        Objects.equals(this.initState, emulationMessage.initState) &&
        Objects.equals(this.isBounce, emulationMessage.isBounce) &&
        Objects.equals(this.isBounced, emulationMessage.isBounced) &&
        Objects.equals(this.messageContent, emulationMessage.messageContent) &&
        Objects.equals(this.source, emulationMessage.source) &&
        Objects.equals(this.value, emulationMessage.value) &&
        Objects.equals(this.valueExtraCurrencies, emulationMessage.valueExtraCurrencies);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, createdLt, destination, fwdFee, ihrDisabled, ihrFee, importFee, initState, isBounce, isBounced, messageContent, source, value, valueExtraCurrencies);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TONEmulationMessage {\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    createdLt: ").append(toIndentedString(createdLt)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    fwdFee: ").append(toIndentedString(fwdFee)).append("\n");
    sb.append("    ihrDisabled: ").append(toIndentedString(ihrDisabled)).append("\n");
    sb.append("    ihrFee: ").append(toIndentedString(ihrFee)).append("\n");
    sb.append("    importFee: ").append(toIndentedString(importFee)).append("\n");
    sb.append("    initState: ").append(toIndentedString(initState)).append("\n");
    sb.append("    isBounce: ").append(toIndentedString(isBounce)).append("\n");
    sb.append("    isBounced: ").append(toIndentedString(isBounced)).append("\n");
    sb.append("    messageContent: ").append(toIndentedString(messageContent)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    valueExtraCurrencies: ").append(toIndentedString(valueExtraCurrencies)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("createdAt");
    openapiFields.add("createdLt");
    openapiFields.add("destination");
    openapiFields.add("fwdFee");
    openapiFields.add("ihrDisabled");
    openapiFields.add("ihrFee");
    openapiFields.add("importFee");
    openapiFields.add("initState");
    openapiFields.add("isBounce");
    openapiFields.add("isBounced");
    openapiFields.add("messageContent");
    openapiFields.add("source");
    openapiFields.add("value");
    openapiFields.add("valueExtraCurrencies");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("destination");
    openapiRequiredFields.add("messageContent");
    openapiRequiredFields.add("valueExtraCurrencies");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TONEmulationMessage
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TONEmulationMessage.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TONEmulationMessage is not found in the empty JSON string", TONEmulationMessage.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TONEmulationMessage.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TONEmulationMessage` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TONEmulationMessage.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("createdLt") != null && !jsonObj.get("createdLt").isJsonNull()) && !jsonObj.get("createdLt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `createdLt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createdLt").toString()));
      }
      if (!jsonObj.get("destination").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `destination` to be a primitive type in the JSON string but got `%s`", jsonObj.get("destination").toString()));
      }
      if ((jsonObj.get("fwdFee") != null && !jsonObj.get("fwdFee").isJsonNull()) && !jsonObj.get("fwdFee").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fwdFee` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fwdFee").toString()));
      }
      if ((jsonObj.get("ihrFee") != null && !jsonObj.get("ihrFee").isJsonNull()) && !jsonObj.get("ihrFee").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ihrFee` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ihrFee").toString()));
      }
      if ((jsonObj.get("importFee") != null && !jsonObj.get("importFee").isJsonNull()) && !jsonObj.get("importFee").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `importFee` to be a primitive type in the JSON string but got `%s`", jsonObj.get("importFee").toString()));
      }
      // validate the required field `messageContent`
      TONEmulationMessageContent.validateJsonElement(jsonObj.get("messageContent"));
      if ((jsonObj.get("source") != null && !jsonObj.get("source").isJsonNull()) && !jsonObj.get("source").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `source` to be a primitive type in the JSON string but got `%s`", jsonObj.get("source").toString()));
      }
      if ((jsonObj.get("value") != null && !jsonObj.get("value").isJsonNull()) && !jsonObj.get("value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("value").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TONEmulationMessage.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TONEmulationMessage' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TONEmulationMessage> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TONEmulationMessage.class));

       return (TypeAdapter<T>) new TypeAdapter<TONEmulationMessage>() {
           @Override
           public void write(JsonWriter out, TONEmulationMessage value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TONEmulationMessage read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TONEmulationMessage given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TONEmulationMessage
   * @throws IOException if the JSON string is invalid with respect to TONEmulationMessage
   */
  public static TONEmulationMessage fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TONEmulationMessage.class);
  }

  /**
   * Convert an instance of TONEmulationMessage to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

