//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

/** Result of a transaction emulation attempt. */
/**
 * A union: {@code result} says which variant this is, and the matching
 * accessor returns it. An unrecognised result leaves the value as the raw
 * JSON rather than failing, so a new variant upstream does not break a
 * response that merely contains one.
 */
public class TONEmulationResult {

    public static final Parser<TONEmulationResult> PARSER = new Parser<TONEmulationResult>() {
        @Override
        public TONEmulationResult parse(JSONObject json) {
            return fromJson(json);
        }
    };

    public static final String SUCCESS = "success";
    public static final String ERROR = "error";

    private String result;
    private Object value;

    /** Which variant this is; one of the constants above. */
    public String getResult() {
        return result;
    }

    /** The variant, typed by {@code result}, or the raw JSON if unrecognised. */
    public Object getValue() {
        return value;
    }

    /** The value when {@code result} is {@code success}, else null. */
    public TONEmulationResultSuccess asSuccess() {
        return value instanceof TONEmulationResultSuccess ? (TONEmulationResultSuccess) value : null;
    }

    /** The value when {@code result} is {@code error}, else null. */
    public TONEmulationResultError asError() {
        return value instanceof TONEmulationResultError ? (TONEmulationResultError) value : null;
    }

    public JSONObject toJson() {
        Object encoded = asJson(value);
        JSONObject json = encoded instanceof JSONObject ? (JSONObject) encoded : new JSONObject();
        TonApiJson.put(json, "result", result);
        return json;
    }

    private static Object asJson(Object value) {
        if (value instanceof TONEmulationResultSuccess) {
            return ((TONEmulationResultSuccess) value).toJson();
        }
        if (value instanceof TONEmulationResultError) {
            return ((TONEmulationResultError) value).toJson();
        }
        return value;
    }

    public static TONEmulationResult fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONEmulationResult out = new TONEmulationResult();
        out.result = TonApiJson.optString(json, "result");
        JSONObject payload = json;
        if (SUCCESS.equals(out.result)) {
            out.value = TONEmulationResultSuccess.fromJson(payload);
        } else if (ERROR.equals(out.result)) {
            out.value = TONEmulationResultError.fromJson(payload);
        } else {
            out.value = payload;
        }
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
