//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

/** Storage phase of transaction execution. */
public class TONEmulationStoragePhase {

    /** Builds one of these from JSON. */
    public static final Parser<TONEmulationStoragePhase> PARSER = new Parser<TONEmulationStoragePhase>() {
        @Override
        public TONEmulationStoragePhase parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private String statusChange;
    private String storageFeesCollected;

    /**
     * Account status change applied during the storage phase
     * Required by the API.
     */
    public String getStatusChange() {
        return statusChange;
    }

    public TONEmulationStoragePhase setStatusChange(String value) {
        this.statusChange = value;
        return this;
    }

    /**
     * Storage fees collected during this phase in nanotons
     * Required by the API.
     */
    public String getStorageFeesCollected() {
        return storageFeesCollected;
    }

    public TONEmulationStoragePhase setStorageFeesCollected(String value) {
        this.storageFeesCollected = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "statusChange", statusChange);
        TonApiJson.put(json, "storageFeesCollected", storageFeesCollected);
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONEmulationStoragePhase fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONEmulationStoragePhase out = new TONEmulationStoragePhase();
        out.statusChange = TonApiJson.optString(json, "statusChange");
        out.storageFeesCollected = TonApiJson.optString(json, "storageFeesCollected");
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
