/*
 * TON WalletKit models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ton.walletkit.api;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.ton.walletkit.api.TONRawStackItem;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.ton.walletkit.api.JSON;

/**
 * TONGetMethodResult
 */
public class TONGetMethodResult {
  public static final String SERIALIZED_NAME_EXIT_CODE = "exitCode";
  @SerializedName(SERIALIZED_NAME_EXIT_CODE)
  private BigDecimal exitCode;

  public static final String SERIALIZED_NAME_GAS_USED = "gasUsed";
  @SerializedName(SERIALIZED_NAME_GAS_USED)
  private BigDecimal gasUsed;

  public static final String SERIALIZED_NAME_STACK = "stack";
  @SerializedName(SERIALIZED_NAME_STACK)
  private List<TONRawStackItem> stack = new ArrayList<>();

  public TONGetMethodResult() {
  }

  public TONGetMethodResult exitCode(BigDecimal exitCode) {
    this.exitCode = exitCode;
    return this;
  }

  /**
   * Get exitCode
   * @return exitCode
   */
  public BigDecimal getExitCode() {
    return exitCode;
  }

  public void setExitCode(BigDecimal exitCode) {
    this.exitCode = exitCode;
  }


  public TONGetMethodResult gasUsed(BigDecimal gasUsed) {
    this.gasUsed = gasUsed;
    return this;
  }

  /**
   * Get gasUsed
   * @return gasUsed
   */
  public BigDecimal getGasUsed() {
    return gasUsed;
  }

  public void setGasUsed(BigDecimal gasUsed) {
    this.gasUsed = gasUsed;
  }


  public TONGetMethodResult stack(List<TONRawStackItem> stack) {
    this.stack = stack;
    return this;
  }

  public TONGetMethodResult addStackItem(TONRawStackItem stackItem) {
    if (this.stack == null) {
      this.stack = new ArrayList<>();
    }
    this.stack.add(stackItem);
    return this;
  }

  /**
   * Get stack
   * @return stack
   */
  public List<TONRawStackItem> getStack() {
    return stack;
  }

  public void setStack(List<TONRawStackItem> stack) {
    this.stack = stack;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TONGetMethodResult getMethodResult = (TONGetMethodResult) o;
    return Objects.equals(this.exitCode, getMethodResult.exitCode) &&
        Objects.equals(this.gasUsed, getMethodResult.gasUsed) &&
        Objects.equals(this.stack, getMethodResult.stack);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exitCode, gasUsed, stack);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TONGetMethodResult {\n");
    sb.append("    exitCode: ").append(toIndentedString(exitCode)).append("\n");
    sb.append("    gasUsed: ").append(toIndentedString(gasUsed)).append("\n");
    sb.append("    stack: ").append(toIndentedString(stack)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("exitCode");
    openapiFields.add("gasUsed");
    openapiFields.add("stack");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("exitCode");
    openapiRequiredFields.add("gasUsed");
    openapiRequiredFields.add("stack");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TONGetMethodResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TONGetMethodResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TONGetMethodResult is not found in the empty JSON string", TONGetMethodResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TONGetMethodResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TONGetMethodResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TONGetMethodResult.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("stack").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `stack` to be an array in the JSON string but got `%s`", jsonObj.get("stack").toString()));
      }

      JsonArray jsonArraystack = jsonObj.getAsJsonArray("stack");
      // validate the required field `stack` (array)
      for (int i = 0; i < jsonArraystack.size(); i++) {
        TONRawStackItem.validateJsonElement(jsonArraystack.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TONGetMethodResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TONGetMethodResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TONGetMethodResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TONGetMethodResult.class));

       return (TypeAdapter<T>) new TypeAdapter<TONGetMethodResult>() {
           @Override
           public void write(JsonWriter out, TONGetMethodResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TONGetMethodResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TONGetMethodResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TONGetMethodResult
   * @throws IOException if the JSON string is invalid with respect to TONGetMethodResult
   */
  public static TONGetMethodResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TONGetMethodResult.class);
  }

  /**
   * Convert an instance of TONGetMethodResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

