/*
 * TON WalletKit models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ton.walletkit.api;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.ton.walletkit.api.TONNetwork;
import org.ton.walletkit.api.TONTransactionRequestMessage;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.ton.walletkit.api.JSON;

/**
 * Parameters to quote a gasless transaction.  The relayer wraps the caller&#39;s messages with fee-collection logic and returns a new set of messages that the wallet should sign via &#x60;signMessage&#x60;.
 */
public class TONGaslessQuoteParams {
  public static final String SERIALIZED_NAME_FEE_ASSET = "feeAsset";
  @SerializedName(SERIALIZED_NAME_FEE_ASSET)
  private String feeAsset;

  public static final String SERIALIZED_NAME_MESSAGES = "messages";
  @SerializedName(SERIALIZED_NAME_MESSAGES)
  private List<TONTransactionRequestMessage> messages = new ArrayList<>();

  public static final String SERIALIZED_NAME_NETWORK = "network";
  @SerializedName(SERIALIZED_NAME_NETWORK)
  private TONNetwork network;

  public static final String SERIALIZED_NAME_WALLET_ADDRESS = "walletAddress";
  @SerializedName(SERIALIZED_NAME_WALLET_ADDRESS)
  private String walletAddress;

  public TONGaslessQuoteParams() {
  }

  public TONGaslessQuoteParams feeAsset(String feeAsset) {
    this.feeAsset = feeAsset;
    return this;
  }

  /**
   * User-friendly TON address representation (e.g., \&quot;EQDtFpEwcFAEcRe5mLVh2N6C0x-_hJEM7W61_JLnSF74p4q2\&quot;)
   * @return feeAsset
   */
  public String getFeeAsset() {
    return feeAsset;
  }

  public void setFeeAsset(String feeAsset) {
    this.feeAsset = feeAsset;
  }


  public TONGaslessQuoteParams messages(List<TONTransactionRequestMessage> messages) {
    this.messages = messages;
    return this;
  }

  public TONGaslessQuoteParams addMessagesItem(TONTransactionRequestMessage messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<>();
    }
    this.messages.add(messagesItem);
    return this;
  }

  /**
   * Messages that the caller wants to include in the transaction
   * @return messages
   */
  public List<TONTransactionRequestMessage> getMessages() {
    return messages;
  }

  public void setMessages(List<TONTransactionRequestMessage> messages) {
    this.messages = messages;
  }


  public TONGaslessQuoteParams network(TONNetwork network) {
    this.network = network;
    return this;
  }

  /**
   * Get network
   * @return network
   */
  public TONNetwork getNetwork() {
    return network;
  }

  public void setNetwork(TONNetwork network) {
    this.network = network;
  }


  public TONGaslessQuoteParams walletAddress(String walletAddress) {
    this.walletAddress = walletAddress;
    return this;
  }

  /**
   * User-friendly TON address representation (e.g., \&quot;EQDtFpEwcFAEcRe5mLVh2N6C0x-_hJEM7W61_JLnSF74p4q2\&quot;)
   * @return walletAddress
   */
  public String getWalletAddress() {
    return walletAddress;
  }

  public void setWalletAddress(String walletAddress) {
    this.walletAddress = walletAddress;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TONGaslessQuoteParams gaslessQuoteParams = (TONGaslessQuoteParams) o;
    return Objects.equals(this.feeAsset, gaslessQuoteParams.feeAsset) &&
        Objects.equals(this.messages, gaslessQuoteParams.messages) &&
        Objects.equals(this.network, gaslessQuoteParams.network) &&
        Objects.equals(this.walletAddress, gaslessQuoteParams.walletAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(feeAsset, messages, network, walletAddress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TONGaslessQuoteParams {\n");
    sb.append("    feeAsset: ").append(toIndentedString(feeAsset)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    walletAddress: ").append(toIndentedString(walletAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("feeAsset");
    openapiFields.add("messages");
    openapiFields.add("network");
    openapiFields.add("walletAddress");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("messages");
    openapiRequiredFields.add("network");
    openapiRequiredFields.add("walletAddress");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TONGaslessQuoteParams
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TONGaslessQuoteParams.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TONGaslessQuoteParams is not found in the empty JSON string", TONGaslessQuoteParams.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TONGaslessQuoteParams.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TONGaslessQuoteParams` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TONGaslessQuoteParams.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("feeAsset") != null && !jsonObj.get("feeAsset").isJsonNull()) && !jsonObj.get("feeAsset").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `feeAsset` to be a primitive type in the JSON string but got `%s`", jsonObj.get("feeAsset").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("messages").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `messages` to be an array in the JSON string but got `%s`", jsonObj.get("messages").toString()));
      }

      JsonArray jsonArraymessages = jsonObj.getAsJsonArray("messages");
      // validate the required field `messages` (array)
      for (int i = 0; i < jsonArraymessages.size(); i++) {
        TONTransactionRequestMessage.validateJsonElement(jsonArraymessages.get(i));
      };
      // validate the required field `network`
      TONNetwork.validateJsonElement(jsonObj.get("network"));
      if (!jsonObj.get("walletAddress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `walletAddress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("walletAddress").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TONGaslessQuoteParams.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TONGaslessQuoteParams' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TONGaslessQuoteParams> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TONGaslessQuoteParams.class));

       return (TypeAdapter<T>) new TypeAdapter<TONGaslessQuoteParams>() {
           @Override
           public void write(JsonWriter out, TONGaslessQuoteParams value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TONGaslessQuoteParams read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TONGaslessQuoteParams given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TONGaslessQuoteParams
   * @throws IOException if the JSON string is invalid with respect to TONGaslessQuoteParams
   */
  public static TONGaslessQuoteParams fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TONGaslessQuoteParams.class);
  }

  /**
   * Convert an instance of TONGaslessQuoteParams to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

