/*
 * TON WalletKit models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ton.walletkit.api;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.ton.walletkit.api.TONGaslessSupportedAsset;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.ton.walletkit.api.JSON;

/**
 * Provider-level configuration for a gasless relayer on a given network.  Bundles every piece of provider state a consumer needs to drive a gasless transfer end-to-end:  - &#x60;relayAddress&#x60; — where the relayer wants residual TON (e.g. jetton-transfer    &#x60;responseDestination&#x60;) returned to.  - &#x60;supportedAssets&#x60; — what the relayer accepts as fee payment.
 */
public class TONGaslessConfig {
  public static final String SERIALIZED_NAME_RELAY_ADDRESS = "relayAddress";
  @SerializedName(SERIALIZED_NAME_RELAY_ADDRESS)
  private String relayAddress;

  public static final String SERIALIZED_NAME_SUPPORTED_ASSETS = "supportedAssets";
  @SerializedName(SERIALIZED_NAME_SUPPORTED_ASSETS)
  private List<TONGaslessSupportedAsset> supportedAssets = new ArrayList<>();

  public TONGaslessConfig() {
  }

  public TONGaslessConfig relayAddress(String relayAddress) {
    this.relayAddress = relayAddress;
    return this;
  }

  /**
   * User-friendly TON address representation (e.g., \&quot;EQDtFpEwcFAEcRe5mLVh2N6C0x-_hJEM7W61_JLnSF74p4q2\&quot;)
   * @return relayAddress
   */
  public String getRelayAddress() {
    return relayAddress;
  }

  public void setRelayAddress(String relayAddress) {
    this.relayAddress = relayAddress;
  }


  public TONGaslessConfig supportedAssets(List<TONGaslessSupportedAsset> supportedAssets) {
    this.supportedAssets = supportedAssets;
    return this;
  }

  public TONGaslessConfig addSupportedAssetsItem(TONGaslessSupportedAsset supportedAssetsItem) {
    if (this.supportedAssets == null) {
      this.supportedAssets = new ArrayList<>();
    }
    this.supportedAssets.add(supportedAssetsItem);
    return this;
  }

  /**
   * Assets the relayer accepts as fee payment.
   * @return supportedAssets
   */
  public List<TONGaslessSupportedAsset> getSupportedAssets() {
    return supportedAssets;
  }

  public void setSupportedAssets(List<TONGaslessSupportedAsset> supportedAssets) {
    this.supportedAssets = supportedAssets;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TONGaslessConfig gaslessConfig = (TONGaslessConfig) o;
    return Objects.equals(this.relayAddress, gaslessConfig.relayAddress) &&
        Objects.equals(this.supportedAssets, gaslessConfig.supportedAssets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(relayAddress, supportedAssets);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TONGaslessConfig {\n");
    sb.append("    relayAddress: ").append(toIndentedString(relayAddress)).append("\n");
    sb.append("    supportedAssets: ").append(toIndentedString(supportedAssets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("relayAddress");
    openapiFields.add("supportedAssets");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("relayAddress");
    openapiRequiredFields.add("supportedAssets");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TONGaslessConfig
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TONGaslessConfig.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TONGaslessConfig is not found in the empty JSON string", TONGaslessConfig.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TONGaslessConfig.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TONGaslessConfig` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TONGaslessConfig.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("relayAddress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `relayAddress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("relayAddress").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("supportedAssets").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `supportedAssets` to be an array in the JSON string but got `%s`", jsonObj.get("supportedAssets").toString()));
      }

      JsonArray jsonArraysupportedAssets = jsonObj.getAsJsonArray("supportedAssets");
      // validate the required field `supportedAssets` (array)
      for (int i = 0; i < jsonArraysupportedAssets.size(); i++) {
        TONGaslessSupportedAsset.validateJsonElement(jsonArraysupportedAssets.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TONGaslessConfig.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TONGaslessConfig' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TONGaslessConfig> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TONGaslessConfig.class));

       return (TypeAdapter<T>) new TypeAdapter<TONGaslessConfig>() {
           @Override
           public void write(JsonWriter out, TONGaslessConfig value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TONGaslessConfig read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TONGaslessConfig given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TONGaslessConfig
   * @throws IOException if the JSON string is invalid with respect to TONGaslessConfig
   */
  public static TONGaslessConfig fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TONGaslessConfig.class);
  }

  /**
   * Convert an instance of TONGaslessConfig to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

