//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import java.util.List;
import java.util.Map;

import org.json.JSONArray;
import org.json.JSONObject;

/** Jetton fungible token on the TON blockchain (TEP-74 standard). */
public class TONJetton {

    /** Builds one of these from JSON. */
    public static final Parser<TONJetton> PARSER = new Parser<TONJetton>() {
        @Override
        public TONJetton parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private String address;
    private String balance;
    private Double decimalsNumber;
    private Map<String, Object> extra;
    private TONTokenInfo info;
    private Boolean isVerified;
    private List<TONJettonPrice> prices;
    private String walletAddress;

    /**
     * The Jetton contract address
     * Required by the API.
     */
    public String getAddress() {
        return address;
    }

    public TONJetton setAddress(String value) {
        this.address = value;
        return this;
    }

    /**
     * The current jetton balance
     * Required by the API.
     */
    public String getBalance() {
        return balance;
    }

    public TONJetton setBalance(String value) {
        this.balance = value;
        return this;
    }

    /** The number of decimal places used by the token */
    public Double getDecimalsNumber() {
        return decimalsNumber;
    }

    public TONJetton setDecimalsNumber(Double value) {
        this.decimalsNumber = value;
        return this;
    }

    /** Additional arbitrary data related to the jetton */
    public Map<String, Object> getExtra() {
        return extra;
    }

    public TONJetton setExtra(Map<String, Object> value) {
        this.extra = value;
        return this;
    }

    /**
     * Information about the token
     * Required by the API.
     */
    public TONTokenInfo getInfo() {
        return info;
    }

    public TONJetton setInfo(TONTokenInfo value) {
        this.info = value;
        return this;
    }

    /**
     * Indicates if the jetton is verified
     * Required by the API.
     */
    public Boolean getIsVerified() {
        return isVerified;
    }

    public TONJetton setIsVerified(Boolean value) {
        this.isVerified = value;
        return this;
    }

    /**
     * Current prices of the jetton in various currencies
     * Required by the API.
     */
    public List<TONJettonPrice> getPrices() {
        return prices;
    }

    public TONJetton setPrices(List<TONJettonPrice> value) {
        this.prices = value;
        return this;
    }

    /**
     * The Jetton wallet address
     * Required by the API.
     */
    public String getWalletAddress() {
        return walletAddress;
    }

    public TONJetton setWalletAddress(String value) {
        this.walletAddress = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "address", address);
        TonApiJson.put(json, "balance", balance);
        TonApiJson.put(json, "decimalsNumber", decimalsNumber);
        TonApiJson.put(json, "extra", TonApiJson.object(extra));
        TonApiJson.put(json, "info", info == null ? null : info.toJson());
        TonApiJson.put(json, "isVerified", isVerified);
        if (prices != null) {
            JSONArray array = new JSONArray();
            for (TONJettonPrice item : prices) {
                array.put(item == null ? JSONObject.NULL : item.toJson());
            }
            TonApiJson.put(json, "prices", array);
        }
        TonApiJson.put(json, "walletAddress", walletAddress);
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONJetton fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONJetton out = new TONJetton();
        out.address = TonApiJson.optString(json, "address");
        out.balance = TonApiJson.optString(json, "balance");
        out.decimalsNumber = TonApiJson.optDouble(json, "decimalsNumber");
        out.extra = TonApiJson.anyMap(TonApiJson.optObject(json, "extra"));
        out.info = TONTokenInfo.fromJson(TonApiJson.optObject(json, "info"));
        out.isVerified = TonApiJson.optBoolean(json, "isVerified");
        out.prices = TonApiJson.list(TonApiJson.optArray(json, "prices"), TONJettonPrice.PARSER);
        out.walletAddress = TonApiJson.optString(json, "walletAddress");
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
