/*
 * TON WalletKit models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ton.walletkit.api;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.ton.walletkit.api.JSON;

/**
 * TONJettonTransferItem
 */
public class TONJettonTransferItem {
  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private String amount;

  public static final String SERIALIZED_NAME_ATTACH_AMOUNT = "attachAmount";
  @SerializedName(SERIALIZED_NAME_ATTACH_AMOUNT)
  private String attachAmount;

  public static final String SERIALIZED_NAME_CUSTOM_PAYLOAD = "customPayload";
  @SerializedName(SERIALIZED_NAME_CUSTOM_PAYLOAD)
  private String customPayload;

  public static final String SERIALIZED_NAME_DESTINATION = "destination";
  @SerializedName(SERIALIZED_NAME_DESTINATION)
  private String destination;

  public static final String SERIALIZED_NAME_FORWARD_AMOUNT = "forwardAmount";
  @SerializedName(SERIALIZED_NAME_FORWARD_AMOUNT)
  private String forwardAmount;

  public static final String SERIALIZED_NAME_FORWARD_PAYLOAD = "forwardPayload";
  @SerializedName(SERIALIZED_NAME_FORWARD_PAYLOAD)
  private String forwardPayload;

  public static final String SERIALIZED_NAME_MASTER = "master";
  @SerializedName(SERIALIZED_NAME_MASTER)
  private String master;

  public static final String SERIALIZED_NAME_QUERY_ID = "queryId";
  @SerializedName(SERIALIZED_NAME_QUERY_ID)
  private String queryId;

  public static final String SERIALIZED_NAME_RESPONSE_DESTINATION = "responseDestination";
  @SerializedName(SERIALIZED_NAME_RESPONSE_DESTINATION)
  private String responseDestination;

  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    JETTON("jetton");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;

  public TONJettonTransferItem() {
  }

  public TONJettonTransferItem amount(String amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Get amount
   * @return amount
   */
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }


  public TONJettonTransferItem attachAmount(String attachAmount) {
    this.attachAmount = attachAmount;
    return this;
  }

  /**
   * Get attachAmount
   * @return attachAmount
   */
  public String getAttachAmount() {
    return attachAmount;
  }

  public void setAttachAmount(String attachAmount) {
    this.attachAmount = attachAmount;
  }


  public TONJettonTransferItem customPayload(String customPayload) {
    this.customPayload = customPayload;
    return this;
  }

  /**
   * Base64-encoded string representation
   * @return customPayload
   */
  public String getCustomPayload() {
    return customPayload;
  }

  public void setCustomPayload(String customPayload) {
    this.customPayload = customPayload;
  }


  public TONJettonTransferItem destination(String destination) {
    this.destination = destination;
    return this;
  }

  /**
   * Get destination
   * @return destination
   */
  public String getDestination() {
    return destination;
  }

  public void setDestination(String destination) {
    this.destination = destination;
  }


  public TONJettonTransferItem forwardAmount(String forwardAmount) {
    this.forwardAmount = forwardAmount;
    return this;
  }

  /**
   * Get forwardAmount
   * @return forwardAmount
   */
  public String getForwardAmount() {
    return forwardAmount;
  }

  public void setForwardAmount(String forwardAmount) {
    this.forwardAmount = forwardAmount;
  }


  public TONJettonTransferItem forwardPayload(String forwardPayload) {
    this.forwardPayload = forwardPayload;
    return this;
  }

  /**
   * Base64-encoded string representation
   * @return forwardPayload
   */
  public String getForwardPayload() {
    return forwardPayload;
  }

  public void setForwardPayload(String forwardPayload) {
    this.forwardPayload = forwardPayload;
  }


  public TONJettonTransferItem master(String master) {
    this.master = master;
    return this;
  }

  /**
   * Get master
   * @return master
   */
  public String getMaster() {
    return master;
  }

  public void setMaster(String master) {
    this.master = master;
  }


  public TONJettonTransferItem queryId(String queryId) {
    this.queryId = queryId;
    return this;
  }

  /**
   * Get queryId
   * @return queryId
   */
  public String getQueryId() {
    return queryId;
  }

  public void setQueryId(String queryId) {
    this.queryId = queryId;
  }


  public TONJettonTransferItem responseDestination(String responseDestination) {
    this.responseDestination = responseDestination;
    return this;
  }

  /**
   * Get responseDestination
   * @return responseDestination
   */
  public String getResponseDestination() {
    return responseDestination;
  }

  public void setResponseDestination(String responseDestination) {
    this.responseDestination = responseDestination;
  }


  public TONJettonTransferItem type(TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TONJettonTransferItem jettonTransferItem = (TONJettonTransferItem) o;
    return Objects.equals(this.amount, jettonTransferItem.amount) &&
        Objects.equals(this.attachAmount, jettonTransferItem.attachAmount) &&
        Objects.equals(this.customPayload, jettonTransferItem.customPayload) &&
        Objects.equals(this.destination, jettonTransferItem.destination) &&
        Objects.equals(this.forwardAmount, jettonTransferItem.forwardAmount) &&
        Objects.equals(this.forwardPayload, jettonTransferItem.forwardPayload) &&
        Objects.equals(this.master, jettonTransferItem.master) &&
        Objects.equals(this.queryId, jettonTransferItem.queryId) &&
        Objects.equals(this.responseDestination, jettonTransferItem.responseDestination) &&
        Objects.equals(this.type, jettonTransferItem.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, attachAmount, customPayload, destination, forwardAmount, forwardPayload, master, queryId, responseDestination, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TONJettonTransferItem {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    attachAmount: ").append(toIndentedString(attachAmount)).append("\n");
    sb.append("    customPayload: ").append(toIndentedString(customPayload)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    forwardAmount: ").append(toIndentedString(forwardAmount)).append("\n");
    sb.append("    forwardPayload: ").append(toIndentedString(forwardPayload)).append("\n");
    sb.append("    master: ").append(toIndentedString(master)).append("\n");
    sb.append("    queryId: ").append(toIndentedString(queryId)).append("\n");
    sb.append("    responseDestination: ").append(toIndentedString(responseDestination)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("amount");
    openapiFields.add("attachAmount");
    openapiFields.add("customPayload");
    openapiFields.add("destination");
    openapiFields.add("forwardAmount");
    openapiFields.add("forwardPayload");
    openapiFields.add("master");
    openapiFields.add("queryId");
    openapiFields.add("responseDestination");
    openapiFields.add("type");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("amount");
    openapiRequiredFields.add("destination");
    openapiRequiredFields.add("master");
    openapiRequiredFields.add("type");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TONJettonTransferItem
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TONJettonTransferItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TONJettonTransferItem is not found in the empty JSON string", TONJettonTransferItem.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TONJettonTransferItem.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TONJettonTransferItem` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TONJettonTransferItem.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("amount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("amount").toString()));
      }
      if ((jsonObj.get("attachAmount") != null && !jsonObj.get("attachAmount").isJsonNull()) && !jsonObj.get("attachAmount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `attachAmount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("attachAmount").toString()));
      }
      if ((jsonObj.get("customPayload") != null && !jsonObj.get("customPayload").isJsonNull()) && !jsonObj.get("customPayload").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customPayload` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customPayload").toString()));
      }
      if (!jsonObj.get("destination").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `destination` to be a primitive type in the JSON string but got `%s`", jsonObj.get("destination").toString()));
      }
      if ((jsonObj.get("forwardAmount") != null && !jsonObj.get("forwardAmount").isJsonNull()) && !jsonObj.get("forwardAmount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `forwardAmount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("forwardAmount").toString()));
      }
      if ((jsonObj.get("forwardPayload") != null && !jsonObj.get("forwardPayload").isJsonNull()) && !jsonObj.get("forwardPayload").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `forwardPayload` to be a primitive type in the JSON string but got `%s`", jsonObj.get("forwardPayload").toString()));
      }
      if (!jsonObj.get("master").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `master` to be a primitive type in the JSON string but got `%s`", jsonObj.get("master").toString()));
      }
      if ((jsonObj.get("queryId") != null && !jsonObj.get("queryId").isJsonNull()) && !jsonObj.get("queryId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `queryId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("queryId").toString()));
      }
      if ((jsonObj.get("responseDestination") != null && !jsonObj.get("responseDestination").isJsonNull()) && !jsonObj.get("responseDestination").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `responseDestination` to be a primitive type in the JSON string but got `%s`", jsonObj.get("responseDestination").toString()));
      }
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      // validate the required field `type`
      TypeEnum.validateJsonElement(jsonObj.get("type"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TONJettonTransferItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TONJettonTransferItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TONJettonTransferItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TONJettonTransferItem.class));

       return (TypeAdapter<T>) new TypeAdapter<TONJettonTransferItem>() {
           @Override
           public void write(JsonWriter out, TONJettonTransferItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TONJettonTransferItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TONJettonTransferItem given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TONJettonTransferItem
   * @throws IOException if the JSON string is invalid with respect to TONJettonTransferItem
   */
  public static TONJettonTransferItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TONJettonTransferItem.class);
  }

  /**
   * Convert an instance of TONJettonTransferItem to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

