//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

public class TONJettonPrice {

    /** Builds one of these from JSON. */
    public static final Parser<TONJettonPrice> PARSER = new Parser<TONJettonPrice>() {
        @Override
        public TONJettonPrice parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private String currency;
    private String value;

    /**
     * Currency code (e.g., "USD", "EUR")
     * Required by the API.
     */
    public String getCurrency() {
        return currency;
    }

    public TONJettonPrice setCurrency(String value) {
        this.currency = value;
        return this;
    }

    /**
     * Price in smallest units of the currency
     * Required by the API.
     */
    public String getValue() {
        return value;
    }

    public TONJettonPrice setValue(String value) {
        this.value = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "currency", currency);
        TonApiJson.put(json, "value", value);
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONJettonPrice fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONJettonPrice out = new TONJettonPrice();
        out.currency = TonApiJson.optString(json, "currency");
        out.value = TonApiJson.optString(json, "value");
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
