//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

/** Request parameters for fetching Jetton tokens. */
public class TONJettonsRequest {

    /** Builds one of these from JSON. */
    public static final Parser<TONJettonsRequest> PARSER = new Parser<TONJettonsRequest>() {
        @Override
        public TONJettonsRequest parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private TONPagination pagination;

    /**
     * Pagination information
     * Required by the API.
     */
    public TONPagination getPagination() {
        return pagination;
    }

    public TONJettonsRequest setPagination(TONPagination value) {
        this.pagination = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "pagination", pagination == null ? null : pagination.toJson());
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONJettonsRequest fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONJettonsRequest out = new TONJettonsRequest();
        out.pagination = TONPagination.fromJson(TonApiJson.optObject(json, "pagination"));
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
