//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

public class TONJettonUpdate {

    /** Builds one of these from JSON. */
    public static final Parser<TONJettonUpdate> PARSER = new Parser<TONJettonUpdate>() {
        @Override
        public TONJettonUpdate parse(JSONObject json) {
            return fromJson(json);
        }
    };

    /** Values this property accepts. */
    public enum TypeEnum {

        JETTONS("jettons");

        private final String value;

        TypeEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static TypeEnum fromValue(Object wire) {
            if (wire == null) {
                return null;
            }
            String text = wire.toString();
            for (TypeEnum candidate : values()) {
                if (candidate.value.equals(text)) {
                    return candidate;
                }
            }
            return null;
        }
    }

    private String balance;
    private Double decimals;
    private String masterAddress;
    private String ownerAddress;
    private String rawBalance;
    private TONStreamingUpdateStatus status;
    private TypeEnum type;
    private String walletAddress;

    /** Human readable formatted balance if decimals are known */
    public String getBalance() {
        return balance;
    }

    public TONJettonUpdate setBalance(String value) {
        this.balance = value;
        return this;
    }

    /** Decimals mapped from metadata if available */
    public Double getDecimals() {
        return decimals;
    }

    public TONJettonUpdate setDecimals(Double value) {
        this.decimals = value;
        return this;
    }

    /**
     * The master jetton contract address
     * Required by the API.
     */
    public String getMasterAddress() {
        return masterAddress;
    }

    public TONJettonUpdate setMasterAddress(String value) {
        this.masterAddress = value;
        return this;
    }

    /**
     * The owner of the jetton wallet
     * Required by the API.
     */
    public String getOwnerAddress() {
        return ownerAddress;
    }

    public TONJettonUpdate setOwnerAddress(String value) {
        this.ownerAddress = value;
        return this;
    }

    /**
     * Balance in raw smallest units (e.g. nano)
     * Required by the API.
     */
    public String getRawBalance() {
        return rawBalance;
    }

    public TONJettonUpdate setRawBalance(String value) {
        this.rawBalance = value;
        return this;
    }

    /**
     * The finality of the update
     * Required by the API.
     */
    public TONStreamingUpdateStatus getStatus() {
        return status;
    }

    public TONJettonUpdate setStatus(TONStreamingUpdateStatus value) {
        this.status = value;
        return this;
    }

    /**
     * The update type field
     * Required by the API.
     */
    public TypeEnum getType() {
        return type;
    }

    public TONJettonUpdate setType(TypeEnum value) {
        this.type = value;
        return this;
    }

    /**
     * The jetton wallet contract address
     * Required by the API.
     */
    public String getWalletAddress() {
        return walletAddress;
    }

    public TONJettonUpdate setWalletAddress(String value) {
        this.walletAddress = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "balance", balance);
        TonApiJson.put(json, "decimals", decimals);
        TonApiJson.put(json, "masterAddress", masterAddress);
        TonApiJson.put(json, "ownerAddress", ownerAddress);
        TonApiJson.put(json, "rawBalance", rawBalance);
        TonApiJson.put(json, "status", status == null ? null : status.getValue());
        TonApiJson.put(json, "type", type == null ? null : type.getValue());
        TonApiJson.put(json, "walletAddress", walletAddress);
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONJettonUpdate fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONJettonUpdate out = new TONJettonUpdate();
        out.balance = TonApiJson.optString(json, "balance");
        out.decimals = TonApiJson.optDouble(json, "decimals");
        out.masterAddress = TonApiJson.optString(json, "masterAddress");
        out.ownerAddress = TonApiJson.optString(json, "ownerAddress");
        out.rawBalance = TonApiJson.optString(json, "rawBalance");
        out.status = TONStreamingUpdateStatus.fromValue(TonApiJson.opt(json, "status"));
        out.type = TypeEnum.fromValue(TonApiJson.opt(json, "type"));
        out.walletAddress = TonApiJson.optString(json, "walletAddress");
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
