//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

public class TONManifestFetchResult {

    /** Builds one of these from JSON. */
    public static final Parser<TONManifestFetchResult> PARSER = new Parser<TONManifestFetchResult>() {
        @Override
        public TONManifestFetchResult parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private Object manifest;
    private TONCONNECTEVENTERRORCODES manifestFetchErrorCode;

    /** Required by the API. */
    public Object getManifest() {
        return manifest;
    }

    public TONManifestFetchResult setManifest(Object value) {
        this.manifest = value;
        return this;
    }

    public TONCONNECTEVENTERRORCODES getManifestFetchErrorCode() {
        return manifestFetchErrorCode;
    }

    public TONManifestFetchResult setManifestFetchErrorCode(TONCONNECTEVENTERRORCODES value) {
        this.manifestFetchErrorCode = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "manifest", manifest);
        TonApiJson.put(json, "manifestFetchErrorCode", manifestFetchErrorCode == null ? null : manifestFetchErrorCode.getValue());
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONManifestFetchResult fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONManifestFetchResult out = new TONManifestFetchResult();
        out.manifest = TonApiJson.opt(json, "manifest");
        out.manifestFetchErrorCode = TONCONNECTEVENTERRORCODES.fromValue(TonApiJson.opt(json, "manifestFetchErrorCode"));
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
