/*
 * TON WalletKit models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ton.walletkit.api;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.ton.walletkit.api.JSON;

/**
 * TONNFTRawTransferRequestMessage
 */
public class TONNFTRawTransferRequestMessage {
  public static final String SERIALIZED_NAME_CUSTOM_PAYLOAD = "customPayload";
  @SerializedName(SERIALIZED_NAME_CUSTOM_PAYLOAD)
  private String customPayload;

  public static final String SERIALIZED_NAME_FORWARD_AMOUNT = "forwardAmount";
  @SerializedName(SERIALIZED_NAME_FORWARD_AMOUNT)
  private String forwardAmount;

  public static final String SERIALIZED_NAME_FORWARD_PAYLOAD = "forwardPayload";
  @SerializedName(SERIALIZED_NAME_FORWARD_PAYLOAD)
  private String forwardPayload;

  public static final String SERIALIZED_NAME_NEW_OWNER = "newOwner";
  @SerializedName(SERIALIZED_NAME_NEW_OWNER)
  private String newOwner;

  public static final String SERIALIZED_NAME_QUERY_ID = "queryId";
  @SerializedName(SERIALIZED_NAME_QUERY_ID)
  private String queryId;

  public static final String SERIALIZED_NAME_RESPONSE_DESTINATION = "responseDestination";
  @SerializedName(SERIALIZED_NAME_RESPONSE_DESTINATION)
  private String responseDestination;

  public TONNFTRawTransferRequestMessage() {
  }

  public TONNFTRawTransferRequestMessage customPayload(String customPayload) {
    this.customPayload = customPayload;
    return this;
  }

  /**
   * Base64-encoded string representation
   * @return customPayload
   */
  public String getCustomPayload() {
    return customPayload;
  }

  public void setCustomPayload(String customPayload) {
    this.customPayload = customPayload;
  }


  public TONNFTRawTransferRequestMessage forwardAmount(String forwardAmount) {
    this.forwardAmount = forwardAmount;
    return this;
  }

  /**
   * Get forwardAmount
   * @return forwardAmount
   */
  public String getForwardAmount() {
    return forwardAmount;
  }

  public void setForwardAmount(String forwardAmount) {
    this.forwardAmount = forwardAmount;
  }


  public TONNFTRawTransferRequestMessage forwardPayload(String forwardPayload) {
    this.forwardPayload = forwardPayload;
    return this;
  }

  /**
   * Base64-encoded string representation
   * @return forwardPayload
   */
  public String getForwardPayload() {
    return forwardPayload;
  }

  public void setForwardPayload(String forwardPayload) {
    this.forwardPayload = forwardPayload;
  }


  public TONNFTRawTransferRequestMessage newOwner(String newOwner) {
    this.newOwner = newOwner;
    return this;
  }

  /**
   * User-friendly TON address representation (e.g., \&quot;EQDtFpEwcFAEcRe5mLVh2N6C0x-_hJEM7W61_JLnSF74p4q2\&quot;)
   * @return newOwner
   */
  public String getNewOwner() {
    return newOwner;
  }

  public void setNewOwner(String newOwner) {
    this.newOwner = newOwner;
  }


  public TONNFTRawTransferRequestMessage queryId(String queryId) {
    this.queryId = queryId;
    return this;
  }

  /**
   * Get queryId
   * @return queryId
   */
  public String getQueryId() {
    return queryId;
  }

  public void setQueryId(String queryId) {
    this.queryId = queryId;
  }


  public TONNFTRawTransferRequestMessage responseDestination(String responseDestination) {
    this.responseDestination = responseDestination;
    return this;
  }

  /**
   * User-friendly TON address representation (e.g., \&quot;EQDtFpEwcFAEcRe5mLVh2N6C0x-_hJEM7W61_JLnSF74p4q2\&quot;)
   * @return responseDestination
   */
  public String getResponseDestination() {
    return responseDestination;
  }

  public void setResponseDestination(String responseDestination) {
    this.responseDestination = responseDestination;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TONNFTRawTransferRequestMessage nfTRawTransferRequestMessage = (TONNFTRawTransferRequestMessage) o;
    return Objects.equals(this.customPayload, nfTRawTransferRequestMessage.customPayload) &&
        Objects.equals(this.forwardAmount, nfTRawTransferRequestMessage.forwardAmount) &&
        Objects.equals(this.forwardPayload, nfTRawTransferRequestMessage.forwardPayload) &&
        Objects.equals(this.newOwner, nfTRawTransferRequestMessage.newOwner) &&
        Objects.equals(this.queryId, nfTRawTransferRequestMessage.queryId) &&
        Objects.equals(this.responseDestination, nfTRawTransferRequestMessage.responseDestination);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customPayload, forwardAmount, forwardPayload, newOwner, queryId, responseDestination);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TONNFTRawTransferRequestMessage {\n");
    sb.append("    customPayload: ").append(toIndentedString(customPayload)).append("\n");
    sb.append("    forwardAmount: ").append(toIndentedString(forwardAmount)).append("\n");
    sb.append("    forwardPayload: ").append(toIndentedString(forwardPayload)).append("\n");
    sb.append("    newOwner: ").append(toIndentedString(newOwner)).append("\n");
    sb.append("    queryId: ").append(toIndentedString(queryId)).append("\n");
    sb.append("    responseDestination: ").append(toIndentedString(responseDestination)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("customPayload");
    openapiFields.add("forwardAmount");
    openapiFields.add("forwardPayload");
    openapiFields.add("newOwner");
    openapiFields.add("queryId");
    openapiFields.add("responseDestination");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("forwardAmount");
    openapiRequiredFields.add("newOwner");
    openapiRequiredFields.add("queryId");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TONNFTRawTransferRequestMessage
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TONNFTRawTransferRequestMessage.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TONNFTRawTransferRequestMessage is not found in the empty JSON string", TONNFTRawTransferRequestMessage.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TONNFTRawTransferRequestMessage.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TONNFTRawTransferRequestMessage` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TONNFTRawTransferRequestMessage.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("customPayload") != null && !jsonObj.get("customPayload").isJsonNull()) && !jsonObj.get("customPayload").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customPayload` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customPayload").toString()));
      }
      if (!jsonObj.get("forwardAmount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `forwardAmount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("forwardAmount").toString()));
      }
      if ((jsonObj.get("forwardPayload") != null && !jsonObj.get("forwardPayload").isJsonNull()) && !jsonObj.get("forwardPayload").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `forwardPayload` to be a primitive type in the JSON string but got `%s`", jsonObj.get("forwardPayload").toString()));
      }
      if (!jsonObj.get("newOwner").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `newOwner` to be a primitive type in the JSON string but got `%s`", jsonObj.get("newOwner").toString()));
      }
      if (!jsonObj.get("queryId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `queryId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("queryId").toString()));
      }
      if ((jsonObj.get("responseDestination") != null && !jsonObj.get("responseDestination").isJsonNull()) && !jsonObj.get("responseDestination").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `responseDestination` to be a primitive type in the JSON string but got `%s`", jsonObj.get("responseDestination").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TONNFTRawTransferRequestMessage.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TONNFTRawTransferRequestMessage' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TONNFTRawTransferRequestMessage> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TONNFTRawTransferRequestMessage.class));

       return (TypeAdapter<T>) new TypeAdapter<TONNFTRawTransferRequestMessage>() {
           @Override
           public void write(JsonWriter out, TONNFTRawTransferRequestMessage value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TONNFTRawTransferRequestMessage read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TONNFTRawTransferRequestMessage given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TONNFTRawTransferRequestMessage
   * @throws IOException if the JSON string is invalid with respect to TONNFTRawTransferRequestMessage
   */
  public static TONNFTRawTransferRequestMessage fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TONNFTRawTransferRequestMessage.class);
  }

  /**
   * Convert an instance of TONNFTRawTransferRequestMessage to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

