//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

public class TONNftTransferItem {

    /** Builds one of these from JSON. */
    public static final Parser<TONNftTransferItem> PARSER = new Parser<TONNftTransferItem>() {
        @Override
        public TONNftTransferItem parse(JSONObject json) {
            return fromJson(json);
        }
    };

    /** Values this property accepts. */
    public enum TypeEnum {

        NFT("nft");

        private final String value;

        TypeEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static TypeEnum fromValue(Object wire) {
            if (wire == null) {
                return null;
            }
            String text = wire.toString();
            for (TypeEnum candidate : values()) {
                if (candidate.value.equals(text)) {
                    return candidate;
                }
            }
            return null;
        }
    }

    private String attachAmount;
    private String customPayload;
    private String forwardAmount;
    private String forwardPayload;
    private String newOwner;
    private String nftAddress;
    private String queryId;
    private String responseDestination;
    private TypeEnum type;

    public String getAttachAmount() {
        return attachAmount;
    }

    public TONNftTransferItem setAttachAmount(String value) {
        this.attachAmount = value;
        return this;
    }

    public String getCustomPayload() {
        return customPayload;
    }

    public TONNftTransferItem setCustomPayload(String value) {
        this.customPayload = value;
        return this;
    }

    public String getForwardAmount() {
        return forwardAmount;
    }

    public TONNftTransferItem setForwardAmount(String value) {
        this.forwardAmount = value;
        return this;
    }

    public String getForwardPayload() {
        return forwardPayload;
    }

    public TONNftTransferItem setForwardPayload(String value) {
        this.forwardPayload = value;
        return this;
    }

    /** Required by the API. */
    public String getNewOwner() {
        return newOwner;
    }

    public TONNftTransferItem setNewOwner(String value) {
        this.newOwner = value;
        return this;
    }

    /** Required by the API. */
    public String getNftAddress() {
        return nftAddress;
    }

    public TONNftTransferItem setNftAddress(String value) {
        this.nftAddress = value;
        return this;
    }

    public String getQueryId() {
        return queryId;
    }

    public TONNftTransferItem setQueryId(String value) {
        this.queryId = value;
        return this;
    }

    public String getResponseDestination() {
        return responseDestination;
    }

    public TONNftTransferItem setResponseDestination(String value) {
        this.responseDestination = value;
        return this;
    }

    /** Required by the API. */
    public TypeEnum getType() {
        return type;
    }

    public TONNftTransferItem setType(TypeEnum value) {
        this.type = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "attachAmount", attachAmount);
        TonApiJson.put(json, "customPayload", customPayload);
        TonApiJson.put(json, "forwardAmount", forwardAmount);
        TonApiJson.put(json, "forwardPayload", forwardPayload);
        TonApiJson.put(json, "newOwner", newOwner);
        TonApiJson.put(json, "nftAddress", nftAddress);
        TonApiJson.put(json, "queryId", queryId);
        TonApiJson.put(json, "responseDestination", responseDestination);
        TonApiJson.put(json, "type", type == null ? null : type.getValue());
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONNftTransferItem fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONNftTransferItem out = new TONNftTransferItem();
        out.attachAmount = TonApiJson.optString(json, "attachAmount");
        out.customPayload = TonApiJson.optString(json, "customPayload");
        out.forwardAmount = TonApiJson.optString(json, "forwardAmount");
        out.forwardPayload = TonApiJson.optString(json, "forwardPayload");
        out.newOwner = TonApiJson.optString(json, "newOwner");
        out.nftAddress = TonApiJson.optString(json, "nftAddress");
        out.queryId = TonApiJson.optString(json, "queryId");
        out.responseDestination = TonApiJson.optString(json, "responseDestination");
        out.type = TypeEnum.fromValue(TonApiJson.opt(json, "type"));
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
