//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

/** Request raw parameters for transferring an NFT to another address. */
public class TONNFTRawTransferRequest {

    /** Builds one of these from JSON. */
    public static final Parser<TONNFTRawTransferRequest> PARSER = new Parser<TONNFTRawTransferRequest>() {
        @Override
        public TONNFTRawTransferRequest parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private TONNFTRawTransferRequestMessage message;
    private String nftAddress;
    private String transferAmount;

    /**
     * Transfer message details
     * Required by the API.
     */
    public TONNFTRawTransferRequestMessage getMessage() {
        return message;
    }

    public TONNFTRawTransferRequest setMessage(TONNFTRawTransferRequestMessage value) {
        this.message = value;
        return this;
    }

    /**
     * Contract address of the NFT to transfer
     * Required by the API.
     */
    public String getNftAddress() {
        return nftAddress;
    }

    public TONNFTRawTransferRequest setNftAddress(String value) {
        this.nftAddress = value;
        return this;
    }

    /**
     * TON amount to attach for gas fees (default: 0.1 TON)
     * Required by the API.
     */
    public String getTransferAmount() {
        return transferAmount;
    }

    public TONNFTRawTransferRequest setTransferAmount(String value) {
        this.transferAmount = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "message", message == null ? null : message.toJson());
        TonApiJson.put(json, "nftAddress", nftAddress);
        TonApiJson.put(json, "transferAmount", transferAmount);
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONNFTRawTransferRequest fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONNFTRawTransferRequest out = new TONNFTRawTransferRequest();
        out.message = TONNFTRawTransferRequestMessage.fromJson(TonApiJson.optObject(json, "message"));
        out.nftAddress = TonApiJson.optString(json, "nftAddress");
        out.transferAmount = TonApiJson.optString(json, "transferAmount");
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
