//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

/** Base parameters for requesting a swap quote */
public class TONSwapQuoteParams {

    /** Builds one of these from JSON. */
    public static final Parser<TONSwapQuoteParams> PARSER = new Parser<TONSwapQuoteParams>() {
        @Override
        public TONSwapQuoteParams parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private String amount;
    private TONSwapToken from;
    private Boolean isReverseSwap;
    private Double maxOutgoingMessages;
    private TONNetwork network;
    private Object providerOptions;
    private Double slippageBps;
    private TONSwapToken to;

    /**
     * Amount of tokens to swap (incoming or outgoing depending on isReverseSwap)
     * Required by the API.
     */
    public String getAmount() {
        return amount;
    }

    public TONSwapQuoteParams setAmount(String value) {
        this.amount = value;
        return this;
    }

    /**
     * Token to swap from
     * Required by the API.
     */
    public TONSwapToken getFrom() {
        return from;
    }

    public TONSwapQuoteParams setFrom(TONSwapToken value) {
        this.from = value;
        return this;
    }

    /** If true, amount is the amount to receive (buy). If false, amount is the amount to spend (sell). */
    public Boolean getIsReverseSwap() {
        return isReverseSwap;
    }

    public TONSwapQuoteParams setIsReverseSwap(Boolean value) {
        this.isReverseSwap = value;
        return this;
    }

    /** Maximum number of outgoing messages */
    public Double getMaxOutgoingMessages() {
        return maxOutgoingMessages;
    }

    public TONSwapQuoteParams setMaxOutgoingMessages(Double value) {
        this.maxOutgoingMessages = value;
        return this;
    }

    /**
     * Network on which the swap will be executed
     * Required by the API.
     */
    public TONNetwork getNetwork() {
        return network;
    }

    public TONSwapQuoteParams setNetwork(TONNetwork value) {
        this.network = value;
        return this;
    }

    /** Provider-specific options */
    public Object getProviderOptions() {
        return providerOptions;
    }

    public TONSwapQuoteParams setProviderOptions(Object value) {
        this.providerOptions = value;
        return this;
    }

    /** Slippage tolerance in basis points (1 bp = 0.01%) */
    public Double getSlippageBps() {
        return slippageBps;
    }

    public TONSwapQuoteParams setSlippageBps(Double value) {
        this.slippageBps = value;
        return this;
    }

    /**
     * Token to swap to
     * Required by the API.
     */
    public TONSwapToken getTo() {
        return to;
    }

    public TONSwapQuoteParams setTo(TONSwapToken value) {
        this.to = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "amount", amount);
        TonApiJson.put(json, "from", from == null ? null : from.toJson());
        TonApiJson.put(json, "isReverseSwap", isReverseSwap);
        TonApiJson.put(json, "maxOutgoingMessages", maxOutgoingMessages);
        TonApiJson.put(json, "network", network == null ? null : network.toJson());
        TonApiJson.put(json, "providerOptions", providerOptions);
        TonApiJson.put(json, "slippageBps", slippageBps);
        TonApiJson.put(json, "to", to == null ? null : to.toJson());
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONSwapQuoteParams fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONSwapQuoteParams out = new TONSwapQuoteParams();
        out.amount = TonApiJson.optString(json, "amount");
        out.from = TONSwapToken.fromJson(TonApiJson.optObject(json, "from"));
        out.isReverseSwap = TonApiJson.optBoolean(json, "isReverseSwap");
        out.maxOutgoingMessages = TonApiJson.optDouble(json, "maxOutgoingMessages");
        out.network = TONNetwork.fromJson(TonApiJson.optObject(json, "network"));
        out.providerOptions = TonApiJson.opt(json, "providerOptions");
        out.slippageBps = TonApiJson.optDouble(json, "slippageBps");
        out.to = TONSwapToken.fromJson(TonApiJson.optObject(json, "to"));
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
