//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

public class TONSignedSendTransactionOptions {

    /** Builds one of these from JSON. */
    public static final Parser<TONSignedSendTransactionOptions> PARSER = new Parser<TONSignedSendTransactionOptions>() {
        @Override
        public TONSignedSendTransactionOptions parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private Boolean fakeSignature;

    public Boolean getFakeSignature() {
        return fakeSignature;
    }

    public TONSignedSendTransactionOptions setFakeSignature(Boolean value) {
        this.fakeSignature = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "fakeSignature", fakeSignature);
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONSignedSendTransactionOptions fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONSignedSendTransactionOptions out = new TONSignedSendTransactionOptions();
        out.fakeSignature = TonApiJson.optBoolean(json, "fakeSignature");
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
