/*
 * TON WalletKit models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ton.walletkit.api;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.ton.walletkit.api.TONSignDataPreviewAnyOf;
import org.ton.walletkit.api.TONSignDataPreviewAnyOf1;
import org.ton.walletkit.api.TONSignDataPreviewAnyOf2;
import org.ton.walletkit.api.TONSignDataPreviewCell;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import org.ton.walletkit.api.JSON;

public class TONSignDataPreview extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(TONSignDataPreview.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!TONSignDataPreview.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'TONSignDataPreview' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<TONSignDataPreviewAnyOf> adapterTONSignDataPreviewAnyOf = gson.getDelegateAdapter(this, TypeToken.get(TONSignDataPreviewAnyOf.class));
            final TypeAdapter<TONSignDataPreviewAnyOf1> adapterTONSignDataPreviewAnyOf1 = gson.getDelegateAdapter(this, TypeToken.get(TONSignDataPreviewAnyOf1.class));
            final TypeAdapter<TONSignDataPreviewAnyOf2> adapterTONSignDataPreviewAnyOf2 = gson.getDelegateAdapter(this, TypeToken.get(TONSignDataPreviewAnyOf2.class));

            return (TypeAdapter<T>) new TypeAdapter<TONSignDataPreview>() {
                @Override
                public void write(JsonWriter out, TONSignDataPreview value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `TONSignDataPreviewAnyOf`
                    if (value.getActualInstance() instanceof TONSignDataPreviewAnyOf) {
                        JsonElement element = adapterTONSignDataPreviewAnyOf.toJsonTree((TONSignDataPreviewAnyOf)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `TONSignDataPreviewAnyOf1`
                    if (value.getActualInstance() instanceof TONSignDataPreviewAnyOf1) {
                        JsonElement element = adapterTONSignDataPreviewAnyOf1.toJsonTree((TONSignDataPreviewAnyOf1)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `TONSignDataPreviewAnyOf2`
                    if (value.getActualInstance() instanceof TONSignDataPreviewAnyOf2) {
                        JsonElement element = adapterTONSignDataPreviewAnyOf2.toJsonTree((TONSignDataPreviewAnyOf2)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match anyOf schemas: TONSignDataPreviewAnyOf, TONSignDataPreviewAnyOf1, TONSignDataPreviewAnyOf2");
                }

                @Override
                public TONSignDataPreview read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize TONSignDataPreviewAnyOf
                    try {
                        // validate the JSON object to see if any exception is thrown
                        TONSignDataPreviewAnyOf.validateJsonElement(jsonElement);
                        actualAdapter = adapterTONSignDataPreviewAnyOf;
                        TONSignDataPreview ret = new TONSignDataPreview();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for TONSignDataPreviewAnyOf failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'TONSignDataPreviewAnyOf'", e);
                    }
                    // deserialize TONSignDataPreviewAnyOf1
                    try {
                        // validate the JSON object to see if any exception is thrown
                        TONSignDataPreviewAnyOf1.validateJsonElement(jsonElement);
                        actualAdapter = adapterTONSignDataPreviewAnyOf1;
                        TONSignDataPreview ret = new TONSignDataPreview();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for TONSignDataPreviewAnyOf1 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'TONSignDataPreviewAnyOf1'", e);
                    }
                    // deserialize TONSignDataPreviewAnyOf2
                    try {
                        // validate the JSON object to see if any exception is thrown
                        TONSignDataPreviewAnyOf2.validateJsonElement(jsonElement);
                        actualAdapter = adapterTONSignDataPreviewAnyOf2;
                        TONSignDataPreview ret = new TONSignDataPreview();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for TONSignDataPreviewAnyOf2 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'TONSignDataPreviewAnyOf2'", e);
                    }

                    throw new IOException(String.format("Failed deserialization for TONSignDataPreview: no class matches result, expected at least 1. Detailed failure message for anyOf schemas: %s. JSON: %s", errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public TONSignDataPreview() {
        super("anyOf", Boolean.FALSE);
    }

    public TONSignDataPreview(Object o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("TONSignDataPreviewAnyOf", TONSignDataPreviewAnyOf.class);
        schemas.put("TONSignDataPreviewAnyOf1", TONSignDataPreviewAnyOf1.class);
        schemas.put("TONSignDataPreviewAnyOf2", TONSignDataPreviewAnyOf2.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return TONSignDataPreview.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * TONSignDataPreviewAnyOf, TONSignDataPreviewAnyOf1, TONSignDataPreviewAnyOf2
     *
     * It could be an instance of the 'anyOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof TONSignDataPreviewAnyOf) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof TONSignDataPreviewAnyOf1) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof TONSignDataPreviewAnyOf2) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be TONSignDataPreviewAnyOf, TONSignDataPreviewAnyOf1, TONSignDataPreviewAnyOf2");
    }

    /**
     * Get the actual instance, which can be the following:
     * TONSignDataPreviewAnyOf, TONSignDataPreviewAnyOf1, TONSignDataPreviewAnyOf2
     *
     * @return The actual instance (TONSignDataPreviewAnyOf, TONSignDataPreviewAnyOf1, TONSignDataPreviewAnyOf2)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `TONSignDataPreviewAnyOf`. If the actual instance is not `TONSignDataPreviewAnyOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TONSignDataPreviewAnyOf`
     * @throws ClassCastException if the instance is not `TONSignDataPreviewAnyOf`
     */
    public TONSignDataPreviewAnyOf getTONSignDataPreviewAnyOf() throws ClassCastException {
        return (TONSignDataPreviewAnyOf)super.getActualInstance();
    }
    /**
     * Get the actual instance of `TONSignDataPreviewAnyOf1`. If the actual instance is not `TONSignDataPreviewAnyOf1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TONSignDataPreviewAnyOf1`
     * @throws ClassCastException if the instance is not `TONSignDataPreviewAnyOf1`
     */
    public TONSignDataPreviewAnyOf1 getTONSignDataPreviewAnyOf1() throws ClassCastException {
        return (TONSignDataPreviewAnyOf1)super.getActualInstance();
    }
    /**
     * Get the actual instance of `TONSignDataPreviewAnyOf2`. If the actual instance is not `TONSignDataPreviewAnyOf2`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TONSignDataPreviewAnyOf2`
     * @throws ClassCastException if the instance is not `TONSignDataPreviewAnyOf2`
     */
    public TONSignDataPreviewAnyOf2 getTONSignDataPreviewAnyOf2() throws ClassCastException {
        return (TONSignDataPreviewAnyOf2)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to TONSignDataPreview
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate anyOf schemas one by one
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with TONSignDataPreviewAnyOf
        try {
            TONSignDataPreviewAnyOf.validateJsonElement(jsonElement);
            return;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for TONSignDataPreviewAnyOf failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with TONSignDataPreviewAnyOf1
        try {
            TONSignDataPreviewAnyOf1.validateJsonElement(jsonElement);
            return;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for TONSignDataPreviewAnyOf1 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with TONSignDataPreviewAnyOf2
        try {
            TONSignDataPreviewAnyOf2.validateJsonElement(jsonElement);
            return;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for TONSignDataPreviewAnyOf2 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        throw new IOException(String.format("The JSON string is invalid for TONSignDataPreview with anyOf schemas: TONSignDataPreviewAnyOf, TONSignDataPreviewAnyOf1, TONSignDataPreviewAnyOf2. no class match the result, expected at least 1. Detailed failure message for anyOf schemas: %s. JSON: %s", errorMessages, jsonElement.toString()));
    }

    /**
     * Create an instance of TONSignDataPreview given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of TONSignDataPreview
     * @throws IOException if the JSON string is invalid with respect to TONSignDataPreview
     */
    public static TONSignDataPreview fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, TONSignDataPreview.class);
    }

    /**
     * Convert an instance of TONSignDataPreview to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

