//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

/** Response after user approves a sign-message request. */
public class TONSignMessageApprovalResponse {

    /** Builds one of these from JSON. */
    public static final Parser<TONSignMessageApprovalResponse> PARSER = new Parser<TONSignMessageApprovalResponse>() {
        @Override
        public TONSignMessageApprovalResponse parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private String internalBoc;

    /**
     * Signed internal message BoC (Bag of Cells) format, encoded in Base64. This is a signed internal message (internal opcode) that the dApp can relay via a third-party relayer.
     * Required by the API.
     */
    public String getInternalBoc() {
        return internalBoc;
    }

    public TONSignMessageApprovalResponse setInternalBoc(String value) {
        this.internalBoc = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "internalBoc", internalBoc);
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONSignMessageApprovalResponse fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONSignMessageApprovalResponse out = new TONSignMessageApprovalResponse();
        out.internalBoc = TonApiJson.optString(json, "internalBoc");
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
