//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import java.util.List;

import org.json.JSONArray;
import org.json.JSONObject;

/** Used in provider configuration to override fields of the provider's metadata. */
public class TONStakingProviderMetadataOverride {

    /** Builds one of these from JSON. */
    public static final Parser<TONStakingProviderMetadataOverride> PARSER = new Parser<TONStakingProviderMetadataOverride>() {
        @Override
        public TONStakingProviderMetadataOverride parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private String contractAddress;
    private String name;
    private TONStakingTokenInfo receiveToken;
    private TONStakingTokenInfo stakeToken;
    private List<TONUnstakeModes> supportedUnstakeModes;
    private Boolean supportsReversedQuote;

    public String getContractAddress() {
        return contractAddress;
    }

    public TONStakingProviderMetadataOverride setContractAddress(String value) {
        this.contractAddress = value;
        return this;
    }

    public String getName() {
        return name;
    }

    public TONStakingProviderMetadataOverride setName(String value) {
        this.name = value;
        return this;
    }

    public TONStakingTokenInfo getReceiveToken() {
        return receiveToken;
    }

    public TONStakingProviderMetadataOverride setReceiveToken(TONStakingTokenInfo value) {
        this.receiveToken = value;
        return this;
    }

    public TONStakingTokenInfo getStakeToken() {
        return stakeToken;
    }

    public TONStakingProviderMetadataOverride setStakeToken(TONStakingTokenInfo value) {
        this.stakeToken = value;
        return this;
    }

    public List<TONUnstakeModes> getSupportedUnstakeModes() {
        return supportedUnstakeModes;
    }

    public TONStakingProviderMetadataOverride setSupportedUnstakeModes(List<TONUnstakeModes> value) {
        this.supportedUnstakeModes = value;
        return this;
    }

    public Boolean getSupportsReversedQuote() {
        return supportsReversedQuote;
    }

    public TONStakingProviderMetadataOverride setSupportsReversedQuote(Boolean value) {
        this.supportsReversedQuote = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "contractAddress", contractAddress);
        TonApiJson.put(json, "name", name);
        TonApiJson.put(json, "receiveToken", receiveToken == null ? null : receiveToken.toJson());
        TonApiJson.put(json, "stakeToken", stakeToken == null ? null : stakeToken.toJson());
        if (supportedUnstakeModes != null) {
            JSONArray array = new JSONArray();
            for (TONUnstakeModes item : supportedUnstakeModes) {
                array.put(item == null ? JSONObject.NULL : item.getValue());
            }
            TonApiJson.put(json, "supportedUnstakeModes", array);
        }
        TonApiJson.put(json, "supportsReversedQuote", supportsReversedQuote);
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONStakingProviderMetadataOverride fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONStakingProviderMetadataOverride out = new TONStakingProviderMetadataOverride();
        out.contractAddress = TonApiJson.optString(json, "contractAddress");
        out.name = TonApiJson.optString(json, "name");
        out.receiveToken = TONStakingTokenInfo.fromJson(TonApiJson.optObject(json, "receiveToken"));
        out.stakeToken = TONStakingTokenInfo.fromJson(TonApiJson.optObject(json, "stakeToken"));
        out.supportedUnstakeModes = TonApiJson.enumList(TonApiJson.optArray(json, "supportedUnstakeModes"), TONUnstakeModes.VALUES);
        out.supportsReversedQuote = TonApiJson.optBoolean(json, "supportsReversedQuote");
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
