//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

public class TONSignatureDomainL2 {

    /** Builds one of these from JSON. */
    public static final Parser<TONSignatureDomainL2> PARSER = new Parser<TONSignatureDomainL2>() {
        @Override
        public TONSignatureDomainL2 parse(JSONObject json) {
            return fromJson(json);
        }
    };

    /** Values this property accepts. */
    public enum TypeEnum {

        L2("l2");

        private final String value;

        TypeEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static TypeEnum fromValue(Object wire) {
            if (wire == null) {
                return null;
            }
            String text = wire.toString();
            for (TypeEnum candidate : values()) {
                if (candidate.value.equals(text)) {
                    return candidate;
                }
            }
            return null;
        }
    }

    private Double globalId;
    private TypeEnum type;

    /** Required by the API. */
    public Double getGlobalId() {
        return globalId;
    }

    public TONSignatureDomainL2 setGlobalId(Double value) {
        this.globalId = value;
        return this;
    }

    /** Required by the API. */
    public TypeEnum getType() {
        return type;
    }

    public TONSignatureDomainL2 setType(TypeEnum value) {
        this.type = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "globalId", globalId);
        TonApiJson.put(json, "type", type == null ? null : type.getValue());
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONSignatureDomainL2 fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONSignatureDomainL2 out = new TONSignatureDomainL2();
        out.globalId = TonApiJson.optDouble(json, "globalId");
        out.type = TypeEnum.fromValue(TonApiJson.opt(json, "type"));
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
