/*
 * TON WalletKit models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ton.walletkit.api;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.ton.walletkit.api.TONStakingTokenInfo;
import org.ton.walletkit.api.TONUnstakeModes;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.ton.walletkit.api.JSON;

/**
 * Used in provider configuration to override fields of the provider&#39;s metadata.
 */
public class TONStakingProviderMetadataOverride {
  public static final String SERIALIZED_NAME_CONTRACT_ADDRESS = "contractAddress";
  @SerializedName(SERIALIZED_NAME_CONTRACT_ADDRESS)
  private String contractAddress;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_RECEIVE_TOKEN = "receiveToken";
  @SerializedName(SERIALIZED_NAME_RECEIVE_TOKEN)
  private TONStakingTokenInfo receiveToken;

  public static final String SERIALIZED_NAME_STAKE_TOKEN = "stakeToken";
  @SerializedName(SERIALIZED_NAME_STAKE_TOKEN)
  private TONStakingTokenInfo stakeToken;

  public static final String SERIALIZED_NAME_SUPPORTED_UNSTAKE_MODES = "supportedUnstakeModes";
  @SerializedName(SERIALIZED_NAME_SUPPORTED_UNSTAKE_MODES)
  private List<TONUnstakeModes> supportedUnstakeModes = new ArrayList<>();

  public static final String SERIALIZED_NAME_SUPPORTS_REVERSED_QUOTE = "supportsReversedQuote";
  @SerializedName(SERIALIZED_NAME_SUPPORTS_REVERSED_QUOTE)
  private Boolean supportsReversedQuote;

  public TONStakingProviderMetadataOverride() {
  }

  public TONStakingProviderMetadataOverride contractAddress(String contractAddress) {
    this.contractAddress = contractAddress;
    return this;
  }

  /**
   * User-friendly TON address representation (e.g., \&quot;EQDtFpEwcFAEcRe5mLVh2N6C0x-_hJEM7W61_JLnSF74p4q2\&quot;)
   * @return contractAddress
   */
  public String getContractAddress() {
    return contractAddress;
  }

  public void setContractAddress(String contractAddress) {
    this.contractAddress = contractAddress;
  }


  public TONStakingProviderMetadataOverride name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public TONStakingProviderMetadataOverride receiveToken(TONStakingTokenInfo receiveToken) {
    this.receiveToken = receiveToken;
    return this;
  }

  /**
   * Get receiveToken
   * @return receiveToken
   */
  public TONStakingTokenInfo getReceiveToken() {
    return receiveToken;
  }

  public void setReceiveToken(TONStakingTokenInfo receiveToken) {
    this.receiveToken = receiveToken;
  }


  public TONStakingProviderMetadataOverride stakeToken(TONStakingTokenInfo stakeToken) {
    this.stakeToken = stakeToken;
    return this;
  }

  /**
   * Get stakeToken
   * @return stakeToken
   */
  public TONStakingTokenInfo getStakeToken() {
    return stakeToken;
  }

  public void setStakeToken(TONStakingTokenInfo stakeToken) {
    this.stakeToken = stakeToken;
  }


  public TONStakingProviderMetadataOverride supportedUnstakeModes(List<TONUnstakeModes> supportedUnstakeModes) {
    this.supportedUnstakeModes = supportedUnstakeModes;
    return this;
  }

  public TONStakingProviderMetadataOverride addSupportedUnstakeModesItem(TONUnstakeModes supportedUnstakeModesItem) {
    if (this.supportedUnstakeModes == null) {
      this.supportedUnstakeModes = new ArrayList<>();
    }
    this.supportedUnstakeModes.add(supportedUnstakeModesItem);
    return this;
  }

  /**
   * Get supportedUnstakeModes
   * @return supportedUnstakeModes
   */
  public List<TONUnstakeModes> getSupportedUnstakeModes() {
    return supportedUnstakeModes;
  }

  public void setSupportedUnstakeModes(List<TONUnstakeModes> supportedUnstakeModes) {
    this.supportedUnstakeModes = supportedUnstakeModes;
  }


  public TONStakingProviderMetadataOverride supportsReversedQuote(Boolean supportsReversedQuote) {
    this.supportsReversedQuote = supportsReversedQuote;
    return this;
  }

  /**
   * Get supportsReversedQuote
   * @return supportsReversedQuote
   */
  public Boolean getSupportsReversedQuote() {
    return supportsReversedQuote;
  }

  public void setSupportsReversedQuote(Boolean supportsReversedQuote) {
    this.supportsReversedQuote = supportsReversedQuote;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TONStakingProviderMetadataOverride stakingProviderMetadataOverride = (TONStakingProviderMetadataOverride) o;
    return Objects.equals(this.contractAddress, stakingProviderMetadataOverride.contractAddress) &&
        Objects.equals(this.name, stakingProviderMetadataOverride.name) &&
        Objects.equals(this.receiveToken, stakingProviderMetadataOverride.receiveToken) &&
        Objects.equals(this.stakeToken, stakingProviderMetadataOverride.stakeToken) &&
        Objects.equals(this.supportedUnstakeModes, stakingProviderMetadataOverride.supportedUnstakeModes) &&
        Objects.equals(this.supportsReversedQuote, stakingProviderMetadataOverride.supportsReversedQuote);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contractAddress, name, receiveToken, stakeToken, supportedUnstakeModes, supportsReversedQuote);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TONStakingProviderMetadataOverride {\n");
    sb.append("    contractAddress: ").append(toIndentedString(contractAddress)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    receiveToken: ").append(toIndentedString(receiveToken)).append("\n");
    sb.append("    stakeToken: ").append(toIndentedString(stakeToken)).append("\n");
    sb.append("    supportedUnstakeModes: ").append(toIndentedString(supportedUnstakeModes)).append("\n");
    sb.append("    supportsReversedQuote: ").append(toIndentedString(supportsReversedQuote)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("contractAddress");
    openapiFields.add("name");
    openapiFields.add("receiveToken");
    openapiFields.add("stakeToken");
    openapiFields.add("supportedUnstakeModes");
    openapiFields.add("supportsReversedQuote");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TONStakingProviderMetadataOverride
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TONStakingProviderMetadataOverride.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TONStakingProviderMetadataOverride is not found in the empty JSON string", TONStakingProviderMetadataOverride.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TONStakingProviderMetadataOverride.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TONStakingProviderMetadataOverride` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("contractAddress") != null && !jsonObj.get("contractAddress").isJsonNull()) && !jsonObj.get("contractAddress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `contractAddress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contractAddress").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // validate the optional field `receiveToken`
      if (jsonObj.get("receiveToken") != null && !jsonObj.get("receiveToken").isJsonNull()) {
        TONStakingTokenInfo.validateJsonElement(jsonObj.get("receiveToken"));
      }
      // validate the optional field `stakeToken`
      if (jsonObj.get("stakeToken") != null && !jsonObj.get("stakeToken").isJsonNull()) {
        TONStakingTokenInfo.validateJsonElement(jsonObj.get("stakeToken"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("supportedUnstakeModes") != null && !jsonObj.get("supportedUnstakeModes").isJsonNull() && !jsonObj.get("supportedUnstakeModes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `supportedUnstakeModes` to be an array in the JSON string but got `%s`", jsonObj.get("supportedUnstakeModes").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TONStakingProviderMetadataOverride.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TONStakingProviderMetadataOverride' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TONStakingProviderMetadataOverride> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TONStakingProviderMetadataOverride.class));

       return (TypeAdapter<T>) new TypeAdapter<TONStakingProviderMetadataOverride>() {
           @Override
           public void write(JsonWriter out, TONStakingProviderMetadataOverride value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TONStakingProviderMetadataOverride read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TONStakingProviderMetadataOverride given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TONStakingProviderMetadataOverride
   * @throws IOException if the JSON string is invalid with respect to TONStakingProviderMetadataOverride
   */
  public static TONStakingProviderMetadataOverride fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TONStakingProviderMetadataOverride.class);
  }

  /**
   * Convert an instance of TONStakingProviderMetadataOverride to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

