/*
 * TON WalletKit models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ton.walletkit.api;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.ton.walletkit.api.TONNetwork;
import org.ton.walletkit.api.TONStakingQuoteDirection;
import org.ton.walletkit.api.TONUnstakeModes;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.ton.walletkit.api.JSON;

/**
 * Parameters for getting a staking quote
 */
public class TONStakingQuoteParams {
  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private String amount;

  public static final String SERIALIZED_NAME_DIRECTION = "direction";
  @SerializedName(SERIALIZED_NAME_DIRECTION)
  private TONStakingQuoteDirection direction;

  public static final String SERIALIZED_NAME_IS_REVERSED = "isReversed";
  @SerializedName(SERIALIZED_NAME_IS_REVERSED)
  private Boolean isReversed;

  public static final String SERIALIZED_NAME_NETWORK = "network";
  @SerializedName(SERIALIZED_NAME_NETWORK)
  private TONNetwork network;

  public static final String SERIALIZED_NAME_PROVIDER_OPTIONS = "providerOptions";
  @SerializedName(SERIALIZED_NAME_PROVIDER_OPTIONS)
  private Object providerOptions = null;

  public static final String SERIALIZED_NAME_UNSTAKE_MODE = "unstakeMode";
  @SerializedName(SERIALIZED_NAME_UNSTAKE_MODE)
  private TONUnstakeModes unstakeMode;

  public static final String SERIALIZED_NAME_USER_ADDRESS = "userAddress";
  @SerializedName(SERIALIZED_NAME_USER_ADDRESS)
  private String userAddress;

  public TONStakingQuoteParams() {
  }

  public TONStakingQuoteParams amount(String amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Amount of tokens to stake or unstake
   * @return amount
   */
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }


  public TONStakingQuoteParams direction(TONStakingQuoteDirection direction) {
    this.direction = direction;
    return this;
  }

  /**
   * Get direction
   * @return direction
   */
  public TONStakingQuoteDirection getDirection() {
    return direction;
  }

  public void setDirection(TONStakingQuoteDirection direction) {
    this.direction = direction;
  }


  public TONStakingQuoteParams isReversed(Boolean isReversed) {
    this.isReversed = isReversed;
    return this;
  }

  /**
   * If true, for unstake requests the amount is specified in the staking coin (e.g. TON) instead of the Liquid Staking Token (e.g. tsTON).
   * @return isReversed
   */
  public Boolean getIsReversed() {
    return isReversed;
  }

  public void setIsReversed(Boolean isReversed) {
    this.isReversed = isReversed;
  }


  public TONStakingQuoteParams network(TONNetwork network) {
    this.network = network;
    return this;
  }

  /**
   * Get network
   * @return network
   */
  public TONNetwork getNetwork() {
    return network;
  }

  public void setNetwork(TONNetwork network) {
    this.network = network;
  }


  public TONStakingQuoteParams providerOptions(Object providerOptions) {
    this.providerOptions = providerOptions;
    return this;
  }

  /**
   * Provider-specific options
   * @return providerOptions
   */
  public Object getProviderOptions() {
    return providerOptions;
  }

  public void setProviderOptions(Object providerOptions) {
    this.providerOptions = providerOptions;
  }


  public TONStakingQuoteParams unstakeMode(TONUnstakeModes unstakeMode) {
    this.unstakeMode = unstakeMode;
    return this;
  }

  /**
   * Get unstakeMode
   * @return unstakeMode
   */
  public TONUnstakeModes getUnstakeMode() {
    return unstakeMode;
  }

  public void setUnstakeMode(TONUnstakeModes unstakeMode) {
    this.unstakeMode = unstakeMode;
  }


  public TONStakingQuoteParams userAddress(String userAddress) {
    this.userAddress = userAddress;
    return this;
  }

  /**
   * User-friendly TON address representation (e.g., \&quot;EQDtFpEwcFAEcRe5mLVh2N6C0x-_hJEM7W61_JLnSF74p4q2\&quot;)
   * @return userAddress
   */
  public String getUserAddress() {
    return userAddress;
  }

  public void setUserAddress(String userAddress) {
    this.userAddress = userAddress;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TONStakingQuoteParams stakingQuoteParams = (TONStakingQuoteParams) o;
    return Objects.equals(this.amount, stakingQuoteParams.amount) &&
        Objects.equals(this.direction, stakingQuoteParams.direction) &&
        Objects.equals(this.isReversed, stakingQuoteParams.isReversed) &&
        Objects.equals(this.network, stakingQuoteParams.network) &&
        Objects.equals(this.providerOptions, stakingQuoteParams.providerOptions) &&
        Objects.equals(this.unstakeMode, stakingQuoteParams.unstakeMode) &&
        Objects.equals(this.userAddress, stakingQuoteParams.userAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, direction, isReversed, network, providerOptions, unstakeMode, userAddress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TONStakingQuoteParams {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    isReversed: ").append(toIndentedString(isReversed)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    providerOptions: ").append(toIndentedString(providerOptions)).append("\n");
    sb.append("    unstakeMode: ").append(toIndentedString(unstakeMode)).append("\n");
    sb.append("    userAddress: ").append(toIndentedString(userAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("amount");
    openapiFields.add("direction");
    openapiFields.add("isReversed");
    openapiFields.add("network");
    openapiFields.add("providerOptions");
    openapiFields.add("unstakeMode");
    openapiFields.add("userAddress");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("amount");
    openapiRequiredFields.add("direction");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TONStakingQuoteParams
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TONStakingQuoteParams.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TONStakingQuoteParams is not found in the empty JSON string", TONStakingQuoteParams.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TONStakingQuoteParams.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TONStakingQuoteParams` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TONStakingQuoteParams.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("amount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("amount").toString()));
      }
      // validate the required field `direction`
      TONStakingQuoteDirection.validateJsonElement(jsonObj.get("direction"));
      // validate the optional field `network`
      if (jsonObj.get("network") != null && !jsonObj.get("network").isJsonNull()) {
        TONNetwork.validateJsonElement(jsonObj.get("network"));
      }
      // validate the optional field `unstakeMode`
      if (jsonObj.get("unstakeMode") != null && !jsonObj.get("unstakeMode").isJsonNull()) {
        TONUnstakeModes.validateJsonElement(jsonObj.get("unstakeMode"));
      }
      if ((jsonObj.get("userAddress") != null && !jsonObj.get("userAddress").isJsonNull()) && !jsonObj.get("userAddress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `userAddress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("userAddress").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TONStakingQuoteParams.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TONStakingQuoteParams' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TONStakingQuoteParams> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TONStakingQuoteParams.class));

       return (TypeAdapter<T>) new TypeAdapter<TONStakingQuoteParams>() {
           @Override
           public void write(JsonWriter out, TONStakingQuoteParams value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TONStakingQuoteParams read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TONStakingQuoteParams given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TONStakingQuoteParams
   * @throws IOException if the JSON string is invalid with respect to TONStakingQuoteParams
   */
  public static TONStakingQuoteParams fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TONStakingQuoteParams.class);
  }

  /**
   * Convert an instance of TONStakingQuoteParams to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

