//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

/** TON Cell data to be signed with a schema definition. */
public class TONSignDataCell {

    /** Builds one of these from JSON. */
    public static final Parser<TONSignDataCell> PARSER = new Parser<TONSignDataCell>() {
        @Override
        public TONSignDataCell parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private String content;
    private String schema;

    /**
     * Cell content encoded in Base64
     * Required by the API.
     */
    public String getContent() {
        return content;
    }

    public TONSignDataCell setContent(String value) {
        this.content = value;
        return this;
    }

    /**
     * Schema describing the cell structure for parsing
     * Required by the API.
     */
    public String getSchema() {
        return schema;
    }

    public TONSignDataCell setSchema(String value) {
        this.schema = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "content", content);
        TonApiJson.put(json, "schema", schema);
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONSignDataCell fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONSignDataCell out = new TONSignDataCell();
        out.content = TonApiJson.optString(json, "content");
        out.schema = TonApiJson.optString(json, "schema");
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
