/*
 * TON WalletKit models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ton.walletkit.api;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Represents the status of a streaming notification.
 */
@JsonAdapter(TONStreamingUpdateStatus.Adapter.class)
public enum TONStreamingUpdateStatus {
  
  PENDING("pending"),
  
  CONFIRMED("confirmed"),
  
  FINALIZED("finalized"),
  
  INVALIDATED("invalidated");

  private String value;

  TONStreamingUpdateStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TONStreamingUpdateStatus fromValue(String value) {
    for (TONStreamingUpdateStatus b : TONStreamingUpdateStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<TONStreamingUpdateStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final TONStreamingUpdateStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TONStreamingUpdateStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TONStreamingUpdateStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    TONStreamingUpdateStatus.fromValue(value);
  }
}

