//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

/** Token type for swap */
public class TONSwapToken {

    /** Builds one of these from JSON. */
    public static final Parser<TONSwapToken> PARSER = new Parser<TONSwapToken>() {
        @Override
        public TONSwapToken parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private String address;
    private String chainId;
    private Double decimals;
    private String image;
    private String name;
    private String symbol;

    /** Required by the API. */
    public String getAddress() {
        return address;
    }

    public TONSwapToken setAddress(String value) {
        this.address = value;
        return this;
    }

    public String getChainId() {
        return chainId;
    }

    public TONSwapToken setChainId(String value) {
        this.chainId = value;
        return this;
    }

    /** Required by the API. */
    public Double getDecimals() {
        return decimals;
    }

    public TONSwapToken setDecimals(Double value) {
        this.decimals = value;
        return this;
    }

    public String getImage() {
        return image;
    }

    public TONSwapToken setImage(String value) {
        this.image = value;
        return this;
    }

    public String getName() {
        return name;
    }

    public TONSwapToken setName(String value) {
        this.name = value;
        return this;
    }

    public String getSymbol() {
        return symbol;
    }

    public TONSwapToken setSymbol(String value) {
        this.symbol = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "address", address);
        TonApiJson.put(json, "chainId", chainId);
        TonApiJson.put(json, "decimals", decimals);
        TonApiJson.put(json, "image", image);
        TonApiJson.put(json, "name", name);
        TonApiJson.put(json, "symbol", symbol);
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONSwapToken fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONSwapToken out = new TONSwapToken();
        out.address = TonApiJson.optString(json, "address");
        out.chainId = TonApiJson.optString(json, "chainId");
        out.decimals = TonApiJson.optDouble(json, "decimals");
        out.image = TonApiJson.optString(json, "image");
        out.name = TonApiJson.optString(json, "name");
        out.symbol = TonApiJson.optString(json, "symbol");
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
