/*
 * TON WalletKit models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ton.walletkit.api;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.ton.walletkit.api.TONDAppInfo;
import org.ton.walletkit.api.TONSignDataPreview;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.ton.walletkit.api.JSON;

/**
 * Preview data for displaying sign data request in the wallet UI.
 */
public class TONSignDataRequestEventPreview {
  public static final String SERIALIZED_NAME_D_APP_INFO = "dAppInfo";
  @SerializedName(SERIALIZED_NAME_D_APP_INFO)
  private TONDAppInfo dAppInfo;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private TONSignDataPreview data;

  public TONSignDataRequestEventPreview() {
  }

  public TONSignDataRequestEventPreview dAppInfo(TONDAppInfo dAppInfo) {
    this.dAppInfo = dAppInfo;
    return this;
  }

  /**
   * Get dAppInfo
   * @return dAppInfo
   */
  public TONDAppInfo getdAppInfo() {
    return dAppInfo;
  }

  public void setdAppInfo(TONDAppInfo dAppInfo) {
    this.dAppInfo = dAppInfo;
  }


  public TONSignDataRequestEventPreview data(TONSignDataPreview data) {
    this.data = data;
    return this;
  }

  /**
   * Get data
   * @return data
   */
  public TONSignDataPreview getData() {
    return data;
  }

  public void setData(TONSignDataPreview data) {
    this.data = data;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TONSignDataRequestEventPreview signDataRequestEventPreview = (TONSignDataRequestEventPreview) o;
    return Objects.equals(this.dAppInfo, signDataRequestEventPreview.dAppInfo) &&
        Objects.equals(this.data, signDataRequestEventPreview.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dAppInfo, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TONSignDataRequestEventPreview {\n");
    sb.append("    dAppInfo: ").append(toIndentedString(dAppInfo)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("dAppInfo");
    openapiFields.add("data");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("data");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TONSignDataRequestEventPreview
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TONSignDataRequestEventPreview.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TONSignDataRequestEventPreview is not found in the empty JSON string", TONSignDataRequestEventPreview.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TONSignDataRequestEventPreview.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TONSignDataRequestEventPreview` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TONSignDataRequestEventPreview.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `dAppInfo`
      if (jsonObj.get("dAppInfo") != null && !jsonObj.get("dAppInfo").isJsonNull()) {
        TONDAppInfo.validateJsonElement(jsonObj.get("dAppInfo"));
      }
      // validate the required field `data`
      TONSignDataPreview.validateJsonElement(jsonObj.get("data"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TONSignDataRequestEventPreview.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TONSignDataRequestEventPreview' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TONSignDataRequestEventPreview> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TONSignDataRequestEventPreview.class));

       return (TypeAdapter<T>) new TypeAdapter<TONSignDataRequestEventPreview>() {
           @Override
           public void write(JsonWriter out, TONSignDataRequestEventPreview value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TONSignDataRequestEventPreview read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TONSignDataRequestEventPreview given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TONSignDataRequestEventPreview
   * @throws IOException if the JSON string is invalid with respect to TONSignDataRequestEventPreview
   */
  public static TONSignDataRequestEventPreview fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TONSignDataRequestEventPreview.class);
  }

  /**
   * Convert an instance of TONSignDataRequestEventPreview to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

