//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

/** Parameters for building swap transaction */
public class TONSwapParams {

    /** Builds one of these from JSON. */
    public static final Parser<TONSwapParams> PARSER = new Parser<TONSwapParams>() {
        @Override
        public TONSwapParams parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private Double deadline;
    private String destinationAddress;
    private Object providerOptions;
    private TONSwapQuote quote;
    private Double slippageBps;
    private String userAddress;

    /** Transaction deadline in unix timestamp */
    public Double getDeadline() {
        return deadline;
    }

    public TONSwapParams setDeadline(Double value) {
        this.deadline = value;
        return this;
    }

    /** Address to receive the swapped tokens (defaults to userAddress) */
    public String getDestinationAddress() {
        return destinationAddress;
    }

    public TONSwapParams setDestinationAddress(String value) {
        this.destinationAddress = value;
        return this;
    }

    /** Provider-specific options */
    public Object getProviderOptions() {
        return providerOptions;
    }

    public TONSwapParams setProviderOptions(Object value) {
        this.providerOptions = value;
        return this;
    }

    /**
     * The swap quote based on which the transaction is built
     * Required by the API.
     */
    public TONSwapQuote getQuote() {
        return quote;
    }

    public TONSwapParams setQuote(TONSwapQuote value) {
        this.quote = value;
        return this;
    }

    /** Slippage tolerance in basis points (1 bp = 0.01%) */
    public Double getSlippageBps() {
        return slippageBps;
    }

    public TONSwapParams setSlippageBps(Double value) {
        this.slippageBps = value;
        return this;
    }

    /**
     * Address of the user performing the swap
     * Required by the API.
     */
    public String getUserAddress() {
        return userAddress;
    }

    public TONSwapParams setUserAddress(String value) {
        this.userAddress = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "deadline", deadline);
        TonApiJson.put(json, "destinationAddress", destinationAddress);
        TonApiJson.put(json, "providerOptions", providerOptions);
        TonApiJson.put(json, "quote", quote == null ? null : quote.toJson());
        TonApiJson.put(json, "slippageBps", slippageBps);
        TonApiJson.put(json, "userAddress", userAddress);
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONSwapParams fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONSwapParams out = new TONSwapParams();
        out.deadline = TonApiJson.optDouble(json, "deadline");
        out.destinationAddress = TonApiJson.optString(json, "destinationAddress");
        out.providerOptions = TonApiJson.opt(json, "providerOptions");
        out.quote = TONSwapQuote.fromJson(TonApiJson.optObject(json, "quote"));
        out.slippageBps = TonApiJson.optDouble(json, "slippageBps");
        out.userAddress = TonApiJson.optString(json, "userAddress");
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
