/*
 * TON WalletKit models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ton.walletkit.api;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.ton.walletkit.api.TONSignDataAnyOf;
import org.ton.walletkit.api.TONSignDataAnyOf1;
import org.ton.walletkit.api.TONSignDataAnyOf2;
import org.ton.walletkit.api.TONSignDataCell;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import org.ton.walletkit.api.JSON;

public class TONSignData extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(TONSignData.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!TONSignData.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'TONSignData' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<TONSignDataAnyOf> adapterTONSignDataAnyOf = gson.getDelegateAdapter(this, TypeToken.get(TONSignDataAnyOf.class));
            final TypeAdapter<TONSignDataAnyOf1> adapterTONSignDataAnyOf1 = gson.getDelegateAdapter(this, TypeToken.get(TONSignDataAnyOf1.class));
            final TypeAdapter<TONSignDataAnyOf2> adapterTONSignDataAnyOf2 = gson.getDelegateAdapter(this, TypeToken.get(TONSignDataAnyOf2.class));

            return (TypeAdapter<T>) new TypeAdapter<TONSignData>() {
                @Override
                public void write(JsonWriter out, TONSignData value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `TONSignDataAnyOf`
                    if (value.getActualInstance() instanceof TONSignDataAnyOf) {
                        JsonElement element = adapterTONSignDataAnyOf.toJsonTree((TONSignDataAnyOf)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `TONSignDataAnyOf1`
                    if (value.getActualInstance() instanceof TONSignDataAnyOf1) {
                        JsonElement element = adapterTONSignDataAnyOf1.toJsonTree((TONSignDataAnyOf1)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `TONSignDataAnyOf2`
                    if (value.getActualInstance() instanceof TONSignDataAnyOf2) {
                        JsonElement element = adapterTONSignDataAnyOf2.toJsonTree((TONSignDataAnyOf2)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match anyOf schemas: TONSignDataAnyOf, TONSignDataAnyOf1, TONSignDataAnyOf2");
                }

                @Override
                public TONSignData read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize TONSignDataAnyOf
                    try {
                        // validate the JSON object to see if any exception is thrown
                        TONSignDataAnyOf.validateJsonElement(jsonElement);
                        actualAdapter = adapterTONSignDataAnyOf;
                        TONSignData ret = new TONSignData();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for TONSignDataAnyOf failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'TONSignDataAnyOf'", e);
                    }
                    // deserialize TONSignDataAnyOf1
                    try {
                        // validate the JSON object to see if any exception is thrown
                        TONSignDataAnyOf1.validateJsonElement(jsonElement);
                        actualAdapter = adapterTONSignDataAnyOf1;
                        TONSignData ret = new TONSignData();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for TONSignDataAnyOf1 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'TONSignDataAnyOf1'", e);
                    }
                    // deserialize TONSignDataAnyOf2
                    try {
                        // validate the JSON object to see if any exception is thrown
                        TONSignDataAnyOf2.validateJsonElement(jsonElement);
                        actualAdapter = adapterTONSignDataAnyOf2;
                        TONSignData ret = new TONSignData();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for TONSignDataAnyOf2 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'TONSignDataAnyOf2'", e);
                    }

                    throw new IOException(String.format("Failed deserialization for TONSignData: no class matches result, expected at least 1. Detailed failure message for anyOf schemas: %s. JSON: %s", errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public TONSignData() {
        super("anyOf", Boolean.FALSE);
    }

    public TONSignData(Object o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("TONSignDataAnyOf", TONSignDataAnyOf.class);
        schemas.put("TONSignDataAnyOf1", TONSignDataAnyOf1.class);
        schemas.put("TONSignDataAnyOf2", TONSignDataAnyOf2.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return TONSignData.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * TONSignDataAnyOf, TONSignDataAnyOf1, TONSignDataAnyOf2
     *
     * It could be an instance of the 'anyOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof TONSignDataAnyOf) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof TONSignDataAnyOf1) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof TONSignDataAnyOf2) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be TONSignDataAnyOf, TONSignDataAnyOf1, TONSignDataAnyOf2");
    }

    /**
     * Get the actual instance, which can be the following:
     * TONSignDataAnyOf, TONSignDataAnyOf1, TONSignDataAnyOf2
     *
     * @return The actual instance (TONSignDataAnyOf, TONSignDataAnyOf1, TONSignDataAnyOf2)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `TONSignDataAnyOf`. If the actual instance is not `TONSignDataAnyOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TONSignDataAnyOf`
     * @throws ClassCastException if the instance is not `TONSignDataAnyOf`
     */
    public TONSignDataAnyOf getTONSignDataAnyOf() throws ClassCastException {
        return (TONSignDataAnyOf)super.getActualInstance();
    }
    /**
     * Get the actual instance of `TONSignDataAnyOf1`. If the actual instance is not `TONSignDataAnyOf1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TONSignDataAnyOf1`
     * @throws ClassCastException if the instance is not `TONSignDataAnyOf1`
     */
    public TONSignDataAnyOf1 getTONSignDataAnyOf1() throws ClassCastException {
        return (TONSignDataAnyOf1)super.getActualInstance();
    }
    /**
     * Get the actual instance of `TONSignDataAnyOf2`. If the actual instance is not `TONSignDataAnyOf2`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TONSignDataAnyOf2`
     * @throws ClassCastException if the instance is not `TONSignDataAnyOf2`
     */
    public TONSignDataAnyOf2 getTONSignDataAnyOf2() throws ClassCastException {
        return (TONSignDataAnyOf2)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to TONSignData
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate anyOf schemas one by one
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with TONSignDataAnyOf
        try {
            TONSignDataAnyOf.validateJsonElement(jsonElement);
            return;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for TONSignDataAnyOf failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with TONSignDataAnyOf1
        try {
            TONSignDataAnyOf1.validateJsonElement(jsonElement);
            return;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for TONSignDataAnyOf1 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with TONSignDataAnyOf2
        try {
            TONSignDataAnyOf2.validateJsonElement(jsonElement);
            return;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for TONSignDataAnyOf2 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        throw new IOException(String.format("The JSON string is invalid for TONSignData with anyOf schemas: TONSignDataAnyOf, TONSignDataAnyOf1, TONSignDataAnyOf2. no class match the result, expected at least 1. Detailed failure message for anyOf schemas: %s. JSON: %s", errorMessages, jsonElement.toString()));
    }

    /**
     * Create an instance of TONSignData given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of TONSignData
     * @throws IOException if the JSON string is invalid with respect to TONSignData
     */
    public static TONSignData fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, TONSignData.class);
    }

    /**
     * Convert an instance of TONSignData to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

