//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

/** Compute phase of transaction execution (TVM execution). */
public class TONTransactionComputePhase {

    /** Builds one of these from JSON. */
    public static final Parser<TONTransactionComputePhase> PARSER = new Parser<TONTransactionComputePhase>() {
        @Override
        public TONTransactionComputePhase parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private Double exitCode;
    private String gasCredit;
    private String gasFees;
    private String gasLimit;
    private String gasUsed;
    private Boolean isAccountActivated;
    private Boolean isMessageStateUsed;
    private Boolean isSkipped;
    private Boolean isSuccess;
    private Double mode;
    private Double vmStepsNumber;

    /** The exit code returned from the VM */
    public Double getExitCode() {
        return exitCode;
    }

    public TONTransactionComputePhase setExitCode(Double value) {
        this.exitCode = value;
        return this;
    }

    /** The gas credit for the compute phase */
    public String getGasCredit() {
        return gasCredit;
    }

    public TONTransactionComputePhase setGasCredit(String value) {
        this.gasCredit = value;
        return this;
    }

    /** The gas fees charged for compute */
    public String getGasFees() {
        return gasFees;
    }

    public TONTransactionComputePhase setGasFees(String value) {
        this.gasFees = value;
        return this;
    }

    /** The gas limit for the compute phase */
    public String getGasLimit() {
        return gasLimit;
    }

    public TONTransactionComputePhase setGasLimit(String value) {
        this.gasLimit = value;
        return this;
    }

    /** The total gas used in the compute phase */
    public String getGasUsed() {
        return gasUsed;
    }

    public TONTransactionComputePhase setGasUsed(String value) {
        this.gasUsed = value;
        return this;
    }

    /** The flag indicating if the account was activated during compute */
    public Boolean getIsAccountActivated() {
        return isAccountActivated;
    }

    public TONTransactionComputePhase setIsAccountActivated(Boolean value) {
        this.isAccountActivated = value;
        return this;
    }

    /** The flag indicating if message state was used */
    public Boolean getIsMessageStateUsed() {
        return isMessageStateUsed;
    }

    public TONTransactionComputePhase setIsMessageStateUsed(Boolean value) {
        this.isMessageStateUsed = value;
        return this;
    }

    /** The flag indicating if the compute phase was skipped */
    public Boolean getIsSkipped() {
        return isSkipped;
    }

    public TONTransactionComputePhase setIsSkipped(Boolean value) {
        this.isSkipped = value;
        return this;
    }

    /** The success state of the compute phase */
    public Boolean getIsSuccess() {
        return isSuccess;
    }

    public TONTransactionComputePhase setIsSuccess(Boolean value) {
        this.isSuccess = value;
        return this;
    }

    /** The compute execution mode */
    public Double getMode() {
        return mode;
    }

    public TONTransactionComputePhase setMode(Double value) {
        this.mode = value;
        return this;
    }

    /** The number of steps executed by the VM */
    public Double getVmStepsNumber() {
        return vmStepsNumber;
    }

    public TONTransactionComputePhase setVmStepsNumber(Double value) {
        this.vmStepsNumber = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "exitCode", exitCode);
        TonApiJson.put(json, "gasCredit", gasCredit);
        TonApiJson.put(json, "gasFees", gasFees);
        TonApiJson.put(json, "gasLimit", gasLimit);
        TonApiJson.put(json, "gasUsed", gasUsed);
        TonApiJson.put(json, "isAccountActivated", isAccountActivated);
        TonApiJson.put(json, "isMessageStateUsed", isMessageStateUsed);
        TonApiJson.put(json, "isSkipped", isSkipped);
        TonApiJson.put(json, "isSuccess", isSuccess);
        TonApiJson.put(json, "mode", mode);
        TonApiJson.put(json, "vmStepsNumber", vmStepsNumber);
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONTransactionComputePhase fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONTransactionComputePhase out = new TONTransactionComputePhase();
        out.exitCode = TonApiJson.optDouble(json, "exitCode");
        out.gasCredit = TonApiJson.optString(json, "gasCredit");
        out.gasFees = TonApiJson.optString(json, "gasFees");
        out.gasLimit = TonApiJson.optString(json, "gasLimit");
        out.gasUsed = TonApiJson.optString(json, "gasUsed");
        out.isAccountActivated = TonApiJson.optBoolean(json, "isAccountActivated");
        out.isMessageStateUsed = TonApiJson.optBoolean(json, "isMessageStateUsed");
        out.isSkipped = TonApiJson.optBoolean(json, "isSkipped");
        out.isSuccess = TonApiJson.optBoolean(json, "isSuccess");
        out.mode = TonApiJson.optDouble(json, "mode");
        out.vmStepsNumber = TonApiJson.optDouble(json, "vmStepsNumber");
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
