//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

public class TONTransactionStatusResponse {

    /** Builds one of these from JSON. */
    public static final Parser<TONTransactionStatusResponse> PARSER = new Parser<TONTransactionStatusResponse>() {
        @Override
        public TONTransactionStatusResponse parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private Double onchainMessages;
    private Double pendingMessages;
    private TONTransactionStatus status;
    private Double totalMessages;

    /**
     * Number of onchain messages (totalMessages - pendingMessages)
     * Required by the API.
     */
    public Double getOnchainMessages() {
        return onchainMessages;
    }

    public TONTransactionStatusResponse setOnchainMessages(Double value) {
        this.onchainMessages = value;
        return this;
    }

    /**
     * Messages still pending
     * Required by the API.
     */
    public Double getPendingMessages() {
        return pendingMessages;
    }

    public TONTransactionStatusResponse setPendingMessages(Double value) {
        this.pendingMessages = value;
        return this;
    }

    /**
     * Overall status of the transaction trace
     * Required by the API.
     */
    public TONTransactionStatus getStatus() {
        return status;
    }

    public TONTransactionStatusResponse setStatus(TONTransactionStatus value) {
        this.status = value;
        return this;
    }

    /**
     * Total messages in the trace
     * Required by the API.
     */
    public Double getTotalMessages() {
        return totalMessages;
    }

    public TONTransactionStatusResponse setTotalMessages(Double value) {
        this.totalMessages = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "onchainMessages", onchainMessages);
        TonApiJson.put(json, "pendingMessages", pendingMessages);
        TonApiJson.put(json, "status", status == null ? null : status.getValue());
        TonApiJson.put(json, "totalMessages", totalMessages);
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONTransactionStatusResponse fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONTransactionStatusResponse out = new TONTransactionStatusResponse();
        out.onchainMessages = TonApiJson.optDouble(json, "onchainMessages");
        out.pendingMessages = TonApiJson.optDouble(json, "pendingMessages");
        out.status = TONTransactionStatus.fromValue(TonApiJson.opt(json, "status"));
        out.totalMessages = TonApiJson.optDouble(json, "totalMessages");
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
