//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import java.util.Map;

import org.json.JSONObject;

/** Base token information shared by all token types. */
public class TONTransactionTokenInfoBase {

    /** Builds one of these from JSON. */
    public static final Parser<TONTransactionTokenInfoBase> PARSER = new Parser<TONTransactionTokenInfoBase>() {
        @Override
        public TONTransactionTokenInfoBase parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private Map<String, Object> extra;
    private Boolean isValid;
    private String type;

    /**
     * Additional metadata for the token, such as image sizes, decimal precision, external links, and marketplaces
     * Required by the API.
     */
    public Map<String, Object> getExtra() {
        return extra;
    }

    public TONTransactionTokenInfoBase setExtra(Map<String, Object> value) {
        this.extra = value;
        return this;
    }

    /**
     * Indicates if the token contract is valid
     * Required by the API.
     */
    public Boolean getIsValid() {
        return isValid;
    }

    public TONTransactionTokenInfoBase setIsValid(Boolean value) {
        this.isValid = value;
        return this;
    }

    /**
     * Type of token
     * Required by the API.
     */
    public String getType() {
        return type;
    }

    public TONTransactionTokenInfoBase setType(String value) {
        this.type = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "extra", TonApiJson.object(extra));
        TonApiJson.put(json, "isValid", isValid);
        TonApiJson.put(json, "type", type);
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONTransactionTokenInfoBase fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONTransactionTokenInfoBase out = new TONTransactionTokenInfoBase();
        out.extra = TonApiJson.anyMap(TonApiJson.optObject(json, "extra"));
        out.isValid = TonApiJson.optBoolean(json, "isValid");
        out.type = TonApiJson.optString(json, "type");
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
