/*
 * TON WalletKit models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ton.walletkit.api;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.ton.walletkit.api.TONAddressBookEntry;
import org.ton.walletkit.api.TONTransaction;
import org.ton.walletkit.api.TONTransactionAddressMetadataEntry;
import org.ton.walletkit.api.TONTransactionTraceAction;
import org.ton.walletkit.api.TONTransactionTraceNode;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.ton.walletkit.api.JSON;

/**
 * Extended transaction trace with emulation-specific data including code/data cells and address metadata.
 */
public class TONTransactionEmulatedTrace {
  public static final String SERIALIZED_NAME_ACTIONS = "actions";
  @SerializedName(SERIALIZED_NAME_ACTIONS)
  private List<TONTransactionTraceAction> actions = new ArrayList<>();

  public static final String SERIALIZED_NAME_ADDRESS_BOOK = "addressBook";
  @SerializedName(SERIALIZED_NAME_ADDRESS_BOOK)
  private Map<String, TONAddressBookEntry> addressBook = new HashMap<>();

  public static final String SERIALIZED_NAME_CODE_CELLS = "codeCells";
  @SerializedName(SERIALIZED_NAME_CODE_CELLS)
  private Map<String, String> codeCells = new HashMap<>();

  public static final String SERIALIZED_NAME_DATA_CELLS = "dataCells";
  @SerializedName(SERIALIZED_NAME_DATA_CELLS)
  private Map<String, String> dataCells = new HashMap<>();

  public static final String SERIALIZED_NAME_IS_INCOMPLETE = "isIncomplete";
  @SerializedName(SERIALIZED_NAME_IS_INCOMPLETE)
  private Boolean isIncomplete;

  public static final String SERIALIZED_NAME_MC_BLOCK_SEQNO = "mcBlockSeqno";
  @SerializedName(SERIALIZED_NAME_MC_BLOCK_SEQNO)
  private BigDecimal mcBlockSeqno;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Map<String, TONTransactionAddressMetadataEntry> metadata = new HashMap<>();

  public static final String SERIALIZED_NAME_TRACE = "trace";
  @SerializedName(SERIALIZED_NAME_TRACE)
  private TONTransactionTraceNode trace;

  public static final String SERIALIZED_NAME_TRANSACTIONS = "transactions";
  @SerializedName(SERIALIZED_NAME_TRANSACTIONS)
  private Map<String, TONTransaction> transactions = new HashMap<>();

  public TONTransactionEmulatedTrace() {
  }

  public TONTransactionEmulatedTrace actions(List<TONTransactionTraceAction> actions) {
    this.actions = actions;
    return this;
  }

  public TONTransactionEmulatedTrace addActionsItem(TONTransactionTraceAction actionsItem) {
    if (this.actions == null) {
      this.actions = new ArrayList<>();
    }
    this.actions.add(actionsItem);
    return this;
  }

  /**
   * List of high-level actions extracted from the trace
   * @return actions
   */
  public List<TONTransactionTraceAction> getActions() {
    return actions;
  }

  public void setActions(List<TONTransactionTraceAction> actions) {
    this.actions = actions;
  }


  public TONTransactionEmulatedTrace addressBook(Map<String, TONAddressBookEntry> addressBook) {
    this.addressBook = addressBook;
    return this;
  }

  public TONTransactionEmulatedTrace putAddressBookItem(String key, TONAddressBookEntry addressBookItem) {
    if (this.addressBook == null) {
      this.addressBook = new HashMap<>();
    }
    this.addressBook.put(key, addressBookItem);
    return this;
  }

  /**
   * Map of raw addresses to their metadata entries.
   * @return addressBook
   */
  public Map<String, TONAddressBookEntry> getAddressBook() {
    return addressBook;
  }

  public void setAddressBook(Map<String, TONAddressBookEntry> addressBook) {
    this.addressBook = addressBook;
  }


  public TONTransactionEmulatedTrace codeCells(Map<String, String> codeCells) {
    this.codeCells = codeCells;
    return this;
  }

  public TONTransactionEmulatedTrace putCodeCellsItem(String key, String codeCellsItem) {
    if (this.codeCells == null) {
      this.codeCells = new HashMap<>();
    }
    this.codeCells.put(key, codeCellsItem);
    return this;
  }

  /**
   * Map of code cell hashes to their Base64-encoded content
   * @return codeCells
   */
  public Map<String, String> getCodeCells() {
    return codeCells;
  }

  public void setCodeCells(Map<String, String> codeCells) {
    this.codeCells = codeCells;
  }


  public TONTransactionEmulatedTrace dataCells(Map<String, String> dataCells) {
    this.dataCells = dataCells;
    return this;
  }

  public TONTransactionEmulatedTrace putDataCellsItem(String key, String dataCellsItem) {
    if (this.dataCells == null) {
      this.dataCells = new HashMap<>();
    }
    this.dataCells.put(key, dataCellsItem);
    return this;
  }

  /**
   * Map of data cell hashes to their Base64-encoded content
   * @return dataCells
   */
  public Map<String, String> getDataCells() {
    return dataCells;
  }

  public void setDataCells(Map<String, String> dataCells) {
    this.dataCells = dataCells;
  }


  public TONTransactionEmulatedTrace isIncomplete(Boolean isIncomplete) {
    this.isIncomplete = isIncomplete;
    return this;
  }

  /**
   * Whether the trace is incomplete due to limits or errors
   * @return isIncomplete
   */
  public Boolean getIsIncomplete() {
    return isIncomplete;
  }

  public void setIsIncomplete(Boolean isIncomplete) {
    this.isIncomplete = isIncomplete;
  }


  public TONTransactionEmulatedTrace mcBlockSeqno(BigDecimal mcBlockSeqno) {
    this.mcBlockSeqno = mcBlockSeqno;
    return this;
  }

  /**
   * Masterchain block sequence number where emulation was performed
   * @return mcBlockSeqno
   */
  public BigDecimal getMcBlockSeqno() {
    return mcBlockSeqno;
  }

  public void setMcBlockSeqno(BigDecimal mcBlockSeqno) {
    this.mcBlockSeqno = mcBlockSeqno;
  }


  public TONTransactionEmulatedTrace metadata(Map<String, TONTransactionAddressMetadataEntry> metadata) {
    this.metadata = metadata;
    return this;
  }

  public TONTransactionEmulatedTrace putMetadataItem(String key, TONTransactionAddressMetadataEntry metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Metadata about addresses, including indexing and associated token info.
   * @return metadata
   */
  public Map<String, TONTransactionAddressMetadataEntry> getMetadata() {
    return metadata;
  }

  public void setMetadata(Map<String, TONTransactionAddressMetadataEntry> metadata) {
    this.metadata = metadata;
  }


  public TONTransactionEmulatedTrace trace(TONTransactionTraceNode trace) {
    this.trace = trace;
    return this;
  }

  /**
   * Get trace
   * @return trace
   */
  public TONTransactionTraceNode getTrace() {
    return trace;
  }

  public void setTrace(TONTransactionTraceNode trace) {
    this.trace = trace;
  }


  public TONTransactionEmulatedTrace transactions(Map<String, TONTransaction> transactions) {
    this.transactions = transactions;
    return this;
  }

  public TONTransactionEmulatedTrace putTransactionsItem(String key, TONTransaction transactionsItem) {
    if (this.transactions == null) {
      this.transactions = new HashMap<>();
    }
    this.transactions.put(key, transactionsItem);
    return this;
  }

  /**
   * Map of transaction hashes to transaction details
   * @return transactions
   */
  public Map<String, TONTransaction> getTransactions() {
    return transactions;
  }

  public void setTransactions(Map<String, TONTransaction> transactions) {
    this.transactions = transactions;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TONTransactionEmulatedTrace transactionEmulatedTrace = (TONTransactionEmulatedTrace) o;
    return Objects.equals(this.actions, transactionEmulatedTrace.actions) &&
        Objects.equals(this.addressBook, transactionEmulatedTrace.addressBook) &&
        Objects.equals(this.codeCells, transactionEmulatedTrace.codeCells) &&
        Objects.equals(this.dataCells, transactionEmulatedTrace.dataCells) &&
        Objects.equals(this.isIncomplete, transactionEmulatedTrace.isIncomplete) &&
        Objects.equals(this.mcBlockSeqno, transactionEmulatedTrace.mcBlockSeqno) &&
        Objects.equals(this.metadata, transactionEmulatedTrace.metadata) &&
        Objects.equals(this.trace, transactionEmulatedTrace.trace) &&
        Objects.equals(this.transactions, transactionEmulatedTrace.transactions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actions, addressBook, codeCells, dataCells, isIncomplete, mcBlockSeqno, metadata, trace, transactions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TONTransactionEmulatedTrace {\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    addressBook: ").append(toIndentedString(addressBook)).append("\n");
    sb.append("    codeCells: ").append(toIndentedString(codeCells)).append("\n");
    sb.append("    dataCells: ").append(toIndentedString(dataCells)).append("\n");
    sb.append("    isIncomplete: ").append(toIndentedString(isIncomplete)).append("\n");
    sb.append("    mcBlockSeqno: ").append(toIndentedString(mcBlockSeqno)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    trace: ").append(toIndentedString(trace)).append("\n");
    sb.append("    transactions: ").append(toIndentedString(transactions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("actions");
    openapiFields.add("addressBook");
    openapiFields.add("codeCells");
    openapiFields.add("dataCells");
    openapiFields.add("isIncomplete");
    openapiFields.add("mcBlockSeqno");
    openapiFields.add("metadata");
    openapiFields.add("trace");
    openapiFields.add("transactions");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("actions");
    openapiRequiredFields.add("addressBook");
    openapiRequiredFields.add("codeCells");
    openapiRequiredFields.add("dataCells");
    openapiRequiredFields.add("isIncomplete");
    openapiRequiredFields.add("mcBlockSeqno");
    openapiRequiredFields.add("metadata");
    openapiRequiredFields.add("trace");
    openapiRequiredFields.add("transactions");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TONTransactionEmulatedTrace
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TONTransactionEmulatedTrace.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TONTransactionEmulatedTrace is not found in the empty JSON string", TONTransactionEmulatedTrace.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TONTransactionEmulatedTrace.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TONTransactionEmulatedTrace` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TONTransactionEmulatedTrace.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("actions").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `actions` to be an array in the JSON string but got `%s`", jsonObj.get("actions").toString()));
      }

      JsonArray jsonArrayactions = jsonObj.getAsJsonArray("actions");
      // validate the required field `actions` (array)
      for (int i = 0; i < jsonArrayactions.size(); i++) {
        TONTransactionTraceAction.validateJsonElement(jsonArrayactions.get(i));
      };
      // validate the required field `trace`
      TONTransactionTraceNode.validateJsonElement(jsonObj.get("trace"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TONTransactionEmulatedTrace.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TONTransactionEmulatedTrace' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TONTransactionEmulatedTrace> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TONTransactionEmulatedTrace.class));

       return (TypeAdapter<T>) new TypeAdapter<TONTransactionEmulatedTrace>() {
           @Override
           public void write(JsonWriter out, TONTransactionEmulatedTrace value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TONTransactionEmulatedTrace read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TONTransactionEmulatedTrace given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TONTransactionEmulatedTrace
   * @throws IOException if the JSON string is invalid with respect to TONTransactionEmulatedTrace
   */
  public static TONTransactionEmulatedTrace fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TONTransactionEmulatedTrace.class);
  }

  /**
   * Convert an instance of TONTransactionEmulatedTrace to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

