/*
 * TON WalletKit models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ton.walletkit.api;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.ton.walletkit.api.TONTransactionTokenInfoAnyOf;
import org.ton.walletkit.api.TONTransactionTokenInfoAnyOf1;
import org.ton.walletkit.api.TONTransactionTokenInfoAnyOf2;
import org.ton.walletkit.api.TONTransactionTokenInfoBase;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import org.ton.walletkit.api.JSON;

public class TONTransactionTokenInfo extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(TONTransactionTokenInfo.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!TONTransactionTokenInfo.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'TONTransactionTokenInfo' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<TONTransactionTokenInfoAnyOf> adapterTONTransactionTokenInfoAnyOf = gson.getDelegateAdapter(this, TypeToken.get(TONTransactionTokenInfoAnyOf.class));
            final TypeAdapter<TONTransactionTokenInfoAnyOf1> adapterTONTransactionTokenInfoAnyOf1 = gson.getDelegateAdapter(this, TypeToken.get(TONTransactionTokenInfoAnyOf1.class));
            final TypeAdapter<TONTransactionTokenInfoAnyOf2> adapterTONTransactionTokenInfoAnyOf2 = gson.getDelegateAdapter(this, TypeToken.get(TONTransactionTokenInfoAnyOf2.class));

            return (TypeAdapter<T>) new TypeAdapter<TONTransactionTokenInfo>() {
                @Override
                public void write(JsonWriter out, TONTransactionTokenInfo value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `TONTransactionTokenInfoAnyOf`
                    if (value.getActualInstance() instanceof TONTransactionTokenInfoAnyOf) {
                        JsonElement element = adapterTONTransactionTokenInfoAnyOf.toJsonTree((TONTransactionTokenInfoAnyOf)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `TONTransactionTokenInfoAnyOf1`
                    if (value.getActualInstance() instanceof TONTransactionTokenInfoAnyOf1) {
                        JsonElement element = adapterTONTransactionTokenInfoAnyOf1.toJsonTree((TONTransactionTokenInfoAnyOf1)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `TONTransactionTokenInfoAnyOf2`
                    if (value.getActualInstance() instanceof TONTransactionTokenInfoAnyOf2) {
                        JsonElement element = adapterTONTransactionTokenInfoAnyOf2.toJsonTree((TONTransactionTokenInfoAnyOf2)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match anyOf schemas: TONTransactionTokenInfoAnyOf, TONTransactionTokenInfoAnyOf1, TONTransactionTokenInfoAnyOf2");
                }

                @Override
                public TONTransactionTokenInfo read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize TONTransactionTokenInfoAnyOf
                    try {
                        // validate the JSON object to see if any exception is thrown
                        TONTransactionTokenInfoAnyOf.validateJsonElement(jsonElement);
                        actualAdapter = adapterTONTransactionTokenInfoAnyOf;
                        TONTransactionTokenInfo ret = new TONTransactionTokenInfo();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for TONTransactionTokenInfoAnyOf failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'TONTransactionTokenInfoAnyOf'", e);
                    }
                    // deserialize TONTransactionTokenInfoAnyOf1
                    try {
                        // validate the JSON object to see if any exception is thrown
                        TONTransactionTokenInfoAnyOf1.validateJsonElement(jsonElement);
                        actualAdapter = adapterTONTransactionTokenInfoAnyOf1;
                        TONTransactionTokenInfo ret = new TONTransactionTokenInfo();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for TONTransactionTokenInfoAnyOf1 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'TONTransactionTokenInfoAnyOf1'", e);
                    }
                    // deserialize TONTransactionTokenInfoAnyOf2
                    try {
                        // validate the JSON object to see if any exception is thrown
                        TONTransactionTokenInfoAnyOf2.validateJsonElement(jsonElement);
                        actualAdapter = adapterTONTransactionTokenInfoAnyOf2;
                        TONTransactionTokenInfo ret = new TONTransactionTokenInfo();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for TONTransactionTokenInfoAnyOf2 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'TONTransactionTokenInfoAnyOf2'", e);
                    }

                    throw new IOException(String.format("Failed deserialization for TONTransactionTokenInfo: no class matches result, expected at least 1. Detailed failure message for anyOf schemas: %s. JSON: %s", errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public TONTransactionTokenInfo() {
        super("anyOf", Boolean.FALSE);
    }

    public TONTransactionTokenInfo(Object o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("TONTransactionTokenInfoAnyOf", TONTransactionTokenInfoAnyOf.class);
        schemas.put("TONTransactionTokenInfoAnyOf1", TONTransactionTokenInfoAnyOf1.class);
        schemas.put("TONTransactionTokenInfoAnyOf2", TONTransactionTokenInfoAnyOf2.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return TONTransactionTokenInfo.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * TONTransactionTokenInfoAnyOf, TONTransactionTokenInfoAnyOf1, TONTransactionTokenInfoAnyOf2
     *
     * It could be an instance of the 'anyOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof TONTransactionTokenInfoAnyOf) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof TONTransactionTokenInfoAnyOf1) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof TONTransactionTokenInfoAnyOf2) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be TONTransactionTokenInfoAnyOf, TONTransactionTokenInfoAnyOf1, TONTransactionTokenInfoAnyOf2");
    }

    /**
     * Get the actual instance, which can be the following:
     * TONTransactionTokenInfoAnyOf, TONTransactionTokenInfoAnyOf1, TONTransactionTokenInfoAnyOf2
     *
     * @return The actual instance (TONTransactionTokenInfoAnyOf, TONTransactionTokenInfoAnyOf1, TONTransactionTokenInfoAnyOf2)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `TONTransactionTokenInfoAnyOf`. If the actual instance is not `TONTransactionTokenInfoAnyOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TONTransactionTokenInfoAnyOf`
     * @throws ClassCastException if the instance is not `TONTransactionTokenInfoAnyOf`
     */
    public TONTransactionTokenInfoAnyOf getTONTransactionTokenInfoAnyOf() throws ClassCastException {
        return (TONTransactionTokenInfoAnyOf)super.getActualInstance();
    }
    /**
     * Get the actual instance of `TONTransactionTokenInfoAnyOf1`. If the actual instance is not `TONTransactionTokenInfoAnyOf1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TONTransactionTokenInfoAnyOf1`
     * @throws ClassCastException if the instance is not `TONTransactionTokenInfoAnyOf1`
     */
    public TONTransactionTokenInfoAnyOf1 getTONTransactionTokenInfoAnyOf1() throws ClassCastException {
        return (TONTransactionTokenInfoAnyOf1)super.getActualInstance();
    }
    /**
     * Get the actual instance of `TONTransactionTokenInfoAnyOf2`. If the actual instance is not `TONTransactionTokenInfoAnyOf2`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TONTransactionTokenInfoAnyOf2`
     * @throws ClassCastException if the instance is not `TONTransactionTokenInfoAnyOf2`
     */
    public TONTransactionTokenInfoAnyOf2 getTONTransactionTokenInfoAnyOf2() throws ClassCastException {
        return (TONTransactionTokenInfoAnyOf2)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to TONTransactionTokenInfo
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate anyOf schemas one by one
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with TONTransactionTokenInfoAnyOf
        try {
            TONTransactionTokenInfoAnyOf.validateJsonElement(jsonElement);
            return;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for TONTransactionTokenInfoAnyOf failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with TONTransactionTokenInfoAnyOf1
        try {
            TONTransactionTokenInfoAnyOf1.validateJsonElement(jsonElement);
            return;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for TONTransactionTokenInfoAnyOf1 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with TONTransactionTokenInfoAnyOf2
        try {
            TONTransactionTokenInfoAnyOf2.validateJsonElement(jsonElement);
            return;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for TONTransactionTokenInfoAnyOf2 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        throw new IOException(String.format("The JSON string is invalid for TONTransactionTokenInfo with anyOf schemas: TONTransactionTokenInfoAnyOf, TONTransactionTokenInfoAnyOf1, TONTransactionTokenInfoAnyOf2. no class match the result, expected at least 1. Detailed failure message for anyOf schemas: %s. JSON: %s", errorMessages, jsonElement.toString()));
    }

    /**
     * Create an instance of TONTransactionTokenInfo given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of TONTransactionTokenInfo
     * @throws IOException if the JSON string is invalid with respect to TONTransactionTokenInfo
     */
    public static TONTransactionTokenInfo fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, TONTransactionTokenInfo.class);
    }

    /**
     * Convert an instance of TONTransactionTokenInfo to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

