//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

/** Token animation URL for displaying animated media. */
public class TONTokenAnimation {

    /** Builds one of these from JSON. */
    public static final Parser<TONTokenAnimation> PARSER = new Parser<TONTokenAnimation>() {
        @Override
        public TONTokenAnimation parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private String lottie;
    private String url;

    /** Optional Lottie animation data as a string */
    public String getLottie() {
        return lottie;
    }

    public TONTokenAnimation setLottie(String value) {
        this.lottie = value;
        return this;
    }

    /** URL to the animation file (e.g., GIF, MP4, Lottie) */
    public String getUrl() {
        return url;
    }

    public TONTokenAnimation setUrl(String value) {
        this.url = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "lottie", lottie);
        TonApiJson.put(json, "url", url);
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONTokenAnimation fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONTokenAnimation out = new TONTokenAnimation();
        out.lottie = TonApiJson.optString(json, "lottie");
        out.url = TonApiJson.optString(json, "url");
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
