//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

/** Size metrics for messages created in a transaction. */
public class TONTransactionActionMessageSize {

    /** Builds one of these from JSON. */
    public static final Parser<TONTransactionActionMessageSize> PARSER = new Parser<TONTransactionActionMessageSize>() {
        @Override
        public TONTransactionActionMessageSize parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private Double bits;
    private Double cells;

    /** The total number of bits used */
    public Double getBits() {
        return bits;
    }

    public TONTransactionActionMessageSize setBits(Double value) {
        this.bits = value;
        return this;
    }

    /** The total number of cells used */
    public Double getCells() {
        return cells;
    }

    public TONTransactionActionMessageSize setCells(Double value) {
        this.cells = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "bits", bits);
        TonApiJson.put(json, "cells", cells);
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONTransactionActionMessageSize fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONTransactionActionMessageSize out = new TONTransactionActionMessageSize();
        out.bits = TonApiJson.optDouble(json, "bits");
        out.cells = TonApiJson.optDouble(json, "cells");
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
