//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

/** Individual message within a transaction request. */
public class TONTransactionRequestMessage {

    /** Builds one of these from JSON. */
    public static final Parser<TONTransactionRequestMessage> PARSER = new Parser<TONTransactionRequestMessage>() {
        @Override
        public TONTransactionRequestMessage parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private String address;
    private String amount;
    private TONExtraCurrencies extraCurrency;
    private TONSendMode mode;
    private String payload;
    private String stateInit;

    /**
     * Recipient wallet address in format received from caller (raw, user friendly)
     * Required by the API.
     */
    public String getAddress() {
        return address;
    }

    public TONTransactionRequestMessage setAddress(String value) {
        this.address = value;
        return this;
    }

    /**
     * Amount to transfer in nanos
     * Required by the API.
     */
    public String getAmount() {
        return amount;
    }

    public TONTransactionRequestMessage setAmount(String value) {
        this.amount = value;
        return this;
    }

    /** Additional currencies to include in the transfer */
    public TONExtraCurrencies getExtraCurrency() {
        return extraCurrency;
    }

    public TONTransactionRequestMessage setExtraCurrency(TONExtraCurrencies value) {
        this.extraCurrency = value;
        return this;
    }

    /** Send mode flags controlling message behavior */
    public TONSendMode getMode() {
        return mode;
    }

    public TONTransactionRequestMessage setMode(TONSendMode value) {
        this.mode = value;
        return this;
    }

    /** Message payload data encoded in Base64 */
    public String getPayload() {
        return payload;
    }

    public TONTransactionRequestMessage setPayload(String value) {
        this.payload = value;
        return this;
    }

    /** Initial state for deploying a new contract, encoded in Base64 */
    public String getStateInit() {
        return stateInit;
    }

    public TONTransactionRequestMessage setStateInit(String value) {
        this.stateInit = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "address", address);
        TonApiJson.put(json, "amount", amount);
        TonApiJson.put(json, "extraCurrency", extraCurrency == null ? null : extraCurrency.toJson());
        TonApiJson.put(json, "mode", mode == null ? null : mode.toJson());
        TonApiJson.put(json, "payload", payload);
        TonApiJson.put(json, "stateInit", stateInit);
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONTransactionRequestMessage fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONTransactionRequestMessage out = new TONTransactionRequestMessage();
        out.address = TonApiJson.optString(json, "address");
        out.amount = TonApiJson.optString(json, "amount");
        out.extraCurrency = TONExtraCurrencies.fromJson(TonApiJson.optObject(json, "extraCurrency"));
        out.mode = TONSendMode.fromJson(TonApiJson.optObject(json, "mode"));
        out.payload = TonApiJson.optString(json, "payload");
        out.stateInit = TonApiJson.optString(json, "stateInit");
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
