/*
 * TON WalletKit models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ton.walletkit.api;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.ton.walletkit.api.JSON;

/**
 * TONTransactionTraceActionCallContractDetails
 */
public class TONTransactionTraceActionCallContractDetails {
  public static final String SERIALIZED_NAME_DESTINATION = "destination";
  @SerializedName(SERIALIZED_NAME_DESTINATION)
  private String destination;

  public static final String SERIALIZED_NAME_OPCODE = "opcode";
  @SerializedName(SERIALIZED_NAME_OPCODE)
  private String opcode;

  public static final String SERIALIZED_NAME_SOURCE = "source";
  @SerializedName(SERIALIZED_NAME_SOURCE)
  private String source;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;

  public static final String SERIALIZED_NAME_VALUE_EXTRA_CURRENCIES = "valueExtraCurrencies";
  @SerializedName(SERIALIZED_NAME_VALUE_EXTRA_CURRENCIES)
  private Map<String, String> valueExtraCurrencies = new HashMap<>();

  public TONTransactionTraceActionCallContractDetails() {
  }

  public TONTransactionTraceActionCallContractDetails destination(String destination) {
    this.destination = destination;
    return this;
  }

  /**
   * User-friendly TON address representation (e.g., \&quot;EQDtFpEwcFAEcRe5mLVh2N6C0x-_hJEM7W61_JLnSF74p4q2\&quot;)
   * @return destination
   */
  public String getDestination() {
    return destination;
  }

  public void setDestination(String destination) {
    this.destination = destination;
  }


  public TONTransactionTraceActionCallContractDetails opcode(String opcode) {
    this.opcode = opcode;
    return this;
  }

  /**
   * Opcode or method identifier of the contract call.
   * @return opcode
   */
  public String getOpcode() {
    return opcode;
  }

  public void setOpcode(String opcode) {
    this.opcode = opcode;
  }


  public TONTransactionTraceActionCallContractDetails source(String source) {
    this.source = source;
    return this;
  }

  /**
   * User-friendly TON address representation (e.g., \&quot;EQDtFpEwcFAEcRe5mLVh2N6C0x-_hJEM7W61_JLnSF74p4q2\&quot;)
   * @return source
   */
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }


  public TONTransactionTraceActionCallContractDetails value(String value) {
    this.value = value;
    return this;
  }

  /**
   * Token amount represented as a string to preserve precision. For TON, this is typically in nanotons (1 TON &#x3D; 10^9 nanotons).
   * @return value
   */
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  public TONTransactionTraceActionCallContractDetails valueExtraCurrencies(Map<String, String> valueExtraCurrencies) {
    this.valueExtraCurrencies = valueExtraCurrencies;
    return this;
  }

  public TONTransactionTraceActionCallContractDetails putValueExtraCurrenciesItem(String key, String valueExtraCurrenciesItem) {
    if (this.valueExtraCurrencies == null) {
      this.valueExtraCurrencies = new HashMap<>();
    }
    this.valueExtraCurrencies.put(key, valueExtraCurrenciesItem);
    return this;
  }

  /**
   * Map of extra currency IDs to their amounts. Extra currencies are additional tokens that can be attached to TON messages.
   * @return valueExtraCurrencies
   */
  public Map<String, String> getValueExtraCurrencies() {
    return valueExtraCurrencies;
  }

  public void setValueExtraCurrencies(Map<String, String> valueExtraCurrencies) {
    this.valueExtraCurrencies = valueExtraCurrencies;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TONTransactionTraceActionCallContractDetails transactionTraceActionCallContractDetails = (TONTransactionTraceActionCallContractDetails) o;
    return Objects.equals(this.destination, transactionTraceActionCallContractDetails.destination) &&
        Objects.equals(this.opcode, transactionTraceActionCallContractDetails.opcode) &&
        Objects.equals(this.source, transactionTraceActionCallContractDetails.source) &&
        Objects.equals(this.value, transactionTraceActionCallContractDetails.value) &&
        Objects.equals(this.valueExtraCurrencies, transactionTraceActionCallContractDetails.valueExtraCurrencies);
  }

  @Override
  public int hashCode() {
    return Objects.hash(destination, opcode, source, value, valueExtraCurrencies);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TONTransactionTraceActionCallContractDetails {\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    opcode: ").append(toIndentedString(opcode)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    valueExtraCurrencies: ").append(toIndentedString(valueExtraCurrencies)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("destination");
    openapiFields.add("opcode");
    openapiFields.add("source");
    openapiFields.add("value");
    openapiFields.add("valueExtraCurrencies");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("opcode");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TONTransactionTraceActionCallContractDetails
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TONTransactionTraceActionCallContractDetails.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TONTransactionTraceActionCallContractDetails is not found in the empty JSON string", TONTransactionTraceActionCallContractDetails.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TONTransactionTraceActionCallContractDetails.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TONTransactionTraceActionCallContractDetails` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TONTransactionTraceActionCallContractDetails.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("destination") != null && !jsonObj.get("destination").isJsonNull()) && !jsonObj.get("destination").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `destination` to be a primitive type in the JSON string but got `%s`", jsonObj.get("destination").toString()));
      }
      if (!jsonObj.get("opcode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `opcode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("opcode").toString()));
      }
      if ((jsonObj.get("source") != null && !jsonObj.get("source").isJsonNull()) && !jsonObj.get("source").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `source` to be a primitive type in the JSON string but got `%s`", jsonObj.get("source").toString()));
      }
      if ((jsonObj.get("value") != null && !jsonObj.get("value").isJsonNull()) && !jsonObj.get("value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("value").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TONTransactionTraceActionCallContractDetails.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TONTransactionTraceActionCallContractDetails' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TONTransactionTraceActionCallContractDetails> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TONTransactionTraceActionCallContractDetails.class));

       return (TypeAdapter<T>) new TypeAdapter<TONTransactionTraceActionCallContractDetails>() {
           @Override
           public void write(JsonWriter out, TONTransactionTraceActionCallContractDetails value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TONTransactionTraceActionCallContractDetails read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TONTransactionTraceActionCallContractDetails given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TONTransactionTraceActionCallContractDetails
   * @throws IOException if the JSON string is invalid with respect to TONTransactionTraceActionCallContractDetails
   */
  public static TONTransactionTraceActionCallContractDetails fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TONTransactionTraceActionCallContractDetails.class);
  }

  /**
   * Convert an instance of TONTransactionTraceActionCallContractDetails to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

