/*
 * TON WalletKit models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ton.walletkit.api;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.ton.walletkit.api.JSON;

/**
 * Content of a transaction message (body or init state).
 */
public class TONTransactionMessageContent {
  public static final String SERIALIZED_NAME_BODY = "body";
  @SerializedName(SERIALIZED_NAME_BODY)
  private String body;

  public static final String SERIALIZED_NAME_DECODED = "decoded";
  @SerializedName(SERIALIZED_NAME_DECODED)
  private Object decoded = null;

  public static final String SERIALIZED_NAME_HASH = "hash";
  @SerializedName(SERIALIZED_NAME_HASH)
  private String hash;

  public TONTransactionMessageContent() {
  }

  public TONTransactionMessageContent body(String body) {
    this.body = body;
    return this;
  }

  /**
   * Base64-encoded string representation
   * @return body
   */
  public String getBody() {
    return body;
  }

  public void setBody(String body) {
    this.body = body;
  }


  public TONTransactionMessageContent decoded(Object decoded) {
    this.decoded = decoded;
    return this;
  }

  /**
   * The decoded metadata from the initial state body
   * @return decoded
   */
  public Object getDecoded() {
    return decoded;
  }

  public void setDecoded(Object decoded) {
    this.decoded = decoded;
  }


  public TONTransactionMessageContent hash(String hash) {
    this.hash = hash;
    return this;
  }

  /**
   * The hash of the initial state
   * @return hash
   */
  public String getHash() {
    return hash;
  }

  public void setHash(String hash) {
    this.hash = hash;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TONTransactionMessageContent transactionMessageContent = (TONTransactionMessageContent) o;
    return Objects.equals(this.body, transactionMessageContent.body) &&
        Objects.equals(this.decoded, transactionMessageContent.decoded) &&
        Objects.equals(this.hash, transactionMessageContent.hash);
  }

  @Override
  public int hashCode() {
    return Objects.hash(body, decoded, hash);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TONTransactionMessageContent {\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    decoded: ").append(toIndentedString(decoded)).append("\n");
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("body");
    openapiFields.add("decoded");
    openapiFields.add("hash");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TONTransactionMessageContent
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TONTransactionMessageContent.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TONTransactionMessageContent is not found in the empty JSON string", TONTransactionMessageContent.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TONTransactionMessageContent.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TONTransactionMessageContent` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("body") != null && !jsonObj.get("body").isJsonNull()) && !jsonObj.get("body").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `body` to be a primitive type in the JSON string but got `%s`", jsonObj.get("body").toString()));
      }
      if ((jsonObj.get("hash") != null && !jsonObj.get("hash").isJsonNull()) && !jsonObj.get("hash").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hash` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hash").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TONTransactionMessageContent.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TONTransactionMessageContent' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TONTransactionMessageContent> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TONTransactionMessageContent.class));

       return (TypeAdapter<T>) new TypeAdapter<TONTransactionMessageContent>() {
           @Override
           public void write(JsonWriter out, TONTransactionMessageContent value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TONTransactionMessageContent read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TONTransactionMessageContent given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TONTransactionMessageContent
   * @throws IOException if the JSON string is invalid with respect to TONTransactionMessageContent
   */
  public static TONTransactionMessageContent fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TONTransactionMessageContent.class);
  }

  /**
   * Convert an instance of TONTransactionMessageContent to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

