/*
 * TON WalletKit models
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ton.walletkit.api;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.ton.walletkit.api.JSON;

/**
 * Token image URLs in various sizes for display purposes.
 */
public class TONTokenImage {
  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private byte[] data;

  public static final String SERIALIZED_NAME_LARGE_URL = "largeUrl";
  @SerializedName(SERIALIZED_NAME_LARGE_URL)
  private String largeUrl;

  public static final String SERIALIZED_NAME_MEDIUM_URL = "mediumUrl";
  @SerializedName(SERIALIZED_NAME_MEDIUM_URL)
  private String mediumUrl;

  public static final String SERIALIZED_NAME_SMALL_URL = "smallUrl";
  @SerializedName(SERIALIZED_NAME_SMALL_URL)
  private String smallUrl;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public TONTokenImage() {
  }

  public TONTokenImage data(byte[] data) {
    this.data = data;
    return this;
  }

  /**
   * Raw image data encoded in Base64
   * @return data
   */
  public byte[] getData() {
    return data;
  }

  public void setData(byte[] data) {
    this.data = data;
  }


  public TONTokenImage largeUrl(String largeUrl) {
    this.largeUrl = largeUrl;
    return this;
  }

  /**
   * Large image URL (typically 512x512 or higher)
   * @return largeUrl
   */
  public String getLargeUrl() {
    return largeUrl;
  }

  public void setLargeUrl(String largeUrl) {
    this.largeUrl = largeUrl;
  }


  public TONTokenImage mediumUrl(String mediumUrl) {
    this.mediumUrl = mediumUrl;
    return this;
  }

  /**
   * Medium-sized image URL (typically 256x256 or similar)
   * @return mediumUrl
   */
  public String getMediumUrl() {
    return mediumUrl;
  }

  public void setMediumUrl(String mediumUrl) {
    this.mediumUrl = mediumUrl;
  }


  public TONTokenImage smallUrl(String smallUrl) {
    this.smallUrl = smallUrl;
    return this;
  }

  /**
   * Small thumbnail URL (typically 64x64 or similar)
   * @return smallUrl
   */
  public String getSmallUrl() {
    return smallUrl;
  }

  public void setSmallUrl(String smallUrl) {
    this.smallUrl = smallUrl;
  }


  public TONTokenImage url(String url) {
    this.url = url;
    return this;
  }

  /**
   * Original image URL
   * @return url
   */
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TONTokenImage tokenImage = (TONTokenImage) o;
    return Arrays.equals(this.data, tokenImage.data) &&
        Objects.equals(this.largeUrl, tokenImage.largeUrl) &&
        Objects.equals(this.mediumUrl, tokenImage.mediumUrl) &&
        Objects.equals(this.smallUrl, tokenImage.smallUrl) &&
        Objects.equals(this.url, tokenImage.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Arrays.hashCode(data), largeUrl, mediumUrl, smallUrl, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TONTokenImage {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    largeUrl: ").append(toIndentedString(largeUrl)).append("\n");
    sb.append("    mediumUrl: ").append(toIndentedString(mediumUrl)).append("\n");
    sb.append("    smallUrl: ").append(toIndentedString(smallUrl)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("data");
    openapiFields.add("largeUrl");
    openapiFields.add("mediumUrl");
    openapiFields.add("smallUrl");
    openapiFields.add("url");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TONTokenImage
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TONTokenImage.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TONTokenImage is not found in the empty JSON string", TONTokenImage.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TONTokenImage.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TONTokenImage` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("largeUrl") != null && !jsonObj.get("largeUrl").isJsonNull()) && !jsonObj.get("largeUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `largeUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("largeUrl").toString()));
      }
      if ((jsonObj.get("mediumUrl") != null && !jsonObj.get("mediumUrl").isJsonNull()) && !jsonObj.get("mediumUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `mediumUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mediumUrl").toString()));
      }
      if ((jsonObj.get("smallUrl") != null && !jsonObj.get("smallUrl").isJsonNull()) && !jsonObj.get("smallUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `smallUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("smallUrl").toString()));
      }
      if ((jsonObj.get("url") != null && !jsonObj.get("url").isJsonNull()) && !jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TONTokenImage.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TONTokenImage' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TONTokenImage> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TONTokenImage.class));

       return (TypeAdapter<T>) new TypeAdapter<TONTokenImage>() {
           @Override
           public void write(JsonWriter out, TONTokenImage value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TONTokenImage read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TONTokenImage given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TONTokenImage
   * @throws IOException if the JSON string is invalid with respect to TONTokenImage
   */
  public static TONTokenImage fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TONTokenImage.class);
  }

  /**
   * Convert an instance of TONTokenImage to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

