//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

/** Token image URLs in various sizes for display purposes. */
public class TONTokenImage {

    /** Builds one of these from JSON. */
    public static final Parser<TONTokenImage> PARSER = new Parser<TONTokenImage>() {
        @Override
        public TONTokenImage parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private String data;
    private String largeUrl;
    private String mediumUrl;
    private String smallUrl;
    private String url;

    /** Raw image data encoded in Base64 */
    public String getData() {
        return data;
    }

    public TONTokenImage setData(String value) {
        this.data = value;
        return this;
    }

    /** Large image URL (typically 512x512 or higher) */
    public String getLargeUrl() {
        return largeUrl;
    }

    public TONTokenImage setLargeUrl(String value) {
        this.largeUrl = value;
        return this;
    }

    /** Medium-sized image URL (typically 256x256 or similar) */
    public String getMediumUrl() {
        return mediumUrl;
    }

    public TONTokenImage setMediumUrl(String value) {
        this.mediumUrl = value;
        return this;
    }

    /** Small thumbnail URL (typically 64x64 or similar) */
    public String getSmallUrl() {
        return smallUrl;
    }

    public TONTokenImage setSmallUrl(String value) {
        this.smallUrl = value;
        return this;
    }

    /** Original image URL */
    public String getUrl() {
        return url;
    }

    public TONTokenImage setUrl(String value) {
        this.url = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "data", data);
        TonApiJson.put(json, "largeUrl", largeUrl);
        TonApiJson.put(json, "mediumUrl", mediumUrl);
        TonApiJson.put(json, "smallUrl", smallUrl);
        TonApiJson.put(json, "url", url);
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONTokenImage fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONTokenImage out = new TONTokenImage();
        out.data = TonApiJson.optString(json, "data");
        out.largeUrl = TonApiJson.optString(json, "largeUrl");
        out.mediumUrl = TonApiJson.optString(json, "mediumUrl");
        out.smallUrl = TonApiJson.optString(json, "smallUrl");
        out.url = TonApiJson.optString(json, "url");
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
