//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import java.util.List;

import org.json.JSONObject;

/** High-level action extracted from a transaction trace. */
public class TONTransactionTraceAction {

    /** Builds one of these from JSON. */
    public static final Parser<TONTransactionTraceAction> PARSER = new Parser<TONTransactionTraceAction>() {
        @Override
        public TONTransactionTraceAction parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private List<String> accounts;
    private String actionId;
    private TONTransactionTraceActionDetails details;
    private String endLt;
    private Double endUtime;
    private Boolean isSuccess;
    private String startLt;
    private Double startUtime;
    private String traceEndLt;
    private Double traceEndUtime;
    private String traceId;
    private Double traceMcSeqnoEnd;
    private List<Object> transactions;

    /**
     * List of accounts involved in this action
     * Required by the API.
     */
    public List<String> getAccounts() {
        return accounts;
    }

    public TONTransactionTraceAction setAccounts(List<String> value) {
        this.accounts = value;
        return this;
    }

    /** Action identifier */
    public String getActionId() {
        return actionId;
    }

    public TONTransactionTraceAction setActionId(String value) {
        this.actionId = value;
        return this;
    }

    /**
     * Detailed information about the action
     * Required by the API.
     */
    public TONTransactionTraceActionDetails getDetails() {
        return details;
    }

    public TONTransactionTraceAction setDetails(TONTransactionTraceActionDetails value) {
        this.details = value;
        return this;
    }

    /** Logical time when the action ended */
    public String getEndLt() {
        return endLt;
    }

    public TONTransactionTraceAction setEndLt(String value) {
        this.endLt = value;
        return this;
    }

    /** Unix time when the action ended */
    public Double getEndUtime() {
        return endUtime;
    }

    public TONTransactionTraceAction setEndUtime(Double value) {
        this.endUtime = value;
        return this;
    }

    /** Indicates if the action was successful */
    public Boolean getIsSuccess() {
        return isSuccess;
    }

    public TONTransactionTraceAction setIsSuccess(Boolean value) {
        this.isSuccess = value;
        return this;
    }

    /** Logical time when the action started */
    public String getStartLt() {
        return startLt;
    }

    public TONTransactionTraceAction setStartLt(String value) {
        this.startLt = value;
        return this;
    }

    /** Unix time when the action started */
    public Double getStartUtime() {
        return startUtime;
    }

    public TONTransactionTraceAction setStartUtime(Double value) {
        this.startUtime = value;
        return this;
    }

    /** Logical time when the trace ended */
    public String getTraceEndLt() {
        return traceEndLt;
    }

    public TONTransactionTraceAction setTraceEndLt(String value) {
        this.traceEndLt = value;
        return this;
    }

    /** Unix time when the trace ended */
    public Double getTraceEndUtime() {
        return traceEndUtime;
    }

    public TONTransactionTraceAction setTraceEndUtime(Double value) {
        this.traceEndUtime = value;
        return this;
    }

    /** Trace identifier */
    public String getTraceId() {
        return traceId;
    }

    public TONTransactionTraceAction setTraceId(String value) {
        this.traceId = value;
        return this;
    }

    /** Masterchain block sequence number when the trace ended */
    public Double getTraceMcSeqnoEnd() {
        return traceMcSeqnoEnd;
    }

    public TONTransactionTraceAction setTraceMcSeqnoEnd(Double value) {
        this.traceMcSeqnoEnd = value;
        return this;
    }

    /**
     * List of transaction hashes involved in this action
     * Required by the API.
     */
    public List<Object> getTransactions() {
        return transactions;
    }

    public TONTransactionTraceAction setTransactions(List<Object> value) {
        this.transactions = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "accounts", TonApiJson.array(accounts));
        TonApiJson.put(json, "actionId", actionId);
        TonApiJson.put(json, "details", details == null ? null : details.toJson());
        TonApiJson.put(json, "endLt", endLt);
        TonApiJson.put(json, "endUtime", endUtime);
        TonApiJson.put(json, "isSuccess", isSuccess);
        TonApiJson.put(json, "startLt", startLt);
        TonApiJson.put(json, "startUtime", startUtime);
        TonApiJson.put(json, "traceEndLt", traceEndLt);
        TonApiJson.put(json, "traceEndUtime", traceEndUtime);
        TonApiJson.put(json, "traceId", traceId);
        TonApiJson.put(json, "traceMcSeqnoEnd", traceMcSeqnoEnd);
        TonApiJson.put(json, "transactions", TonApiJson.array(transactions));
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONTransactionTraceAction fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONTransactionTraceAction out = new TONTransactionTraceAction();
        out.accounts = TonApiJson.stringList(TonApiJson.optArray(json, "accounts"));
        out.actionId = TonApiJson.optString(json, "actionId");
        out.details = TONTransactionTraceActionDetails.fromJson(TonApiJson.optObject(json, "details"));
        out.endLt = TonApiJson.optString(json, "endLt");
        out.endUtime = TonApiJson.optDouble(json, "endUtime");
        out.isSuccess = TonApiJson.optBoolean(json, "isSuccess");
        out.startLt = TonApiJson.optString(json, "startLt");
        out.startUtime = TonApiJson.optDouble(json, "startUtime");
        out.traceEndLt = TonApiJson.optString(json, "traceEndLt");
        out.traceEndUtime = TonApiJson.optDouble(json, "traceEndUtime");
        out.traceId = TonApiJson.optString(json, "traceId");
        out.traceMcSeqnoEnd = TonApiJson.optDouble(json, "traceMcSeqnoEnd");
        out.transactions = TonApiJson.anyList(TonApiJson.optArray(json, "transactions"));
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
