//
// Copyright (c) Fela Ameghino 2026
//
// Distributed under the MIT License. (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)
//
// GENERATED by scripts/generate-api/emit-java-dto.mjs from the walletkit types —
// do not edit. Run `npm run java` in scripts/generate-api to regenerate.
//

package org.ton.walletkit.api;

import org.json.JSONObject;

public class TONTransactionTraceActionCallContractDetails {

    /** Builds one of these from JSON. */
    public static final Parser<TONTransactionTraceActionCallContractDetails> PARSER = new Parser<TONTransactionTraceActionCallContractDetails>() {
        @Override
        public TONTransactionTraceActionCallContractDetails parse(JSONObject json) {
            return fromJson(json);
        }
    };

    private String destination;
    private String opcode;
    private String source;
    private String value;
    private TONExtraCurrencies valueExtraCurrencies;

    /** Address of the receiver account. */
    public String getDestination() {
        return destination;
    }

    public TONTransactionTraceActionCallContractDetails setDestination(String value) {
        this.destination = value;
        return this;
    }

    /**
     * Opcode or method identifier of the contract call.
     * Required by the API.
     */
    public String getOpcode() {
        return opcode;
    }

    public TONTransactionTraceActionCallContractDetails setOpcode(String value) {
        this.opcode = value;
        return this;
    }

    /** Address of the sender account. */
    public String getSource() {
        return source;
    }

    public TONTransactionTraceActionCallContractDetails setSource(String value) {
        this.source = value;
        return this;
    }

    /** Value transferred during the contract call. */
    public String getValue() {
        return value;
    }

    public TONTransactionTraceActionCallContractDetails setValue(String value) {
        this.value = value;
        return this;
    }

    /** Extra currencies sent with the call. */
    public TONExtraCurrencies getValueExtraCurrencies() {
        return valueExtraCurrencies;
    }

    public TONTransactionTraceActionCallContractDetails setValueExtraCurrencies(TONExtraCurrencies value) {
        this.valueExtraCurrencies = value;
        return this;
    }

    /** This model as JSON. Null members are omitted, not written as null. */
    public JSONObject toJson() {
        JSONObject json = new JSONObject();
        TonApiJson.put(json, "destination", destination);
        TonApiJson.put(json, "opcode", opcode);
        TonApiJson.put(json, "source", source);
        TonApiJson.put(json, "value", value);
        TonApiJson.put(json, "valueExtraCurrencies", valueExtraCurrencies == null ? null : valueExtraCurrencies.toJson());
        return json;
    }

    /** @return null when {@code json} is null. */
    public static TONTransactionTraceActionCallContractDetails fromJson(JSONObject json) {
        if (json == null) {
            return null;
        }
        TONTransactionTraceActionCallContractDetails out = new TONTransactionTraceActionCallContractDetails();
        out.destination = TonApiJson.optString(json, "destination");
        out.opcode = TonApiJson.optString(json, "opcode");
        out.source = TonApiJson.optString(json, "source");
        out.value = TonApiJson.optString(json, "value");
        out.valueExtraCurrencies = TONExtraCurrencies.fromJson(TonApiJson.optObject(json, "valueExtraCurrencies"));
        return out;
    }

    @Override
    public String toString() {
        return toJson().toString();
    }
}
