//
// twk-bundlec — compile the JS bundle to QuickJS bytecode at build time.
//
// Usage: twk-bundlec <in.js> <out.h> [symbol]
//
// Each client otherwise re-parses ~1.7MB of JS on startup. Precompiling moves the
// parse to build time; the runtime only deserializes (JS_ReadObject) and runs.
//
// The output is tied to this exact QuickJS build, so the tool is built from the
// same vendored submodule and run as part of the build. When cross-compiling the
// tool cannot run on the build host for the target, so the core keeps the source
// path as a fallback (see TWK_BUNDLE_BYTECODE).
//
#include <cstdio>
#include <cstdlib>
#include <string>
#include <vector>

#include "quickjs.h"
#include "util/base64.h"

static bool read_file(const char* path, std::string& out) {
    FILE* f = std::fopen(path, "rb");
    if (f == nullptr) {
        return false;
    }
    std::fseek(f, 0, SEEK_END);
    long size = std::ftell(f);
    std::fseek(f, 0, SEEK_SET);
    out.resize(static_cast<size_t>(size));
    size_t got = std::fread(&out[0], 1, out.size(), f);
    std::fclose(f);
    return got == out.size();
}

int main(int argc, char** argv) {
    if (argc < 3) {
        std::fprintf(stderr, "usage: twk-bundlec <in.js> <out.h> [symbol]\n");
        return 2;
    }
    const char* in_path = argv[1];
    const char* out_path = argv[2];
    const char* symbol = argc > 3 ? argv[3] : "twk_bundle_bc";

    std::string source;
    if (!read_file(in_path, source)) {
        std::fprintf(stderr, "twk-bundlec: cannot read %s\n", in_path);
        return 1;
    }

    JSRuntime* rt = JS_NewRuntime();
    JSContext* ctx = JS_NewContext(rt);

    // Compile only: produces the global-code function object without running it
    // (the bundle references host globals that only exist at runtime).
    JSValue fn = JS_Eval(ctx, source.c_str(), source.size(), "<bundle>",
                         JS_EVAL_TYPE_GLOBAL | JS_EVAL_FLAG_COMPILE_ONLY);
    if (JS_IsException(fn)) {
        JSValue exc = JS_GetException(ctx);
        const char* msg = JS_ToCString(ctx, exc);
        std::fprintf(stderr, "twk-bundlec: compile failed: %s\n", msg ? msg : "(unknown)");
        if (msg != nullptr) {
            JS_FreeCString(ctx, msg);
        }
        JS_FreeValue(ctx, exc);
        JS_FreeValue(ctx, fn);
        JS_FreeContext(ctx);
        JS_FreeRuntime(rt);
        return 1;
    }

    size_t bc_len = 0;
    uint8_t* bc = JS_WriteObject(ctx, &bc_len, fn,
                                 JS_WRITE_OBJ_BYTECODE | JS_WRITE_OBJ_STRIP_SOURCE | JS_WRITE_OBJ_STRIP_DEBUG);
    JS_FreeValue(ctx, fn);
    if (bc == nullptr) {
        std::fprintf(stderr, "twk-bundlec: JS_WriteObject failed\n");
        JS_FreeContext(ctx);
        JS_FreeRuntime(rt);
        return 1;
    }

    // Emit as base64 string literals: fast for the compiler to ingest, unlike a
    // multi-MB byte-array initializer.
    std::string b64 = twk::base64::encode(bc, bc_len);
    js_free(ctx, bc);

    FILE* out = std::fopen(out_path, "wb");
    if (out == nullptr) {
        std::fprintf(stderr, "twk-bundlec: cannot write %s\n", out_path);
        JS_FreeContext(ctx);
        JS_FreeRuntime(rt);
        return 1;
    }
    std::fprintf(out, "// Generated by twk-bundlec from %s. Do not edit.\n", in_path);
    std::fprintf(out, "static const char %s[] =\n", symbol);
    const size_t kChunk = 20000; // under the MSVC 65535-byte string-literal limit
    for (size_t i = 0; i < b64.size(); i += kChunk) {
        std::fprintf(out, "\"%s\"\n", b64.substr(i, kChunk).c_str());
    }
    std::fprintf(out, ";\nstatic const unsigned long %s_len = %luul;\n", symbol,
                 static_cast<unsigned long>(b64.size()));
    std::fclose(out);

    std::printf("twk-bundlec: %s (%zu bytes JS) -> %s (%zu bytes bytecode)\n", in_path, source.size(), out_path,
                bc_len);

    JS_FreeContext(ctx);
    JS_FreeRuntime(rt);
    return 0;
}
